// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// AUTH.LOGIN.ACCOUNT_LOCKED — Account is temporarily locked
	AuthLoginAccountLocked = &Spec{Code: "AUTH.LOGIN.ACCOUNT_LOCKED", Status: 423, Message: "Account is temporarily locked"}
	// AUTH.LOGIN.INVALID_CREDENTIALS — Invalid email or password
	AuthLoginInvalidCredentials = &Spec{Code: "AUTH.LOGIN.INVALID_CREDENTIALS", Status: 401, Message: "Invalid email or password"}
	// AUTH.LOGIN.RATE_LIMITED_AFTER_RETRIES — Too many failed login attempts
	AuthLoginRateLimitedAfterRetries = &Spec{Code: "AUTH.LOGIN.RATE_LIMITED_AFTER_RETRIES", Status: 429, Message: "Too many failed login attempts"}
	// AUTH.MAGIC_LINK.ALREADY_USED — This magic link has already been used
	AuthMagicLinkAlreadyUsed = &Spec{Code: "AUTH.MAGIC_LINK.ALREADY_USED", Status: 409, Message: "This magic link has already been used"}
	// AUTH.MAGIC_LINK.EMAIL_NOT_FOUND — No account found for this email address
	AuthMagicLinkEmailNotFound = &Spec{Code: "AUTH.MAGIC_LINK.EMAIL_NOT_FOUND", Status: 404, Message: "No account found for this email address"}
	// AUTH.MAGIC_LINK.INVALID_OR_EXPIRED — Magic link is invalid or has expired
	AuthMagicLinkInvalidOrExpired = &Spec{Code: "AUTH.MAGIC_LINK.INVALID_OR_EXPIRED", Status: 401, Message: "Magic link is invalid or has expired"}
	// AUTH.OIDC.EMAIL_NOT_VERIFIED — Email address is not verified by the identity provider
	AuthOidcEmailNotVerified = &Spec{Code: "AUTH.OIDC.EMAIL_NOT_VERIFIED", Status: 403, Message: "Email address is not verified by the identity provider"}
	// AUTH.OIDC.GITHUB_NOT_CONFIGURED — GitHub login is not configured
	AuthOidcGithubNotConfigured = &Spec{Code: "AUTH.OIDC.GITHUB_NOT_CONFIGURED", Status: 503, Message: "GitHub login is not configured"}
	// AUTH.OIDC.ID_TOKEN_INVALID — OIDC ID token is invalid
	AuthOidcIdTokenInvalid = &Spec{Code: "AUTH.OIDC.ID_TOKEN_INVALID", Status: 401, Message: "OIDC ID token is invalid"}
	// AUTH.OIDC.MICROSOFT_NOT_CONFIGURED — Microsoft login is not configured
	AuthOidcMicrosoftNotConfigured = &Spec{Code: "AUTH.OIDC.MICROSOFT_NOT_CONFIGURED", Status: 503, Message: "Microsoft login is not configured"}
	// AUTH.OIDC.NONCE_MISMATCH — OIDC nonce does not match
	AuthOidcNonceMismatch = &Spec{Code: "AUTH.OIDC.NONCE_MISMATCH", Status: 400, Message: "OIDC nonce does not match"}
	// AUTH.OIDC.PROVIDER_UNREACHABLE — OIDC provider is unreachable
	AuthOidcProviderUnreachable = &Spec{Code: "AUTH.OIDC.PROVIDER_UNREACHABLE", Status: 502, Message: "OIDC provider is unreachable"}
	// AUTH.OIDC.STATE_MISMATCH — OIDC state parameter does not match
	AuthOidcStateMismatch = &Spec{Code: "AUTH.OIDC.STATE_MISMATCH", Status: 400, Message: "OIDC state parameter does not match"}
	// AUTH.PASSWORD.CURRENT_MISMATCH — Current password is incorrect
	AuthPasswordCurrentMismatch = &Spec{Code: "AUTH.PASSWORD.CURRENT_MISMATCH", Status: 401, Message: "Current password is incorrect"}
	// AUTH.PASSWORD.NO_LOCAL_IDENTITY — Account has no local password to change
	AuthPasswordNoLocalIdentity = &Spec{Code: "AUTH.PASSWORD.NO_LOCAL_IDENTITY", Status: 409, Message: "Account has no local password to change"}
	// AUTH.PASSWORD.TOO_WEAK — Password does not meet strength requirements
	AuthPasswordTooWeak = &Spec{Code: "AUTH.PASSWORD.TOO_WEAK", Status: 422, Message: "Password does not meet strength requirements"}
	// AUTH.PAT.EXPIRED — Personal access token has expired
	AuthPatExpired = &Spec{Code: "AUTH.PAT.EXPIRED", Status: 401, Message: "Personal access token has expired"}
	// AUTH.PAT.TOKEN_UNKNOWN — Personal access token is invalid
	AuthPatTokenUnknown = &Spec{Code: "AUTH.PAT.TOKEN_UNKNOWN", Status: 401, Message: "Personal access token is invalid"}
	// AUTH.REGISTER.EMAIL_ALREADY_TAKEN — Email address is already registered
	AuthRegisterEmailAlreadyTaken = &Spec{Code: "AUTH.REGISTER.EMAIL_ALREADY_TAKEN", Status: 409, Message: "Email address is already registered"}
	// AUTH.REGISTER.INSTANCE_REGISTRATION_DISABLED — Self-service registration is disabled on this instance
	AuthRegisterInstanceRegistrationDisabled = &Spec{Code: "AUTH.REGISTER.INSTANCE_REGISTRATION_DISABLED", Status: 403, Message: "Self-service registration is disabled on this instance"}
	// AUTH.REGISTER.PASSWORD_TOO_WEAK — Password does not meet strength requirements
	AuthRegisterPasswordTooWeak = &Spec{Code: "AUTH.REGISTER.PASSWORD_TOO_WEAK", Status: 422, Message: "Password does not meet strength requirements"}
	// AUTH.SESSION.EXPIRED — Session has expired
	AuthSessionExpired = &Spec{Code: "AUTH.SESSION.EXPIRED", Status: 401, Message: "Session has expired"}
	// AUTH.SESSION.REVOKED — Session has been revoked
	AuthSessionRevoked = &Spec{Code: "AUTH.SESSION.REVOKED", Status: 401, Message: "Session has been revoked"}
	// AUTH.TOKEN.MISSING_OR_MALFORMED — Missing or invalid authentication token
	AuthTokenMissingOrMalformed = &Spec{Code: "AUTH.TOKEN.MISSING_OR_MALFORMED", Status: 401, Message: "Missing or invalid authentication token"}
	// AUTH.TOKEN.REFRESH_EXPIRED — Refresh token has expired
	AuthTokenRefreshExpired = &Spec{Code: "AUTH.TOKEN.REFRESH_EXPIRED", Status: 401, Message: "Refresh token has expired"}
	// AUTH.TOKEN.REFRESH_INVALID — Refresh token is invalid
	AuthTokenRefreshInvalid = &Spec{Code: "AUTH.TOKEN.REFRESH_INVALID", Status: 401, Message: "Refresh token is invalid"}
	// AUTH.TOKEN.SIGNATURE_INVALID — Token signature is invalid
	AuthTokenSignatureInvalid = &Spec{Code: "AUTH.TOKEN.SIGNATURE_INVALID", Status: 401, Message: "Token signature is invalid"}
	// AUTH.TOTP.ALREADY_ENROLLED — Two-factor authentication is already enabled
	AuthTotpAlreadyEnrolled = &Spec{Code: "AUTH.TOTP.ALREADY_ENROLLED", Status: 409, Message: "Two-factor authentication is already enabled"}
	// AUTH.TOTP.CODE_MISMATCH — Two-factor authentication code is incorrect
	AuthTotpCodeMismatch = &Spec{Code: "AUTH.TOTP.CODE_MISMATCH", Status: 401, Message: "Two-factor authentication code is incorrect"}
	// AUTH.TOTP.CODE_REQUIRED — Two-factor authentication code is required
	AuthTotpCodeRequired = &Spec{Code: "AUTH.TOTP.CODE_REQUIRED", Status: 401, Message: "Two-factor authentication code is required"}
	// AUTH.TOTP.NOT_CONFIGURED — Two-factor authentication is not available on this server
	AuthTotpNotConfigured = &Spec{Code: "AUTH.TOTP.NOT_CONFIGURED", Status: 503, Message: "Two-factor authentication is not available on this server"}
	// AUTH.TOTP.NOT_ENROLLED — Two-factor authentication is not enabled
	AuthTotpNotEnrolled = &Spec{Code: "AUTH.TOTP.NOT_ENROLLED", Status: 409, Message: "Two-factor authentication is not enabled"}
	// AUTH.TOTP.RECOVERY_CODE_INVALID — Recovery code is invalid
	AuthTotpRecoveryCodeInvalid = &Spec{Code: "AUTH.TOTP.RECOVERY_CODE_INVALID", Status: 401, Message: "Recovery code is invalid"}
	// AUTH.TOTP.RECOVERY_CODE_REQUIRED — Either a TOTP code or a recovery code is required
	AuthTotpRecoveryCodeRequired = &Spec{Code: "AUTH.TOTP.RECOVERY_CODE_REQUIRED", Status: 400, Message: "Either a TOTP code or a recovery code is required"}
)
