// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// CALENDAR.ATTACHMENT.LIST_QUERY_INTERRUPTED — Could not retrieve attachments
	CalendarAttachmentListQueryInterrupted = &Spec{Code: "CALENDAR.ATTACHMENT.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve attachments"}
	// CALENDAR.ATTACHMENT.NOT_FOUND — Attachment not found
	CalendarAttachmentNotFound = &Spec{Code: "CALENDAR.ATTACHMENT.NOT_FOUND", Status: 404, Message: "Attachment not found"}
	// CALENDAR.ATTACHMENT.STORE_DELETE_INTERRUPTED — Could not delete attachment
	CalendarAttachmentStoreDeleteInterrupted = &Spec{Code: "CALENDAR.ATTACHMENT.STORE_DELETE_INTERRUPTED", Status: 500, Message: "Could not delete attachment"}
	// CALENDAR.ATTACHMENT.STORE_READ_INTERRUPTED — Could not find attachment
	CalendarAttachmentStoreReadInterrupted = &Spec{Code: "CALENDAR.ATTACHMENT.STORE_READ_INTERRUPTED", Status: 500, Message: "Could not find attachment"}
	// CALENDAR.ATTACHMENT.STORE_WRITE_INTERRUPTED — Could not save attachment
	CalendarAttachmentStoreWriteInterrupted = &Spec{Code: "CALENDAR.ATTACHMENT.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not save attachment"}
	// CALENDAR.ATTACHMENT.UPLOADER_OR_OWNER_REQUIRED — Only the uploader or calendar owner can delete this attachment
	CalendarAttachmentUploaderOrOwnerRequired = &Spec{Code: "CALENDAR.ATTACHMENT.UPLOADER_OR_OWNER_REQUIRED", Status: 403, Message: "Only the uploader or calendar owner can delete this attachment"}
	// CALENDAR.ATTENDEE.CAN_EDIT_UPDATE_INTERRUPTED — Could not update edit permission
	CalendarAttendeeCanEditUpdateInterrupted = &Spec{Code: "CALENDAR.ATTENDEE.CAN_EDIT_UPDATE_INTERRUPTED", Status: 500, Message: "Could not update edit permission"}
	// CALENDAR.ATTENDEE.OWNER_REQUIRED_TO_TOGGLE_EDIT — Only the event owner can change edit permissions
	CalendarAttendeeOwnerRequiredToToggleEdit = &Spec{Code: "CALENDAR.ATTENDEE.OWNER_REQUIRED_TO_TOGGLE_EDIT", Status: 403, Message: "Only the event owner can change edit permissions"}
	// CALENDAR.ATTENDEE.RSVP_UPDATE_INTERRUPTED — Could not update RSVP
	CalendarAttendeeRsvpUpdateInterrupted = &Spec{Code: "CALENDAR.ATTENDEE.RSVP_UPDATE_INTERRUPTED", Status: 500, Message: "Could not update RSVP"}
	// CALENDAR.ATTENDEE.STORE_REMOVE_INTERRUPTED — Could not remove attendee
	CalendarAttendeeStoreRemoveInterrupted = &Spec{Code: "CALENDAR.ATTENDEE.STORE_REMOVE_INTERRUPTED", Status: 500, Message: "Could not remove attendee"}
	// CALENDAR.ATTENDEE.USER_ID_MALFORMED — Invalid user ID
	CalendarAttendeeUserIdMalformed = &Spec{Code: "CALENDAR.ATTENDEE.USER_ID_MALFORMED", Status: 400, Message: "Invalid user ID"}
	// CALENDAR.ATTENDEE.USER_NOT_FOUND — User not found
	CalendarAttendeeUserNotFound = &Spec{Code: "CALENDAR.ATTENDEE.USER_NOT_FOUND", Status: 404, Message: "User not found"}
	// CALENDAR.CALENDAR.ACCESS_DENIED — You do not have access to this calendar
	CalendarCalendarAccessDenied = &Spec{Code: "CALENDAR.CALENDAR.ACCESS_DENIED", Status: 403, Message: "You do not have access to this calendar"}
	// CALENDAR.CALENDAR.LIST_QUERY_INTERRUPTED — Could not retrieve calendars
	CalendarCalendarListQueryInterrupted = &Spec{Code: "CALENDAR.CALENDAR.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve calendars"}
	// CALENDAR.CALENDAR.NOT_FOUND — Calendar not found
	CalendarCalendarNotFound = &Spec{Code: "CALENDAR.CALENDAR.NOT_FOUND", Status: 404, Message: "Calendar not found"}
	// CALENDAR.CALENDAR.OWNER_ROLE_REQUIRED — Only calendar owners can perform this action
	CalendarCalendarOwnerRoleRequired = &Spec{Code: "CALENDAR.CALENDAR.OWNER_ROLE_REQUIRED", Status: 403, Message: "Only calendar owners can perform this action"}
	// CALENDAR.CALENDAR.STORE_DELETE_INTERRUPTED — Could not delete calendar
	CalendarCalendarStoreDeleteInterrupted = &Spec{Code: "CALENDAR.CALENDAR.STORE_DELETE_INTERRUPTED", Status: 500, Message: "Could not delete calendar"}
	// CALENDAR.CALENDAR.STORE_READ_INTERRUPTED — Could not read calendar after update
	CalendarCalendarStoreReadInterrupted = &Spec{Code: "CALENDAR.CALENDAR.STORE_READ_INTERRUPTED", Status: 500, Message: "Could not read calendar after update"}
	// CALENDAR.CALENDAR.STORE_WRITE_INTERRUPTED — Could not save calendar
	CalendarCalendarStoreWriteInterrupted = &Spec{Code: "CALENDAR.CALENDAR.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not save calendar"}
	// CALENDAR.CHECKLIST.ITEM_NOT_FOUND — Checklist item not found
	CalendarChecklistItemNotFound = &Spec{Code: "CALENDAR.CHECKLIST.ITEM_NOT_FOUND", Status: 404, Message: "Checklist item not found"}
	// CALENDAR.CHECKLIST.LIST_QUERY_INTERRUPTED — Could not retrieve checklist items
	CalendarChecklistListQueryInterrupted = &Spec{Code: "CALENDAR.CHECKLIST.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve checklist items"}
	// CALENDAR.CHECKLIST.STORE_DELETE_INTERRUPTED — Could not delete checklist item
	CalendarChecklistStoreDeleteInterrupted = &Spec{Code: "CALENDAR.CHECKLIST.STORE_DELETE_INTERRUPTED", Status: 500, Message: "Could not delete checklist item"}
	// CALENDAR.CHECKLIST.STORE_WRITE_INTERRUPTED — Could not save checklist item
	CalendarChecklistStoreWriteInterrupted = &Spec{Code: "CALENDAR.CHECKLIST.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not save checklist item"}
	// CALENDAR.COMMENT.AUTHOR_OR_OWNER_REQUIRED — Only the comment author or calendar owner can delete this comment
	CalendarCommentAuthorOrOwnerRequired = &Spec{Code: "CALENDAR.COMMENT.AUTHOR_OR_OWNER_REQUIRED", Status: 403, Message: "Only the comment author or calendar owner can delete this comment"}
	// CALENDAR.COMMENT.LIST_QUERY_INTERRUPTED — Could not retrieve comments
	CalendarCommentListQueryInterrupted = &Spec{Code: "CALENDAR.COMMENT.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve comments"}
	// CALENDAR.COMMENT.NOT_FOUND — Comment not found
	CalendarCommentNotFound = &Spec{Code: "CALENDAR.COMMENT.NOT_FOUND", Status: 404, Message: "Comment not found"}
	// CALENDAR.COMMENT.STORE_DELETE_INTERRUPTED — Could not delete comment
	CalendarCommentStoreDeleteInterrupted = &Spec{Code: "CALENDAR.COMMENT.STORE_DELETE_INTERRUPTED", Status: 500, Message: "Could not delete comment"}
	// CALENDAR.COMMENT.STORE_READ_INTERRUPTED — Could not find comment
	CalendarCommentStoreReadInterrupted = &Spec{Code: "CALENDAR.COMMENT.STORE_READ_INTERRUPTED", Status: 500, Message: "Could not find comment"}
	// CALENDAR.COMMENT.STORE_WRITE_INTERRUPTED — Could not save comment
	CalendarCommentStoreWriteInterrupted = &Spec{Code: "CALENDAR.COMMENT.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not save comment"}
	// CALENDAR.EVENT.DATE_RANGE_UNPARSEABLE — Could not parse date or datetime parameter
	CalendarEventDateRangeUnparseable = &Spec{Code: "CALENDAR.EVENT.DATE_RANGE_UNPARSEABLE", Status: 422, Message: "Could not parse date or datetime parameter"}
	// CALENDAR.EVENT.EDIT_PERMISSION_REQUIRED — You do not have permission to edit this event
	CalendarEventEditPermissionRequired = &Spec{Code: "CALENDAR.EVENT.EDIT_PERMISSION_REQUIRED", Status: 403, Message: "You do not have permission to edit this event"}
	// CALENDAR.EVENT.LIST_QUERY_INTERRUPTED — Could not retrieve events
	CalendarEventListQueryInterrupted = &Spec{Code: "CALENDAR.EVENT.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve events"}
	// CALENDAR.EVENT.NOT_FOUND — Event not found
	CalendarEventNotFound = &Spec{Code: "CALENDAR.EVENT.NOT_FOUND", Status: 404, Message: "Event not found"}
	// CALENDAR.EVENT.OWNER_USER_ID_MALFORMED — Invalid ownerUserId
	CalendarEventOwnerUserIdMalformed = &Spec{Code: "CALENDAR.EVENT.OWNER_USER_ID_MALFORMED", Status: 400, Message: "Invalid ownerUserId"}
	// CALENDAR.EVENT.OWNER_USER_NOT_FOUND — Owner user not found
	CalendarEventOwnerUserNotFound = &Spec{Code: "CALENDAR.EVENT.OWNER_USER_NOT_FOUND", Status: 400, Message: "Owner user not found"}
	// CALENDAR.EVENT.OWNER_USER_RESOLVE_INTERRUPTED — Could not resolve owner user
	CalendarEventOwnerUserResolveInterrupted = &Spec{Code: "CALENDAR.EVENT.OWNER_USER_RESOLVE_INTERRUPTED", Status: 500, Message: "Could not resolve owner user"}
	// CALENDAR.EVENT.START_END_PAIR_REQUIRED — startAt and endAt must be provided together
	CalendarEventStartEndPairRequired = &Spec{Code: "CALENDAR.EVENT.START_END_PAIR_REQUIRED", Status: 422, Message: "startAt and endAt must be provided together"}
	// CALENDAR.EVENT.STORE_DELETE_INTERRUPTED — Could not delete event
	CalendarEventStoreDeleteInterrupted = &Spec{Code: "CALENDAR.EVENT.STORE_DELETE_INTERRUPTED", Status: 500, Message: "Could not delete event"}
	// CALENDAR.EVENT.STORE_READ_INTERRUPTED — Could not read event
	CalendarEventStoreReadInterrupted = &Spec{Code: "CALENDAR.EVENT.STORE_READ_INTERRUPTED", Status: 500, Message: "Could not read event"}
	// CALENDAR.EVENT.STORE_WRITE_INTERRUPTED — Could not save event
	CalendarEventStoreWriteInterrupted = &Spec{Code: "CALENDAR.EVENT.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not save event"}
	// CALENDAR.INVITE.EMAIL_SEND_INTERRUPTED — Could not send invite email
	CalendarInviteEmailSendInterrupted = &Spec{Code: "CALENDAR.INVITE.EMAIL_SEND_INTERRUPTED", Status: 500, Message: "Could not send invite email"}
	// CALENDAR.INVITE.LIST_QUERY_INTERRUPTED — Could not retrieve invites
	CalendarInviteListQueryInterrupted = &Spec{Code: "CALENDAR.INVITE.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve invites"}
	// CALENDAR.INVITE.NOT_FOUND — Invite not found or expired
	CalendarInviteNotFound = &Spec{Code: "CALENDAR.INVITE.NOT_FOUND", Status: 404, Message: "Invite not found or expired"}
	// CALENDAR.INVITE.STORE_LOOKUP_INTERRUPTED — Could not look up invite
	CalendarInviteStoreLookupInterrupted = &Spec{Code: "CALENDAR.INVITE.STORE_LOOKUP_INTERRUPTED", Status: 500, Message: "Could not look up invite"}
	// CALENDAR.INVITE.STORE_REVOKE_INTERRUPTED — Could not revoke invite
	CalendarInviteStoreRevokeInterrupted = &Spec{Code: "CALENDAR.INVITE.STORE_REVOKE_INTERRUPTED", Status: 500, Message: "Could not revoke invite"}
	// CALENDAR.INVITE.STORE_WRITE_INTERRUPTED — Could not save invite
	CalendarInviteStoreWriteInterrupted = &Spec{Code: "CALENDAR.INVITE.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not save invite"}
	// CALENDAR.INVITE.TOKEN_GENERATE_INTERRUPTED — Could not generate invite token
	CalendarInviteTokenGenerateInterrupted = &Spec{Code: "CALENDAR.INVITE.TOKEN_GENERATE_INTERRUPTED", Status: 500, Message: "Could not generate invite token"}
	// CALENDAR.MEMBER.ALREADY_SUBSCRIBED — User is already a member of this calendar
	CalendarMemberAlreadySubscribed = &Spec{Code: "CALENDAR.MEMBER.ALREADY_SUBSCRIBED", Status: 409, Message: "User is already a member of this calendar"}
	// CALENDAR.MEMBER.LAST_OWNER_REMOVAL_BLOCKED — Cannot remove the last owner of a calendar
	CalendarMemberLastOwnerRemovalBlocked = &Spec{Code: "CALENDAR.MEMBER.LAST_OWNER_REMOVAL_BLOCKED", Status: 409, Message: "Cannot remove the last owner of a calendar"}
	// CALENDAR.MEMBER.LIST_QUERY_INTERRUPTED — Could not retrieve members
	CalendarMemberListQueryInterrupted = &Spec{Code: "CALENDAR.MEMBER.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve members"}
	// CALENDAR.MEMBER.NOT_FOUND — Member not found
	CalendarMemberNotFound = &Spec{Code: "CALENDAR.MEMBER.NOT_FOUND", Status: 404, Message: "Member not found"}
	// CALENDAR.MEMBER.OWNER_COUNT_QUERY_INTERRUPTED — Could not verify owner count
	CalendarMemberOwnerCountQueryInterrupted = &Spec{Code: "CALENDAR.MEMBER.OWNER_COUNT_QUERY_INTERRUPTED", Status: 500, Message: "Could not verify owner count"}
	// CALENDAR.MEMBER.STORE_READ_INTERRUPTED — Could not look up member
	CalendarMemberStoreReadInterrupted = &Spec{Code: "CALENDAR.MEMBER.STORE_READ_INTERRUPTED", Status: 500, Message: "Could not look up member"}
	// CALENDAR.MEMBER.STORE_REMOVE_INTERRUPTED — Could not remove member
	CalendarMemberStoreRemoveInterrupted = &Spec{Code: "CALENDAR.MEMBER.STORE_REMOVE_INTERRUPTED", Status: 500, Message: "Could not remove member"}
	// CALENDAR.MEMBER.STORE_ROLE_UPDATE_INTERRUPTED — Could not update member role
	CalendarMemberStoreRoleUpdateInterrupted = &Spec{Code: "CALENDAR.MEMBER.STORE_ROLE_UPDATE_INTERRUPTED", Status: 500, Message: "Could not update member role"}
	// CALENDAR.MEMBER.STORE_WRITE_INTERRUPTED — Could not add member
	CalendarMemberStoreWriteInterrupted = &Spec{Code: "CALENDAR.MEMBER.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not add member"}
	// CALENDAR.MEMBER.USER_ID_MALFORMED — Invalid user ID
	CalendarMemberUserIdMalformed = &Spec{Code: "CALENDAR.MEMBER.USER_ID_MALFORMED", Status: 400, Message: "Invalid user ID"}
	// CALENDAR.MEMBER.USER_NOT_FOUND — User not found
	CalendarMemberUserNotFound = &Spec{Code: "CALENDAR.MEMBER.USER_NOT_FOUND", Status: 404, Message: "User not found"}
	// CALENDAR.MEMO.LIST_QUERY_INTERRUPTED — Could not retrieve memos
	CalendarMemoListQueryInterrupted = &Spec{Code: "CALENDAR.MEMO.LIST_QUERY_INTERRUPTED", Status: 500, Message: "Could not retrieve memos"}
	// CALENDAR.MEMO.NOT_FOUND — Memo not found
	CalendarMemoNotFound = &Spec{Code: "CALENDAR.MEMO.NOT_FOUND", Status: 404, Message: "Memo not found"}
	// CALENDAR.MEMO.STORE_DELETE_INTERRUPTED — Could not delete memo
	CalendarMemoStoreDeleteInterrupted = &Spec{Code: "CALENDAR.MEMO.STORE_DELETE_INTERRUPTED", Status: 500, Message: "Could not delete memo"}
	// CALENDAR.MEMO.STORE_READ_INTERRUPTED — Could not find memo
	CalendarMemoStoreReadInterrupted = &Spec{Code: "CALENDAR.MEMO.STORE_READ_INTERRUPTED", Status: 500, Message: "Could not find memo"}
	// CALENDAR.MEMO.STORE_WRITE_INTERRUPTED — Could not save memo
	CalendarMemoStoreWriteInterrupted = &Spec{Code: "CALENDAR.MEMO.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not save memo"}
	// CALENDAR.SMART_CREATE.TEXT_UNPARSEABLE — Could not parse event from text
	CalendarSmartCreateTextUnparseable = &Spec{Code: "CALENDAR.SMART_CREATE.TEXT_UNPARSEABLE", Status: 422, Message: "Could not parse event from text"}
	// CALENDAR.SUBSCRIPTION.COUNTRY_INVALID — Country code is invalid or not supported
	CalendarSubscriptionCountryInvalid = &Spec{Code: "CALENDAR.SUBSCRIPTION.COUNTRY_INVALID", Status: 400, Message: "Country code is invalid or not supported"}
	// CALENDAR.SUBSCRIPTION.MEMBERSHIP_CHECK_INTERRUPTED — Could not verify membership
	CalendarSubscriptionMembershipCheckInterrupted = &Spec{Code: "CALENDAR.SUBSCRIPTION.MEMBERSHIP_CHECK_INTERRUPTED", Status: 500, Message: "Could not verify membership"}
	// CALENDAR.SUBSCRIPTION.STORE_WRITE_INTERRUPTED — Could not create calendar subscription
	CalendarSubscriptionStoreWriteInterrupted = &Spec{Code: "CALENDAR.SUBSCRIPTION.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not create calendar subscription"}
	// CALENDAR.TASK_SYNC.STORE_WRITE_INTERRUPTED — Could not create event from task
	CalendarTaskSyncStoreWriteInterrupted = &Spec{Code: "CALENDAR.TASK_SYNC.STORE_WRITE_INTERRUPTED", Status: 500, Message: "Could not create event from task"}
	// CALENDAR.TASK_SYNC.TASK_ID_MALFORMED — Invalid taskId format
	CalendarTaskSyncTaskIdMalformed = &Spec{Code: "CALENDAR.TASK_SYNC.TASK_ID_MALFORMED", Status: 400, Message: "Invalid taskId format"}
	// CALENDAR.TASK_SYNC.TASK_LOOKUP_INTERRUPTED — Could not look up task
	CalendarTaskSyncTaskLookupInterrupted = &Spec{Code: "CALENDAR.TASK_SYNC.TASK_LOOKUP_INTERRUPTED", Status: 500, Message: "Could not look up task"}
	// CALENDAR.TASK_SYNC.TASK_NOT_FOUND — Task not found
	CalendarTaskSyncTaskNotFound = &Spec{Code: "CALENDAR.TASK_SYNC.TASK_NOT_FOUND", Status: 404, Message: "Task not found"}
	// CALENDAR.TASK_SYNC.TIMEZONE_UNRECOGNIZED — Unrecognized timezone
	CalendarTaskSyncTimezoneUnrecognized = &Spec{Code: "CALENDAR.TASK_SYNC.TIMEZONE_UNRECOGNIZED", Status: 400, Message: "Unrecognized timezone"}
	// CALENDAR.TASK_SYNC.VIEWER_ROLE_INSUFFICIENT — Viewers cannot create events
	CalendarTaskSyncViewerRoleInsufficient = &Spec{Code: "CALENDAR.TASK_SYNC.VIEWER_ROLE_INSUFFICIENT", Status: 403, Message: "Viewers cannot create events"}
	// CALENDAR.USER_PROFILE.LOOKUP_INTERRUPTED — Could not retrieve user profile
	CalendarUserProfileLookupInterrupted = &Spec{Code: "CALENDAR.USER_PROFILE.LOOKUP_INTERRUPTED", Status: 500, Message: "Could not retrieve user profile"}
	// CALENDAR.USER_PROFILE.USER_LOOKUP_INTERRUPTED — Could not look up user
	CalendarUserProfileUserLookupInterrupted = &Spec{Code: "CALENDAR.USER_PROFILE.USER_LOOKUP_INTERRUPTED", Status: 500, Message: "Could not look up user"}
	// CALENDAR.WORKSPACE.NOT_FOUND — Workspace not found
	CalendarWorkspaceNotFound = &Spec{Code: "CALENDAR.WORKSPACE.NOT_FOUND", Status: 404, Message: "Workspace not found"}
)
