// Authorization suite for the event-side link routes.
//
// An event id is reachable by every member of the workspace it lives in,
// but the calendar it sits on has an audience of its own: a workspace
// holds calendars whose member lists do not coincide. Listing an event's
// linked tasks, and attaching a task to an event, therefore both take a
// live grant on that calendar. The floor is membership at any role
// rather than the editor floor a change to the calendar's contents
// takes — a calendar's contents are visible to all of its members.
//
// A caller without that grant is answered exactly as one who named an id
// matching nothing. The request names an event and never names a
// calendar, so a distinct refusal would confirm that the id belongs to a
// live event on a calendar the caller cannot see.
package e2e

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// freshUUID returns a UUID that names nothing. It is generated by the
// database so the value is well-formed by the same rules the column
// stores, leaving the route's answer as the only variable.
func freshUUID(t *testing.T) string {
	t.Helper()
	var id string
	require.NoError(t, testDB.QueryRow(`SELECT UUID()`).Scan(&id))
	return id
}

// linkedTasksURL builds the event-side list route for a workspace.
func linkedTasksURL(wsID, evtID string) string {
	return testServerURL + "/workspaces/" + wsID + "/calendar-events/" + evtID + "/linked-tasks"
}

// linkedTasksList is the decoded list response, carrying enough of each
// row to tell which tasks reached the caller.
type linkedTasksList struct {
	Total int64 `json:"total"`
	Links []struct {
		TaskID    string `json:"taskId"`
		TaskTitle string `json:"taskTitle"`
	} `json:"links"`
}

// taskIDs collapses a list response to the task ids it carried.
func (l linkedTasksList) taskIDs() []string {
	out := make([]string, 0, len(l.Links))
	for _, link := range l.Links {
		out = append(out, link.TaskID)
	}
	return out
}

// TestLinkedTasksRequireCalendarMembership walks one workspace member
// through both standings on the calendar an event lives on.
//
// The member never being added to the calendar is the case that matters:
// they hold a legitimate session in the workspace, so a check that
// scopes the event id to the workspace and stops there is satisfied, and
// they can confirm that an id names a live event on a calendar they
// cannot open and read the shape of its link set.
//
// The second leg grants viewer to the same user, so a regression that
// simply refuses everybody cannot pass — and the viewer leg doubles as
// the proof that closing this did not widen anything, since the private
// task linked to the same event must still be filtered out of what they
// see.
func TestLinkedTasksRequireCalendarMembership(t *testing.T) {
	bootstrap(t)
	t.Parallel()

	host := newTenant(t)
	outsider := inviteAndJoinWorkspace(t, host)

	calID := createCalendarMut(t, host, "Linked Tasks ACL Cal")
	evtID := createEventMut(t, host, calID, "Board seat negotiation")

	publicTask := createTaskWithVisibility(t, host, "Draft the term sheet", "public")
	privateTask := createTaskWithVisibility(t, host, "Sound out the outgoing director", "private")
	linkTaskToEventContributesTo(t, publicTask, evtID)
	linkTaskToEventContributesTo(t, privateTask, evtID)

	listURL := linkedTasksURL(host.WorkspacePublicID, evtID)

	// No membership at all: the route answers as though the event were
	// not there.
	status, body := doJSONStatus(t, http.MethodGet, listURL, outsider.AccessToken, nil)
	requireDenied(t, status, body, http.StatusNotFound, "CALENDAR.EVENT.NOT_FOUND",
		"linked-tasks for a workspace member holding no grant on the calendar")

	// Granting viewer is what changes the answer: a calendar's contents
	// are visible to every one of its members, so the read floor is
	// membership rather than the editor floor a write takes.
	addCalendarMemberWithRole(t, host, calID, outsider.Email, "viewer")

	var seen linkedTasksList
	doJSON(t, http.MethodGet, listURL, outsider.AccessToken, nil, &seen)
	assert.Equal(t, []string{publicTask}, seen.taskIDs(),
		"a calendar viewer must see the links whose tasks they may read")
	assert.Equal(t, int64(1), seen.Total,
		"total must count the filtered set, not every link on the event")

	// Reaching the calendar is not permission to read every task hanging
	// off it. The private task is the witness: it is linked to the same
	// event, so a handler that stopped filtering once the calendar check
	// passed would surface its title here.
	for _, link := range seen.Links {
		assert.NotEqual(t, privateTask, link.TaskID,
			"a task the viewer may not read must stay out of the link list")
		assert.NotContains(t, link.TaskTitle, "outgoing director",
			"a filtered task's title must not reach the wire")
	}

	// The host reads the same event and sees both links, so the empty
	// half above is the visibility filter at work rather than a list
	// that answers nothing to anyone.
	var hostSeen linkedTasksList
	doJSON(t, http.MethodGet, listURL, host.AccessToken, nil, &hostSeen)
	assert.ElementsMatch(t, []string{publicTask, privateTask}, hostSeen.taskIDs(),
		"the workspace owner must still see every link on the event")
	assert.Equal(t, int64(2), hostSeen.Total)
}

// TestLinkedTasksRefusalIsIndistinguishableFromAMissingEvent is the
// disclosure property stated directly: the answer a caller gets for a
// live event on a calendar they cannot reach must equal the answer they
// get for an id that names nothing.
//
// Asserting the equality rather than each response's shape separately is
// the point. Two refusals that happen to share a code today can drift to
// different statuses, different bodies, or different response times, and
// any of those hands back the existence answer the check exists to
// withhold.
func TestLinkedTasksRefusalIsIndistinguishableFromAMissingEvent(t *testing.T) {
	bootstrap(t)
	t.Parallel()

	host := newTenant(t)
	outsider := inviteAndJoinWorkspace(t, host)

	// The linked task's title is what this route puts on the wire, so it
	// is the value the refusal has to be shown withholding. The event's
	// own title is never in any answer here — asserting its absence would
	// hold just as well against a route that returns nothing at all.
	const linkedTaskTitle = "Prepare the headcount model"

	calID := createCalendarMut(t, host, "Unreachable Cal")
	evtID := createEventMut(t, host, calID, "Redundancy planning")
	taskID := createTaskWithVisibility(t, host, linkedTaskTitle, "public")
	linkTaskToEventContributesTo(t, taskID, evtID)

	unreachableStatus, unreachableBody := doJSONStatus(t, http.MethodGet,
		linkedTasksURL(host.WorkspacePublicID, evtID), outsider.AccessToken, nil)
	missingStatus, missingBody := doJSONStatus(t, http.MethodGet,
		linkedTasksURL(host.WorkspacePublicID, freshUUID(t)), outsider.AccessToken, nil)

	require.Equal(t, missingStatus, unreachableStatus,
		"a live event on an unreachable calendar must carry the status of a missing one")
	require.JSONEq(t, string(missingBody), string(unreachableBody),
		"the two refusals must be the same response; body=%s", string(unreachableBody))

	// Pinned so the pair cannot converge on something other than a
	// not-found — two identical 500s would satisfy the equality above.
	requireDenied(t, unreachableStatus, unreachableBody, http.StatusNotFound,
		"CALENDAR.EVENT.NOT_FOUND", "linked-tasks for an event on an unreachable calendar")

	// The owner of the calendar reads the same URL, which is what makes
	// the negation below a statement about the refusal: the title is
	// demonstrably carried by this route to someone allowed to have it.
	_, ownerBody := doJSONStatus(t, http.MethodGet,
		linkedTasksURL(host.WorkspacePublicID, evtID), host.AccessToken, nil)
	assert.Contains(t, string(ownerBody), linkedTaskTitle,
		"the route must carry the linked task's title to the calendar's owner")
	assert.NotContains(t, string(unreachableBody), linkedTaskTitle,
		"the refusal must not carry what the successful answer would have")
}

// TestLinkTaskToEventRequiresCalendarMembership covers the write side of
// the same lookup. Attaching a task to an event resolves that event from
// its public id, so it carries the same existence oracle — and it plants
// a row that puts the event's title, times and calendar name into the
// task's own linked-events list, which turns "this id exists" into the
// event's contents.
//
// The actor is a project editor on the host's project, which is what the
// route's task floor takes, and deliberately not a member of the
// calendar. The last leg grants viewer and repeats the link, so a
// regression that refuses every link cannot pass.
func TestLinkTaskToEventRequiresCalendarMembership(t *testing.T) {
	bootstrap(t)
	t.Parallel()

	host := newTenant(t)
	editor := seedProjectRoleMember(t, host, "editor")

	calID := createCalendarMut(t, host, "Link ACL Cal")
	evtID := createEventMut(t, host, calID, "Succession review")
	taskID := createTaskWithVisibility(t, host, "Collect the panel feedback", "public")

	linksURL := testServerURL + "/tasks/" + taskID + "/links"
	linkBody := map[string]any{"eventId": evtID, "relation": "contributes_to"}

	status, body := doJSONStatus(t, http.MethodPost, linksURL, editor.AccessToken, linkBody)
	requireDenied(t, status, body, http.StatusNotFound, "CALENDAR.EVENT.NOT_FOUND",
		"link for a task editor holding no grant on the event's calendar")

	// A refused link must leave no row: the event would otherwise reach
	// the task's linked-events list, which renders its title and the
	// name of the calendar it lives on.
	var links int
	require.NoError(t, testDB.QueryRow(
		`SELECT COUNT(*)
		   FROM task_event_links l
		   JOIN calendar_events e ON e.id = l.event_id
		  WHERE e.public_id = UUID_TO_BIN(?, 0)
		    AND l.enabled = TRUE`,
		evtID).Scan(&links))
	assert.Zero(t, links, "a refused link must not reach the table")

	status, body = doJSONStatus(t, http.MethodGet, testServerURL+"/tasks/"+taskID+"/linked-events",
		editor.AccessToken, nil)
	require.Equal(t, http.StatusOK, status, "linked-events must render; body=%s", string(body))
	assert.NotContains(t, string(body), "Succession review",
		"a refused link must leave the event's title off the task's linked-events list")

	// Membership on the calendar is what opens it.
	addCalendarMemberWithRole(t, host, calID, editor.Email, "viewer")

	var created struct {
		ID      string `json:"id"`
		EventID string `json:"eventId"`
	}
	doJSON(t, http.MethodPost, linksURL, editor.AccessToken, linkBody, &created)
	assert.NotEmpty(t, created.ID, "a calendar member must be able to link a task to its events")
	assert.Equal(t, evtID, created.EventID)
}
