package e2e

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestProjectTimelineShowsEvents verifies that GET /projects/{prjId}/timeline
// returns events generated by task operations within the project.
func TestProjectTimelineShowsEvents(t *testing.T) {
	bootstrap(t)
	t.Parallel()
	tt := newTenant(t)

	// Create a task (generates task.created event).
	var task struct {
		ID string `json:"id"`
	}
	doJSON(t, http.MethodPost, testServerURL+"/tasks", tt.AccessToken,
		map[string]any{"projectId": tt.ProjectPublicID, "title": "Timeline event source"}, &task)

	// Transition the task (generates task.transition event).
	doJSON(t, http.MethodPost,
		testServerURL+"/tasks/"+task.ID+"/transitions",
		tt.AccessToken, map[string]any{"transition": "start"}, nil)

	// Fetch project timeline.
	var timeline struct {
		Total  int64 `json:"total"`
		Events []struct {
			ID   string `json:"id"`
			Type string `json:"type"`
		} `json:"events"`
	}
	doJSON(t, http.MethodGet,
		testServerURL+"/projects/"+tt.ProjectPublicID+"/timeline",
		tt.AccessToken, nil, &timeline)

	require.Greater(t, timeline.Total, int64(0),
		"project timeline must contain events after task operations")

	// At least one event should be present.
	require.NotEmpty(t, timeline.Events)
	for _, ev := range timeline.Events {
		require.NotEmpty(t, ev.ID)
		require.NotEmpty(t, ev.Type)
	}
}

// TestProjectTimelinePagination verifies that the project timeline
// supports limit/offset pagination.
func TestProjectTimelinePagination(t *testing.T) {
	bootstrap(t)
	t.Parallel()
	tt := newTenant(t)

	// Create several tasks to generate events.
	for i := 0; i < 3; i++ {
		doJSON(t, http.MethodPost, testServerURL+"/tasks", tt.AccessToken,
			map[string]any{
				"projectId": tt.ProjectPublicID,
				"title":     "Timeline paginate " + randomHex(4),
			}, nil)
	}

	// Fetch page 1 with limit=1.
	var page1 struct {
		Total  int64 `json:"total"`
		Events []struct {
			ID string `json:"id"`
		} `json:"events"`
	}
	doJSON(t, http.MethodGet,
		testServerURL+"/projects/"+tt.ProjectPublicID+"/timeline?limit=1&offset=0",
		tt.AccessToken, nil, &page1)
	require.GreaterOrEqual(t, page1.Total, int64(3))
	require.Len(t, page1.Events, 1)

	// Fetch page 2 with limit=1, offset=1.
	var page2 struct {
		Events []struct {
			ID string `json:"id"`
		} `json:"events"`
	}
	doJSON(t, http.MethodGet,
		testServerURL+"/projects/"+tt.ProjectPublicID+"/timeline?limit=1&offset=1",
		tt.AccessToken, nil, &page2)
	require.Len(t, page2.Events, 1)

	// No overlap.
	require.NotEqual(t, page1.Events[0].ID, page2.Events[0].ID,
		"paginated timeline pages must not overlap")
}
