/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SetupRouteImport } from './routes/setup';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as LoginRouteImport } from './routes/login';
import { Route as IndexRouteImport } from './routes/index';
import { Route as MeInvitesRouteImport } from './routes/me/invites';
import { Route as InvitesAcceptRouteImport } from './routes/invites/accept';
import { Route as ShareCalTokenRouteImport } from './routes/share/cal/$token';

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const MeInvitesRoute = MeInvitesRouteImport.update({
  id: '/me/invites',
  path: '/me/invites',
  getParentRoute: () => rootRouteImport,
} as any);
const InvitesAcceptRoute = InvitesAcceptRouteImport.update({
  id: '/invites/accept',
  path: '/invites/accept',
  getParentRoute: () => rootRouteImport,
} as any);
const ShareCalTokenRoute = ShareCalTokenRouteImport.update({
  id: '/share/cal/$token',
  path: '/share/cal/$token',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/setup': typeof SetupRoute;
  '/invites/accept': typeof InvitesAcceptRoute;
  '/me/invites': typeof MeInvitesRoute;
  '/share/cal/$token': typeof ShareCalTokenRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/setup': typeof SetupRoute;
  '/invites/accept': typeof InvitesAcceptRoute;
  '/me/invites': typeof MeInvitesRoute;
  '/share/cal/$token': typeof ShareCalTokenRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/setup': typeof SetupRoute;
  '/invites/accept': typeof InvitesAcceptRoute;
  '/me/invites': typeof MeInvitesRoute;
  '/share/cal/$token': typeof ShareCalTokenRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/invites/accept'
    | '/me/invites'
    | '/share/cal/$token';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/invites/accept'
    | '/me/invites'
    | '/share/cal/$token';
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/invites/accept'
    | '/me/invites'
    | '/share/cal/$token';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  SetupRoute: typeof SetupRoute;
  InvitesAcceptRoute: typeof InvitesAcceptRoute;
  MeInvitesRoute: typeof MeInvitesRoute;
  ShareCalTokenRoute: typeof ShareCalTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup';
      path: '/setup';
      fullPath: '/setup';
      preLoaderRoute: typeof SetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/me/invites': {
      id: '/me/invites';
      path: '/me/invites';
      fullPath: '/me/invites';
      preLoaderRoute: typeof MeInvitesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/invites/accept': {
      id: '/invites/accept';
      path: '/invites/accept';
      fullPath: '/invites/accept';
      preLoaderRoute: typeof InvitesAcceptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/share/cal/$token': {
      id: '/share/cal/$token';
      path: '/share/cal/$token';
      fullPath: '/share/cal/$token';
      preLoaderRoute: typeof ShareCalTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  InvitesAcceptRoute: InvitesAcceptRoute,
  MeInvitesRoute: MeInvitesRoute,
  ShareCalTokenRoute: ShareCalTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
