// Hand-authored error-code lookup over the generated error catalog.
//
// The per-domain error modules under ./errors are generated by
// scripts/gen-errors.go from errors/*.yaml (DO NOT EDIT), and the
// ./errors/index.ts barrel is regenerated on every run. This module lives
// OUTSIDE that generated directory so the codegen never clobbers it, and is
// re-exported from ./index.ts as part of the SDK's public surface.

import {
  AiErrors,
  AuthErrors,
  CalendarErrors,
  ConstraintErrors,
  ExportErrors,
  InstanceErrors,
  IntegrationGhErrors,
  IntegrationGoogleErrors,
  IntegrationSlackErrors,
  IntegrationsErrors,
  InternalErrors,
  ItemErrors,
  McpErrors,
  PageErrors,
  RateErrors,
  RelationErrors,
  ShareErrors,
  TimeboxErrors,
  UserErrors,
  ValidationErrors,
  WebhookErrors,
  WorkspaceErrors,
  WsErrors,
} from './errors/index.js';

export interface ErrorDefinition {
  code: string;
  status: number;
  message: string;
  i18nKey?: string;
}

const ERROR_GROUPS: ReadonlyArray<Record<string, ErrorDefinition>> = [
  AiErrors,
  AuthErrors,
  CalendarErrors,
  ConstraintErrors,
  ExportErrors,
  InstanceErrors,
  IntegrationGhErrors,
  IntegrationGoogleErrors,
  IntegrationSlackErrors,
  IntegrationsErrors,
  InternalErrors,
  ItemErrors,
  McpErrors,
  PageErrors,
  RateErrors,
  RelationErrors,
  ShareErrors,
  TimeboxErrors,
  UserErrors,
  ValidationErrors,
  WebhookErrors,
  WorkspaceErrors,
  WsErrors,
];

const ERROR_BY_CODE = new Map<string, ErrorDefinition>(
  ERROR_GROUPS.flatMap((group) => Object.values(group).map((def) => [def.code, def] as const)),
);

export function lookupErrorDefinition(code: string | undefined): ErrorDefinition | undefined {
  if (!code) return undefined;
  return ERROR_BY_CODE.get(code);
}

export function lookupErrorI18nKey(code: string | undefined): string | undefined {
  return lookupErrorDefinition(code)?.i18nKey;
}
