// Error-code lookup over the generated error catalog.
//
// The per-domain error modules under ./errors are generated by
// scripts/gen-errors.go from errors/*.yaml (DO NOT EDIT), and the
// ./errors/index.ts barrel is regenerated on every run. This module lives
// OUTSIDE that generated directory so the codegen never clobbers it, and is
// re-exported from ./index.ts as part of the SDK's public surface.
//
// The catalog is read through a namespace import of the barrel rather than a
// hand-written list of groups. A list has to be edited every time a domain is
// added to errors/*.yaml, and forgetting to edit it fails silently: the new
// codes simply resolve to `undefined`, so the UI falls back to the raw English
// message with no test or build step objecting. The namespace object carries
// exactly the barrel's runtime exports, so a new domain is picked up the
// moment codegen runs.

import * as catalog from './errors/index.js';

export interface ErrorDefinition {
  code: string;
  status: number;
  message: string;
  i18nKey?: string;
}

/** Narrows one namespace member to a `{ [constName]: ErrorDefinition }` group. */
function isErrorGroup(value: unknown): value is Record<string, ErrorDefinition> {
  if (typeof value !== 'object' || value === null) return false;
  const entries = Object.values(value);
  if (entries.length === 0) return false;
  return entries.every((entry) => {
    if (typeof entry !== 'object' || entry === null) return false;
    const def = entry as Partial<ErrorDefinition>;
    return typeof def.code === 'string' && typeof def.status === 'number';
  });
}

/**
 * Every generated error group, keyed by its barrel export name (`AiErrors`,
 * `WsErrors`, …). Exported so tests can assert the catalog is non-empty and
 * that the lookup covers all of it.
 */
export const ERROR_GROUPS: Readonly<Record<string, Record<string, ErrorDefinition>>> =
  Object.fromEntries(
    Object.entries(catalog as Record<string, unknown>).filter(
      (entry): entry is [string, Record<string, ErrorDefinition>] => isErrorGroup(entry[1]),
    ),
  );

const ERROR_BY_CODE = new Map<string, ErrorDefinition>(
  Object.values(ERROR_GROUPS).flatMap((group) =>
    Object.values(group).map((def) => [def.code, def] as const),
  ),
);

export function lookupErrorDefinition(code: string | undefined): ErrorDefinition | undefined {
  if (!code) return undefined;
  return ERROR_BY_CODE.get(code);
}

export function lookupErrorI18nKey(code: string | undefined): string | undefined {
  return lookupErrorDefinition(code)?.i18nKey;
}
