/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index';
import { Route as InvitesAcceptRouteImport } from './routes/invites.accept';
import { Route as InviteTokenRouteImport } from './routes/invite.$token';
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated.workspaces';
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated.today';
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated.setup';
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings';
import { Route as AuthenticatedPagesRouteImport } from './routes/_authenticated.pages';
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox';
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar';
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated.workspaces.index';
import { Route as AuthenticatedPagesIndexRouteImport } from './routes/_authenticated.pages.index';
import { Route as ShareCalTokenRouteImport } from './routes/share.cal.$token';
import { Route as PublicLensesTokenRouteImport } from './routes/public.lenses.$token';
import { Route as AuthenticatedWorkspacesIdRouteImport } from './routes/_authenticated.workspaces.$id';
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated.tasks.$taskId';
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated.settings.security';
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated.settings.profile';
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated.settings.notifications';
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated.settings.integrations';
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId';
import { Route as AuthenticatedPagesPageIdRouteImport } from './routes/_authenticated.pages.$pageId';
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated.projects.$projectId.index';
import { Route as AuthenticatedWorkspacesIdTimelineRouteImport } from './routes/_authenticated.workspaces.$id.timeline';
import { Route as AuthenticatedWorkspacesIdTimeboxesRouteImport } from './routes/_authenticated.workspaces.$id.timeboxes';
import { Route as AuthenticatedWorkspacesIdSettingsRouteImport } from './routes/_authenticated.workspaces.$id.settings';
import { Route as AuthenticatedWorkspacesIdRemindersRouteImport } from './routes/_authenticated.workspaces.$id.reminders';
import { Route as AuthenticatedWorkspacesIdProjectsRouteImport } from './routes/_authenticated.workspaces.$id.projects';
import { Route as AuthenticatedProjectsProjectIdTimelineRouteImport } from './routes/_authenticated.projects.$projectId.timeline';
import { Route as AuthenticatedProjectsProjectIdTasksRouteImport } from './routes/_authenticated.projects.$projectId.tasks';
import { Route as AuthenticatedProjectsProjectIdGanttRouteImport } from './routes/_authenticated.projects.$projectId.gantt';
import { Route as AuthenticatedWorkspacesIdSettingsIndexRouteImport } from './routes/_authenticated.workspaces.$id.settings.index';
import { Route as AuthenticatedWorkspacesIdProjectsIndexRouteImport } from './routes/_authenticated.workspaces.$id.projects.index';
import { Route as AuthenticatedProjectsProjectIdTasksIndexRouteImport } from './routes/_authenticated.projects.$projectId.tasks.index';
import { Route as AuthenticatedWorkspacesIdTasksDraftsRouteImport } from './routes/_authenticated.workspaces.$id.tasks.drafts';
import { Route as AuthenticatedWorkspacesIdTasksArchivedRouteImport } from './routes/_authenticated.workspaces.$id.tasks.archived';
import { Route as AuthenticatedWorkspacesIdSettingsWeeklyDigestRouteImport } from './routes/_authenticated.workspaces.$id.settings.weekly-digest';
import { Route as AuthenticatedWorkspacesIdSettingsWebhooksRouteImport } from './routes/_authenticated.workspaces.$id.settings.webhooks';
import { Route as AuthenticatedWorkspacesIdSettingsPublicSharesRouteImport } from './routes/_authenticated.workspaces.$id.settings.public-shares';
import { Route as AuthenticatedWorkspacesIdSettingsMcpTokensRouteImport } from './routes/_authenticated.workspaces.$id.settings.mcp-tokens';
import { Route as AuthenticatedWorkspacesIdSettingsGeneralRouteImport } from './routes/_authenticated.workspaces.$id.settings.general';
import { Route as AuthenticatedWorkspacesIdSettingsDataRouteImport } from './routes/_authenticated.workspaces.$id.settings.data';
import { Route as AuthenticatedWorkspacesIdSettingsAutoActionsRouteImport } from './routes/_authenticated.workspaces.$id.settings.auto-actions';
import { Route as AuthenticatedWorkspacesIdSettingsAuditLogRouteImport } from './routes/_authenticated.workspaces.$id.settings.audit-log';
import { Route as AuthenticatedWorkspacesIdSettingsAiProvidersRouteImport } from './routes/_authenticated.workspaces.$id.settings.ai-providers';
import { Route as AuthenticatedWorkspacesIdSettingsAiAgentsRouteImport } from './routes/_authenticated.workspaces.$id.settings.ai-agents';
import { Route as AuthenticatedWorkspacesIdSettingsAiActivityRouteImport } from './routes/_authenticated.workspaces.$id.settings.ai-activity';
import { Route as AuthenticatedWorkspacesIdProjectsProjectIdRouteImport } from './routes/_authenticated.workspaces.$id.projects.$projectId';
import { Route as AuthenticatedWorkspacesIdInsightsPriorityRouteImport } from './routes/_authenticated.workspaces.$id.insights.priority';
import { Route as AuthenticatedWorkspacesIdSettingsPublicSharesIndexRouteImport } from './routes/_authenticated.workspaces.$id.settings.public-shares.index';
import { Route as AuthenticatedWorkspacesIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated.workspaces.$id.projects.$projectId.index';
import { Route as AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRouteImport } from './routes/_authenticated.workspaces.$id.settings.public-shares.$shareId';
import { Route as AuthenticatedWorkspacesIdSettingsAiMetricsRouteImport } from './routes/_authenticated.workspaces.$id.settings.ai.metrics';
import { Route as AuthenticatedWorkspacesIdProjectsProjectIdTimelineRouteImport } from './routes/_authenticated.workspaces.$id.projects.$projectId.timeline';
import { Route as AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteImport } from './routes/_authenticated.workspaces.$id.projects.$projectId.tasks';
import { Route as AuthenticatedWorkspacesIdProjectsProjectIdMembersRouteImport } from './routes/_authenticated.workspaces.$id.projects.$projectId.members';
import { Route as AuthenticatedWorkspacesIdProjectsProjectIdGanttRouteImport } from './routes/_authenticated.workspaces.$id.projects.$projectId.gantt';
import { Route as AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRouteImport } from './routes/_authenticated.workspaces.$id.projects.$projectId.tasks.index';
import { Route as AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRouteImport } from './routes/_authenticated.workspaces.$id.calendars.$calId.events.$evtId';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const InvitesAcceptRoute = InvitesAcceptRouteImport.update({
  id: '/invites/accept',
  path: '/invites/accept',
  getParentRoute: () => rootRouteImport,
} as any);
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/invite.$token.lazy').then((d) => d.Route),
);
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.settings.lazy').then((d) => d.Route),
);
const AuthenticatedPagesRoute = AuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.inbox.lazy').then((d) => d.Route),
);
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesRoute,
  } as any);
const AuthenticatedPagesIndexRoute = AuthenticatedPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPagesRoute,
} as any);
const ShareCalTokenRoute = ShareCalTokenRouteImport.update({
  id: '/share/cal/$token',
  path: '/share/cal/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicLensesTokenRoute = PublicLensesTokenRouteImport.update({
  id: '/public/lenses/$token',
  path: '/public/lenses/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedWorkspacesIdRoute =
  AuthenticatedWorkspacesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWorkspacesRoute,
  } as any);
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.tasks.$taskId.lazy').then((d) => d.Route),
  );
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.settings.security.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.settings.profile.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.settings.notifications.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.settings.integrations.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedPagesPageIdRoute =
  AuthenticatedPagesPageIdRouteImport.update({
    id: '/$pageId',
    path: '/$pageId',
    getParentRoute: () => AuthenticatedPagesRoute,
  } as any);
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any);
const AuthenticatedWorkspacesIdTimelineRoute =
  AuthenticatedWorkspacesIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.timeline.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdTimeboxesRoute =
  AuthenticatedWorkspacesIdTimeboxesRouteImport.update({
    id: '/timeboxes',
    path: '/timeboxes',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.timeboxes.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsRoute =
  AuthenticatedWorkspacesIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdRemindersRoute =
  AuthenticatedWorkspacesIdRemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.reminders.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdProjectsRoute =
  AuthenticatedWorkspacesIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any);
const AuthenticatedProjectsProjectIdTimelineRoute =
  AuthenticatedProjectsProjectIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any);
const AuthenticatedProjectsProjectIdTasksRoute =
  AuthenticatedProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any);
const AuthenticatedProjectsProjectIdGanttRoute =
  AuthenticatedProjectsProjectIdGanttRouteImport.update({
    id: '/gantt',
    path: '/gantt',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any);
const AuthenticatedWorkspacesIdSettingsIndexRoute =
  AuthenticatedWorkspacesIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any);
const AuthenticatedWorkspacesIdProjectsIndexRoute =
  AuthenticatedWorkspacesIdProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsRoute,
  } as any);
const AuthenticatedProjectsProjectIdTasksIndexRoute =
  AuthenticatedProjectsProjectIdTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdTasksRoute,
  } as any);
const AuthenticatedWorkspacesIdTasksDraftsRoute =
  AuthenticatedWorkspacesIdTasksDraftsRouteImport.update({
    id: '/tasks/drafts',
    path: '/tasks/drafts',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.tasks.drafts.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdTasksArchivedRoute =
  AuthenticatedWorkspacesIdTasksArchivedRouteImport.update({
    id: '/tasks/archived',
    path: '/tasks/archived',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.tasks.archived.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute =
  AuthenticatedWorkspacesIdSettingsWeeklyDigestRouteImport.update({
    id: '/weekly-digest',
    path: '/weekly-digest',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.weekly-digest.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsWebhooksRoute =
  AuthenticatedWorkspacesIdSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.webhooks.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsPublicSharesRoute =
  AuthenticatedWorkspacesIdSettingsPublicSharesRouteImport.update({
    id: '/public-shares',
    path: '/public-shares',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.public-shares.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsMcpTokensRoute =
  AuthenticatedWorkspacesIdSettingsMcpTokensRouteImport.update({
    id: '/mcp-tokens',
    path: '/mcp-tokens',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.mcp-tokens.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsGeneralRoute =
  AuthenticatedWorkspacesIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.general.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsDataRoute =
  AuthenticatedWorkspacesIdSettingsDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.data.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsAutoActionsRoute =
  AuthenticatedWorkspacesIdSettingsAutoActionsRouteImport.update({
    id: '/auto-actions',
    path: '/auto-actions',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.auto-actions.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsAuditLogRoute =
  AuthenticatedWorkspacesIdSettingsAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.audit-log.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsAiProvidersRoute =
  AuthenticatedWorkspacesIdSettingsAiProvidersRouteImport.update({
    id: '/ai-providers',
    path: '/ai-providers',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.ai-providers.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsAiAgentsRoute =
  AuthenticatedWorkspacesIdSettingsAiAgentsRouteImport.update({
    id: '/ai-agents',
    path: '/ai-agents',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.ai-agents.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsAiActivityRoute =
  AuthenticatedWorkspacesIdSettingsAiActivityRouteImport.update({
    id: '/ai-activity',
    path: '/ai-activity',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.ai-activity.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdProjectsProjectIdRoute =
  AuthenticatedWorkspacesIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsRoute,
  } as any);
const AuthenticatedWorkspacesIdInsightsPriorityRoute =
  AuthenticatedWorkspacesIdInsightsPriorityRouteImport.update({
    id: '/insights/priority',
    path: '/insights/priority',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.insights.priority.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute =
  AuthenticatedWorkspacesIdSettingsPublicSharesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsPublicSharesRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.public-shares.index.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute =
  AuthenticatedWorkspacesIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsProjectIdRoute,
  } as any);
const AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute =
  AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRouteImport.update({
    id: '/$shareId',
    path: '/$shareId',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsPublicSharesRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.public-shares.$shareId.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdSettingsAiMetricsRoute =
  AuthenticatedWorkspacesIdSettingsAiMetricsRouteImport.update({
    id: '/ai/metrics',
    path: '/ai/metrics',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.settings.ai.metrics.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute =
  AuthenticatedWorkspacesIdProjectsProjectIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.projects.$projectId.timeline.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdProjectsProjectIdTasksRoute =
  AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.projects.$projectId.tasks.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute =
  AuthenticatedWorkspacesIdProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsProjectIdRoute,
  } as any);
const AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute =
  AuthenticatedWorkspacesIdProjectsProjectIdGanttRouteImport.update({
    id: '/gantt',
    path: '/gantt',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.projects.$projectId.gantt.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute =
  AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesIdProjectsProjectIdTasksRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.projects.$projectId.tasks.index.lazy').then(
      (d) => d.Route,
    ),
  );
const AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute =
  AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRouteImport.update({
    id: '/calendars/$calId/events/$evtId',
    path: '/calendars/$calId/events/$evtId',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workspaces.$id.calendars.$calId.events.$evtId.lazy').then(
      (d) => d.Route,
    ),
  );

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/calendar': typeof AuthenticatedCalendarRoute;
  '/inbox': typeof AuthenticatedInboxRoute;
  '/pages': typeof AuthenticatedPagesRouteWithChildren;
  '/settings': typeof AuthenticatedSettingsRouteWithChildren;
  '/setup': typeof AuthenticatedSetupRoute;
  '/today': typeof AuthenticatedTodayRoute;
  '/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren;
  '/invite/$token': typeof InviteTokenRoute;
  '/invites/accept': typeof InvitesAcceptRoute;
  '/pages/$pageId': typeof AuthenticatedPagesPageIdRoute;
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren;
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute;
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute;
  '/workspaces/$id': typeof AuthenticatedWorkspacesIdRouteWithChildren;
  '/public/lenses/$token': typeof PublicLensesTokenRoute;
  '/share/cal/$token': typeof ShareCalTokenRoute;
  '/pages/': typeof AuthenticatedPagesIndexRoute;
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute;
  '/projects/$projectId/gantt': typeof AuthenticatedProjectsProjectIdGanttRoute;
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRouteWithChildren;
  '/projects/$projectId/timeline': typeof AuthenticatedProjectsProjectIdTimelineRoute;
  '/workspaces/$id/projects': typeof AuthenticatedWorkspacesIdProjectsRouteWithChildren;
  '/workspaces/$id/reminders': typeof AuthenticatedWorkspacesIdRemindersRoute;
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRouteWithChildren;
  '/workspaces/$id/timeboxes': typeof AuthenticatedWorkspacesIdTimeboxesRoute;
  '/workspaces/$id/timeline': typeof AuthenticatedWorkspacesIdTimelineRoute;
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute;
  '/workspaces/$id/insights/priority': typeof AuthenticatedWorkspacesIdInsightsPriorityRoute;
  '/workspaces/$id/projects/$projectId': typeof AuthenticatedWorkspacesIdProjectsProjectIdRouteWithChildren;
  '/workspaces/$id/settings/ai-activity': typeof AuthenticatedWorkspacesIdSettingsAiActivityRoute;
  '/workspaces/$id/settings/ai-agents': typeof AuthenticatedWorkspacesIdSettingsAiAgentsRoute;
  '/workspaces/$id/settings/ai-providers': typeof AuthenticatedWorkspacesIdSettingsAiProvidersRoute;
  '/workspaces/$id/settings/audit-log': typeof AuthenticatedWorkspacesIdSettingsAuditLogRoute;
  '/workspaces/$id/settings/auto-actions': typeof AuthenticatedWorkspacesIdSettingsAutoActionsRoute;
  '/workspaces/$id/settings/data': typeof AuthenticatedWorkspacesIdSettingsDataRoute;
  '/workspaces/$id/settings/general': typeof AuthenticatedWorkspacesIdSettingsGeneralRoute;
  '/workspaces/$id/settings/mcp-tokens': typeof AuthenticatedWorkspacesIdSettingsMcpTokensRoute;
  '/workspaces/$id/settings/public-shares': typeof AuthenticatedWorkspacesIdSettingsPublicSharesRouteWithChildren;
  '/workspaces/$id/settings/webhooks': typeof AuthenticatedWorkspacesIdSettingsWebhooksRoute;
  '/workspaces/$id/settings/weekly-digest': typeof AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute;
  '/workspaces/$id/tasks/archived': typeof AuthenticatedWorkspacesIdTasksArchivedRoute;
  '/workspaces/$id/tasks/drafts': typeof AuthenticatedWorkspacesIdTasksDraftsRoute;
  '/projects/$projectId/tasks/': typeof AuthenticatedProjectsProjectIdTasksIndexRoute;
  '/workspaces/$id/projects/': typeof AuthenticatedWorkspacesIdProjectsIndexRoute;
  '/workspaces/$id/settings/': typeof AuthenticatedWorkspacesIdSettingsIndexRoute;
  '/workspaces/$id/projects/$projectId/gantt': typeof AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute;
  '/workspaces/$id/projects/$projectId/members': typeof AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute;
  '/workspaces/$id/projects/$projectId/tasks': typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteWithChildren;
  '/workspaces/$id/projects/$projectId/timeline': typeof AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute;
  '/workspaces/$id/settings/ai/metrics': typeof AuthenticatedWorkspacesIdSettingsAiMetricsRoute;
  '/workspaces/$id/settings/public-shares/$shareId': typeof AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute;
  '/workspaces/$id/projects/$projectId/': typeof AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute;
  '/workspaces/$id/settings/public-shares/': typeof AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute;
  '/workspaces/$id/calendars/$calId/events/$evtId': typeof AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute;
  '/workspaces/$id/projects/$projectId/tasks/': typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/calendar': typeof AuthenticatedCalendarRoute;
  '/inbox': typeof AuthenticatedInboxRoute;
  '/settings': typeof AuthenticatedSettingsRouteWithChildren;
  '/setup': typeof AuthenticatedSetupRoute;
  '/today': typeof AuthenticatedTodayRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/invites/accept': typeof InvitesAcceptRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/pages/$pageId': typeof AuthenticatedPagesPageIdRoute;
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute;
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute;
  '/workspaces/$id': typeof AuthenticatedWorkspacesIdRouteWithChildren;
  '/public/lenses/$token': typeof PublicLensesTokenRoute;
  '/share/cal/$token': typeof ShareCalTokenRoute;
  '/pages': typeof AuthenticatedPagesIndexRoute;
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute;
  '/projects/$projectId/gantt': typeof AuthenticatedProjectsProjectIdGanttRoute;
  '/projects/$projectId/timeline': typeof AuthenticatedProjectsProjectIdTimelineRoute;
  '/workspaces/$id/reminders': typeof AuthenticatedWorkspacesIdRemindersRoute;
  '/workspaces/$id/timeboxes': typeof AuthenticatedWorkspacesIdTimeboxesRoute;
  '/workspaces/$id/timeline': typeof AuthenticatedWorkspacesIdTimelineRoute;
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute;
  '/workspaces/$id/insights/priority': typeof AuthenticatedWorkspacesIdInsightsPriorityRoute;
  '/workspaces/$id/settings/ai-activity': typeof AuthenticatedWorkspacesIdSettingsAiActivityRoute;
  '/workspaces/$id/settings/ai-agents': typeof AuthenticatedWorkspacesIdSettingsAiAgentsRoute;
  '/workspaces/$id/settings/ai-providers': typeof AuthenticatedWorkspacesIdSettingsAiProvidersRoute;
  '/workspaces/$id/settings/audit-log': typeof AuthenticatedWorkspacesIdSettingsAuditLogRoute;
  '/workspaces/$id/settings/auto-actions': typeof AuthenticatedWorkspacesIdSettingsAutoActionsRoute;
  '/workspaces/$id/settings/data': typeof AuthenticatedWorkspacesIdSettingsDataRoute;
  '/workspaces/$id/settings/general': typeof AuthenticatedWorkspacesIdSettingsGeneralRoute;
  '/workspaces/$id/settings/mcp-tokens': typeof AuthenticatedWorkspacesIdSettingsMcpTokensRoute;
  '/workspaces/$id/settings/webhooks': typeof AuthenticatedWorkspacesIdSettingsWebhooksRoute;
  '/workspaces/$id/settings/weekly-digest': typeof AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute;
  '/workspaces/$id/tasks/archived': typeof AuthenticatedWorkspacesIdTasksArchivedRoute;
  '/workspaces/$id/tasks/drafts': typeof AuthenticatedWorkspacesIdTasksDraftsRoute;
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksIndexRoute;
  '/workspaces/$id/projects': typeof AuthenticatedWorkspacesIdProjectsIndexRoute;
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsIndexRoute;
  '/workspaces/$id/projects/$projectId/gantt': typeof AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute;
  '/workspaces/$id/projects/$projectId/members': typeof AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute;
  '/workspaces/$id/projects/$projectId/timeline': typeof AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute;
  '/workspaces/$id/settings/ai/metrics': typeof AuthenticatedWorkspacesIdSettingsAiMetricsRoute;
  '/workspaces/$id/settings/public-shares/$shareId': typeof AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute;
  '/workspaces/$id/projects/$projectId': typeof AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute;
  '/workspaces/$id/settings/public-shares': typeof AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute;
  '/workspaces/$id/calendars/$calId/events/$evtId': typeof AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute;
  '/workspaces/$id/projects/$projectId/tasks': typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute;
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute;
  '/_authenticated/pages': typeof AuthenticatedPagesRouteWithChildren;
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren;
  '/_authenticated/setup': typeof AuthenticatedSetupRoute;
  '/_authenticated/today': typeof AuthenticatedTodayRoute;
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren;
  '/invite/$token': typeof InviteTokenRoute;
  '/invites/accept': typeof InvitesAcceptRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/pages/$pageId': typeof AuthenticatedPagesPageIdRoute;
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren;
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute;
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute;
  '/_authenticated/workspaces/$id': typeof AuthenticatedWorkspacesIdRouteWithChildren;
  '/public/lenses/$token': typeof PublicLensesTokenRoute;
  '/share/cal/$token': typeof ShareCalTokenRoute;
  '/_authenticated/pages/': typeof AuthenticatedPagesIndexRoute;
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute;
  '/_authenticated/projects/$projectId/gantt': typeof AuthenticatedProjectsProjectIdGanttRoute;
  '/_authenticated/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRouteWithChildren;
  '/_authenticated/projects/$projectId/timeline': typeof AuthenticatedProjectsProjectIdTimelineRoute;
  '/_authenticated/workspaces/$id/projects': typeof AuthenticatedWorkspacesIdProjectsRouteWithChildren;
  '/_authenticated/workspaces/$id/reminders': typeof AuthenticatedWorkspacesIdRemindersRoute;
  '/_authenticated/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRouteWithChildren;
  '/_authenticated/workspaces/$id/timeboxes': typeof AuthenticatedWorkspacesIdTimeboxesRoute;
  '/_authenticated/workspaces/$id/timeline': typeof AuthenticatedWorkspacesIdTimelineRoute;
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute;
  '/_authenticated/workspaces/$id/insights/priority': typeof AuthenticatedWorkspacesIdInsightsPriorityRoute;
  '/_authenticated/workspaces/$id/projects/$projectId': typeof AuthenticatedWorkspacesIdProjectsProjectIdRouteWithChildren;
  '/_authenticated/workspaces/$id/settings/ai-activity': typeof AuthenticatedWorkspacesIdSettingsAiActivityRoute;
  '/_authenticated/workspaces/$id/settings/ai-agents': typeof AuthenticatedWorkspacesIdSettingsAiAgentsRoute;
  '/_authenticated/workspaces/$id/settings/ai-providers': typeof AuthenticatedWorkspacesIdSettingsAiProvidersRoute;
  '/_authenticated/workspaces/$id/settings/audit-log': typeof AuthenticatedWorkspacesIdSettingsAuditLogRoute;
  '/_authenticated/workspaces/$id/settings/auto-actions': typeof AuthenticatedWorkspacesIdSettingsAutoActionsRoute;
  '/_authenticated/workspaces/$id/settings/data': typeof AuthenticatedWorkspacesIdSettingsDataRoute;
  '/_authenticated/workspaces/$id/settings/general': typeof AuthenticatedWorkspacesIdSettingsGeneralRoute;
  '/_authenticated/workspaces/$id/settings/mcp-tokens': typeof AuthenticatedWorkspacesIdSettingsMcpTokensRoute;
  '/_authenticated/workspaces/$id/settings/public-shares': typeof AuthenticatedWorkspacesIdSettingsPublicSharesRouteWithChildren;
  '/_authenticated/workspaces/$id/settings/webhooks': typeof AuthenticatedWorkspacesIdSettingsWebhooksRoute;
  '/_authenticated/workspaces/$id/settings/weekly-digest': typeof AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute;
  '/_authenticated/workspaces/$id/tasks/archived': typeof AuthenticatedWorkspacesIdTasksArchivedRoute;
  '/_authenticated/workspaces/$id/tasks/drafts': typeof AuthenticatedWorkspacesIdTasksDraftsRoute;
  '/_authenticated/projects/$projectId/tasks/': typeof AuthenticatedProjectsProjectIdTasksIndexRoute;
  '/_authenticated/workspaces/$id/projects/': typeof AuthenticatedWorkspacesIdProjectsIndexRoute;
  '/_authenticated/workspaces/$id/settings/': typeof AuthenticatedWorkspacesIdSettingsIndexRoute;
  '/_authenticated/workspaces/$id/projects/$projectId/gantt': typeof AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute;
  '/_authenticated/workspaces/$id/projects/$projectId/members': typeof AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute;
  '/_authenticated/workspaces/$id/projects/$projectId/tasks': typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteWithChildren;
  '/_authenticated/workspaces/$id/projects/$projectId/timeline': typeof AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute;
  '/_authenticated/workspaces/$id/settings/ai/metrics': typeof AuthenticatedWorkspacesIdSettingsAiMetricsRoute;
  '/_authenticated/workspaces/$id/settings/public-shares/$shareId': typeof AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute;
  '/_authenticated/workspaces/$id/projects/$projectId/': typeof AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute;
  '/_authenticated/workspaces/$id/settings/public-shares/': typeof AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute;
  '/_authenticated/workspaces/$id/calendars/$calId/events/$evtId': typeof AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute;
  '/_authenticated/workspaces/$id/projects/$projectId/tasks/': typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/calendar'
    | '/inbox'
    | '/pages'
    | '/settings'
    | '/setup'
    | '/today'
    | '/workspaces'
    | '/invite/$token'
    | '/invites/accept'
    | '/pages/$pageId'
    | '/projects/$projectId'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/tasks/$taskId'
    | '/workspaces/$id'
    | '/public/lenses/$token'
    | '/share/cal/$token'
    | '/pages/'
    | '/workspaces/'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/timeline'
    | '/workspaces/$id/projects'
    | '/workspaces/$id/reminders'
    | '/workspaces/$id/settings'
    | '/workspaces/$id/timeboxes'
    | '/workspaces/$id/timeline'
    | '/projects/$projectId/'
    | '/workspaces/$id/insights/priority'
    | '/workspaces/$id/projects/$projectId'
    | '/workspaces/$id/settings/ai-activity'
    | '/workspaces/$id/settings/ai-agents'
    | '/workspaces/$id/settings/ai-providers'
    | '/workspaces/$id/settings/audit-log'
    | '/workspaces/$id/settings/auto-actions'
    | '/workspaces/$id/settings/data'
    | '/workspaces/$id/settings/general'
    | '/workspaces/$id/settings/mcp-tokens'
    | '/workspaces/$id/settings/public-shares'
    | '/workspaces/$id/settings/webhooks'
    | '/workspaces/$id/settings/weekly-digest'
    | '/workspaces/$id/tasks/archived'
    | '/workspaces/$id/tasks/drafts'
    | '/projects/$projectId/tasks/'
    | '/workspaces/$id/projects/'
    | '/workspaces/$id/settings/'
    | '/workspaces/$id/projects/$projectId/gantt'
    | '/workspaces/$id/projects/$projectId/members'
    | '/workspaces/$id/projects/$projectId/tasks'
    | '/workspaces/$id/projects/$projectId/timeline'
    | '/workspaces/$id/settings/ai/metrics'
    | '/workspaces/$id/settings/public-shares/$shareId'
    | '/workspaces/$id/projects/$projectId/'
    | '/workspaces/$id/settings/public-shares/'
    | '/workspaces/$id/calendars/$calId/events/$evtId'
    | '/workspaces/$id/projects/$projectId/tasks/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/signup'
    | '/calendar'
    | '/inbox'
    | '/settings'
    | '/setup'
    | '/today'
    | '/invite/$token'
    | '/invites/accept'
    | '/'
    | '/pages/$pageId'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/tasks/$taskId'
    | '/workspaces/$id'
    | '/public/lenses/$token'
    | '/share/cal/$token'
    | '/pages'
    | '/workspaces'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/timeline'
    | '/workspaces/$id/reminders'
    | '/workspaces/$id/timeboxes'
    | '/workspaces/$id/timeline'
    | '/projects/$projectId'
    | '/workspaces/$id/insights/priority'
    | '/workspaces/$id/settings/ai-activity'
    | '/workspaces/$id/settings/ai-agents'
    | '/workspaces/$id/settings/ai-providers'
    | '/workspaces/$id/settings/audit-log'
    | '/workspaces/$id/settings/auto-actions'
    | '/workspaces/$id/settings/data'
    | '/workspaces/$id/settings/general'
    | '/workspaces/$id/settings/mcp-tokens'
    | '/workspaces/$id/settings/webhooks'
    | '/workspaces/$id/settings/weekly-digest'
    | '/workspaces/$id/tasks/archived'
    | '/workspaces/$id/tasks/drafts'
    | '/projects/$projectId/tasks'
    | '/workspaces/$id/projects'
    | '/workspaces/$id/settings'
    | '/workspaces/$id/projects/$projectId/gantt'
    | '/workspaces/$id/projects/$projectId/members'
    | '/workspaces/$id/projects/$projectId/timeline'
    | '/workspaces/$id/settings/ai/metrics'
    | '/workspaces/$id/settings/public-shares/$shareId'
    | '/workspaces/$id/projects/$projectId'
    | '/workspaces/$id/settings/public-shares'
    | '/workspaces/$id/calendars/$calId/events/$evtId'
    | '/workspaces/$id/projects/$projectId/tasks';
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/calendar'
    | '/_authenticated/inbox'
    | '/_authenticated/pages'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/today'
    | '/_authenticated/workspaces'
    | '/invite/$token'
    | '/invites/accept'
    | '/_authenticated/'
    | '/_authenticated/pages/$pageId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/workspaces/$id'
    | '/public/lenses/$token'
    | '/share/cal/$token'
    | '/_authenticated/pages/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/projects/$projectId/gantt'
    | '/_authenticated/projects/$projectId/tasks'
    | '/_authenticated/projects/$projectId/timeline'
    | '/_authenticated/workspaces/$id/projects'
    | '/_authenticated/workspaces/$id/reminders'
    | '/_authenticated/workspaces/$id/settings'
    | '/_authenticated/workspaces/$id/timeboxes'
    | '/_authenticated/workspaces/$id/timeline'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/workspaces/$id/insights/priority'
    | '/_authenticated/workspaces/$id/projects/$projectId'
    | '/_authenticated/workspaces/$id/settings/ai-activity'
    | '/_authenticated/workspaces/$id/settings/ai-agents'
    | '/_authenticated/workspaces/$id/settings/ai-providers'
    | '/_authenticated/workspaces/$id/settings/audit-log'
    | '/_authenticated/workspaces/$id/settings/auto-actions'
    | '/_authenticated/workspaces/$id/settings/data'
    | '/_authenticated/workspaces/$id/settings/general'
    | '/_authenticated/workspaces/$id/settings/mcp-tokens'
    | '/_authenticated/workspaces/$id/settings/public-shares'
    | '/_authenticated/workspaces/$id/settings/webhooks'
    | '/_authenticated/workspaces/$id/settings/weekly-digest'
    | '/_authenticated/workspaces/$id/tasks/archived'
    | '/_authenticated/workspaces/$id/tasks/drafts'
    | '/_authenticated/projects/$projectId/tasks/'
    | '/_authenticated/workspaces/$id/projects/'
    | '/_authenticated/workspaces/$id/settings/'
    | '/_authenticated/workspaces/$id/projects/$projectId/gantt'
    | '/_authenticated/workspaces/$id/projects/$projectId/members'
    | '/_authenticated/workspaces/$id/projects/$projectId/tasks'
    | '/_authenticated/workspaces/$id/projects/$projectId/timeline'
    | '/_authenticated/workspaces/$id/settings/ai/metrics'
    | '/_authenticated/workspaces/$id/settings/public-shares/$shareId'
    | '/_authenticated/workspaces/$id/projects/$projectId/'
    | '/_authenticated/workspaces/$id/settings/public-shares/'
    | '/_authenticated/workspaces/$id/calendars/$calId/events/$evtId'
    | '/_authenticated/workspaces/$id/projects/$projectId/tasks/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
  InviteTokenRoute: typeof InviteTokenRoute;
  InvitesAcceptRoute: typeof InvitesAcceptRoute;
  PublicLensesTokenRoute: typeof PublicLensesTokenRoute;
  ShareCalTokenRoute: typeof ShareCalTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/invites/accept': {
      id: '/invites/accept';
      path: '/invites/accept';
      fullPath: '/invites/accept';
      preLoaderRoute: typeof InvitesAcceptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/invite/$token': {
      id: '/invite/$token';
      path: '/invite/$token';
      fullPath: '/invite/$token';
      preLoaderRoute: typeof InviteTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces';
      path: '/workspaces';
      fullPath: '/workspaces';
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/today': {
      id: '/_authenticated/today';
      path: '/today';
      fullPath: '/today';
      preLoaderRoute: typeof AuthenticatedTodayRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/setup': {
      id: '/_authenticated/setup';
      path: '/setup';
      fullPath: '/setup';
      preLoaderRoute: typeof AuthenticatedSetupRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/settings': {
      id: '/_authenticated/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/pages': {
      id: '/_authenticated/pages';
      path: '/pages';
      fullPath: '/pages';
      preLoaderRoute: typeof AuthenticatedPagesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox';
      path: '/inbox';
      fullPath: '/inbox';
      preLoaderRoute: typeof AuthenticatedInboxRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar';
      path: '/calendar';
      fullPath: '/calendar';
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/';
      path: '/';
      fullPath: '/workspaces/';
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesRoute;
    };
    '/_authenticated/pages/': {
      id: '/_authenticated/pages/';
      path: '/';
      fullPath: '/pages/';
      preLoaderRoute: typeof AuthenticatedPagesIndexRouteImport;
      parentRoute: typeof AuthenticatedPagesRoute;
    };
    '/share/cal/$token': {
      id: '/share/cal/$token';
      path: '/share/cal/$token';
      fullPath: '/share/cal/$token';
      preLoaderRoute: typeof ShareCalTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/public/lenses/$token': {
      id: '/public/lenses/$token';
      path: '/public/lenses/$token';
      fullPath: '/public/lenses/$token';
      preLoaderRoute: typeof PublicLensesTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/workspaces/$id': {
      id: '/_authenticated/workspaces/$id';
      path: '/$id';
      fullPath: '/workspaces/$id';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesRoute;
    };
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId';
      path: '/tasks/$taskId';
      fullPath: '/tasks/$taskId';
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security';
      path: '/security';
      fullPath: '/settings/security';
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile';
      path: '/profile';
      fullPath: '/settings/profile';
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications';
      path: '/notifications';
      fullPath: '/settings/notifications';
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations';
      path: '/integrations';
      fullPath: '/settings/integrations';
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId';
      path: '/projects/$projectId';
      fullPath: '/projects/$projectId';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/pages/$pageId': {
      id: '/_authenticated/pages/$pageId';
      path: '/$pageId';
      fullPath: '/pages/$pageId';
      preLoaderRoute: typeof AuthenticatedPagesPageIdRouteImport;
      parentRoute: typeof AuthenticatedPagesRoute;
    };
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/';
      path: '/';
      fullPath: '/projects/$projectId/';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute;
    };
    '/_authenticated/workspaces/$id/timeline': {
      id: '/_authenticated/workspaces/$id/timeline';
      path: '/timeline';
      fullPath: '/workspaces/$id/timeline';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdTimelineRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/workspaces/$id/timeboxes': {
      id: '/_authenticated/workspaces/$id/timeboxes';
      path: '/timeboxes';
      fullPath: '/workspaces/$id/timeboxes';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdTimeboxesRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/workspaces/$id/settings': {
      id: '/_authenticated/workspaces/$id/settings';
      path: '/settings';
      fullPath: '/workspaces/$id/settings';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/workspaces/$id/reminders': {
      id: '/_authenticated/workspaces/$id/reminders';
      path: '/reminders';
      fullPath: '/workspaces/$id/reminders';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdRemindersRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/workspaces/$id/projects': {
      id: '/_authenticated/workspaces/$id/projects';
      path: '/projects';
      fullPath: '/workspaces/$id/projects';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/projects/$projectId/timeline': {
      id: '/_authenticated/projects/$projectId/timeline';
      path: '/timeline';
      fullPath: '/projects/$projectId/timeline';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTimelineRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute;
    };
    '/_authenticated/projects/$projectId/tasks': {
      id: '/_authenticated/projects/$projectId/tasks';
      path: '/tasks';
      fullPath: '/projects/$projectId/tasks';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute;
    };
    '/_authenticated/projects/$projectId/gantt': {
      id: '/_authenticated/projects/$projectId/gantt';
      path: '/gantt';
      fullPath: '/projects/$projectId/gantt';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdGanttRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute;
    };
    '/_authenticated/workspaces/$id/settings/': {
      id: '/_authenticated/workspaces/$id/settings/';
      path: '/';
      fullPath: '/workspaces/$id/settings/';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/projects/': {
      id: '/_authenticated/workspaces/$id/projects/';
      path: '/';
      fullPath: '/workspaces/$id/projects/';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsIndexRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsRoute;
    };
    '/_authenticated/projects/$projectId/tasks/': {
      id: '/_authenticated/projects/$projectId/tasks/';
      path: '/';
      fullPath: '/projects/$projectId/tasks/';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdTasksRoute;
    };
    '/_authenticated/workspaces/$id/tasks/drafts': {
      id: '/_authenticated/workspaces/$id/tasks/drafts';
      path: '/tasks/drafts';
      fullPath: '/workspaces/$id/tasks/drafts';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdTasksDraftsRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/workspaces/$id/tasks/archived': {
      id: '/_authenticated/workspaces/$id/tasks/archived';
      path: '/tasks/archived';
      fullPath: '/workspaces/$id/tasks/archived';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdTasksArchivedRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/workspaces/$id/settings/weekly-digest': {
      id: '/_authenticated/workspaces/$id/settings/weekly-digest';
      path: '/weekly-digest';
      fullPath: '/workspaces/$id/settings/weekly-digest';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsWeeklyDigestRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/webhooks': {
      id: '/_authenticated/workspaces/$id/settings/webhooks';
      path: '/webhooks';
      fullPath: '/workspaces/$id/settings/webhooks';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsWebhooksRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/public-shares': {
      id: '/_authenticated/workspaces/$id/settings/public-shares';
      path: '/public-shares';
      fullPath: '/workspaces/$id/settings/public-shares';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/mcp-tokens': {
      id: '/_authenticated/workspaces/$id/settings/mcp-tokens';
      path: '/mcp-tokens';
      fullPath: '/workspaces/$id/settings/mcp-tokens';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsMcpTokensRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/general': {
      id: '/_authenticated/workspaces/$id/settings/general';
      path: '/general';
      fullPath: '/workspaces/$id/settings/general';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsGeneralRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/data': {
      id: '/_authenticated/workspaces/$id/settings/data';
      path: '/data';
      fullPath: '/workspaces/$id/settings/data';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsDataRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/auto-actions': {
      id: '/_authenticated/workspaces/$id/settings/auto-actions';
      path: '/auto-actions';
      fullPath: '/workspaces/$id/settings/auto-actions';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsAutoActionsRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/audit-log': {
      id: '/_authenticated/workspaces/$id/settings/audit-log';
      path: '/audit-log';
      fullPath: '/workspaces/$id/settings/audit-log';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsAuditLogRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/ai-providers': {
      id: '/_authenticated/workspaces/$id/settings/ai-providers';
      path: '/ai-providers';
      fullPath: '/workspaces/$id/settings/ai-providers';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsAiProvidersRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/ai-agents': {
      id: '/_authenticated/workspaces/$id/settings/ai-agents';
      path: '/ai-agents';
      fullPath: '/workspaces/$id/settings/ai-agents';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsAiAgentsRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/settings/ai-activity': {
      id: '/_authenticated/workspaces/$id/settings/ai-activity';
      path: '/ai-activity';
      fullPath: '/workspaces/$id/settings/ai-activity';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsAiActivityRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/projects/$projectId': {
      id: '/_authenticated/workspaces/$id/projects/$projectId';
      path: '/$projectId';
      fullPath: '/workspaces/$id/projects/$projectId';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsRoute;
    };
    '/_authenticated/workspaces/$id/insights/priority': {
      id: '/_authenticated/workspaces/$id/insights/priority';
      path: '/insights/priority';
      fullPath: '/workspaces/$id/insights/priority';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdInsightsPriorityRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
    '/_authenticated/workspaces/$id/settings/public-shares/': {
      id: '/_authenticated/workspaces/$id/settings/public-shares/';
      path: '/';
      fullPath: '/workspaces/$id/settings/public-shares/';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesIndexRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesRoute;
    };
    '/_authenticated/workspaces/$id/projects/$projectId/': {
      id: '/_authenticated/workspaces/$id/projects/$projectId/';
      path: '/';
      fullPath: '/workspaces/$id/projects/$projectId/';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdIndexRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdRoute;
    };
    '/_authenticated/workspaces/$id/settings/public-shares/$shareId': {
      id: '/_authenticated/workspaces/$id/settings/public-shares/$shareId';
      path: '/$shareId';
      fullPath: '/workspaces/$id/settings/public-shares/$shareId';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesRoute;
    };
    '/_authenticated/workspaces/$id/settings/ai/metrics': {
      id: '/_authenticated/workspaces/$id/settings/ai/metrics';
      path: '/ai/metrics';
      fullPath: '/workspaces/$id/settings/ai/metrics';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsAiMetricsRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute;
    };
    '/_authenticated/workspaces/$id/projects/$projectId/timeline': {
      id: '/_authenticated/workspaces/$id/projects/$projectId/timeline';
      path: '/timeline';
      fullPath: '/workspaces/$id/projects/$projectId/timeline';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdTimelineRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdRoute;
    };
    '/_authenticated/workspaces/$id/projects/$projectId/tasks': {
      id: '/_authenticated/workspaces/$id/projects/$projectId/tasks';
      path: '/tasks';
      fullPath: '/workspaces/$id/projects/$projectId/tasks';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdRoute;
    };
    '/_authenticated/workspaces/$id/projects/$projectId/members': {
      id: '/_authenticated/workspaces/$id/projects/$projectId/members';
      path: '/members';
      fullPath: '/workspaces/$id/projects/$projectId/members';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdMembersRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdRoute;
    };
    '/_authenticated/workspaces/$id/projects/$projectId/gantt': {
      id: '/_authenticated/workspaces/$id/projects/$projectId/gantt';
      path: '/gantt';
      fullPath: '/workspaces/$id/projects/$projectId/gantt';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdGanttRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdRoute;
    };
    '/_authenticated/workspaces/$id/projects/$projectId/tasks/': {
      id: '/_authenticated/workspaces/$id/projects/$projectId/tasks/';
      path: '/';
      fullPath: '/workspaces/$id/projects/$projectId/tasks/';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksRoute;
    };
    '/_authenticated/workspaces/$id/calendars/$calId/events/$evtId': {
      id: '/_authenticated/workspaces/$id/calendars/$calId/events/$evtId';
      path: '/calendars/$calId/events/$evtId';
      fullPath: '/workspaces/$id/calendars/$calId/events/$evtId';
      preLoaderRoute: typeof AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRouteImport;
      parentRoute: typeof AuthenticatedWorkspacesIdRoute;
    };
  }
}

interface AuthenticatedPagesRouteChildren {
  AuthenticatedPagesPageIdRoute: typeof AuthenticatedPagesPageIdRoute;
  AuthenticatedPagesIndexRoute: typeof AuthenticatedPagesIndexRoute;
}

const AuthenticatedPagesRouteChildren: AuthenticatedPagesRouteChildren = {
  AuthenticatedPagesPageIdRoute: AuthenticatedPagesPageIdRoute,
  AuthenticatedPagesIndexRoute: AuthenticatedPagesIndexRoute,
};

const AuthenticatedPagesRouteWithChildren =
  AuthenticatedPagesRoute._addFileChildren(AuthenticatedPagesRouteChildren);

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute;
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute;
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute;
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute;
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
};

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  );

interface AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteChildren {
  AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute;
}

const AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteChildren: AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteChildren =
  {
    AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute:
      AuthenticatedWorkspacesIdProjectsProjectIdTasksIndexRoute,
  };

const AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteWithChildren =
  AuthenticatedWorkspacesIdProjectsProjectIdTasksRoute._addFileChildren(
    AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteChildren,
  );

interface AuthenticatedWorkspacesIdProjectsProjectIdRouteChildren {
  AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute;
  AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute;
  AuthenticatedWorkspacesIdProjectsProjectIdTasksRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteWithChildren;
  AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute;
  AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute;
}

const AuthenticatedWorkspacesIdProjectsProjectIdRouteChildren: AuthenticatedWorkspacesIdProjectsProjectIdRouteChildren =
  {
    AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute:
      AuthenticatedWorkspacesIdProjectsProjectIdGanttRoute,
    AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute:
      AuthenticatedWorkspacesIdProjectsProjectIdMembersRoute,
    AuthenticatedWorkspacesIdProjectsProjectIdTasksRoute:
      AuthenticatedWorkspacesIdProjectsProjectIdTasksRouteWithChildren,
    AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute:
      AuthenticatedWorkspacesIdProjectsProjectIdTimelineRoute,
    AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute:
      AuthenticatedWorkspacesIdProjectsProjectIdIndexRoute,
  };

const AuthenticatedWorkspacesIdProjectsProjectIdRouteWithChildren =
  AuthenticatedWorkspacesIdProjectsProjectIdRoute._addFileChildren(
    AuthenticatedWorkspacesIdProjectsProjectIdRouteChildren,
  );

interface AuthenticatedWorkspacesIdProjectsRouteChildren {
  AuthenticatedWorkspacesIdProjectsProjectIdRoute: typeof AuthenticatedWorkspacesIdProjectsProjectIdRouteWithChildren;
  AuthenticatedWorkspacesIdProjectsIndexRoute: typeof AuthenticatedWorkspacesIdProjectsIndexRoute;
}

const AuthenticatedWorkspacesIdProjectsRouteChildren: AuthenticatedWorkspacesIdProjectsRouteChildren =
  {
    AuthenticatedWorkspacesIdProjectsProjectIdRoute:
      AuthenticatedWorkspacesIdProjectsProjectIdRouteWithChildren,
    AuthenticatedWorkspacesIdProjectsIndexRoute:
      AuthenticatedWorkspacesIdProjectsIndexRoute,
  };

const AuthenticatedWorkspacesIdProjectsRouteWithChildren =
  AuthenticatedWorkspacesIdProjectsRoute._addFileChildren(
    AuthenticatedWorkspacesIdProjectsRouteChildren,
  );

interface AuthenticatedWorkspacesIdSettingsPublicSharesRouteChildren {
  AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute;
  AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute;
}

const AuthenticatedWorkspacesIdSettingsPublicSharesRouteChildren: AuthenticatedWorkspacesIdSettingsPublicSharesRouteChildren =
  {
    AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute:
      AuthenticatedWorkspacesIdSettingsPublicSharesShareIdRoute,
    AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute:
      AuthenticatedWorkspacesIdSettingsPublicSharesIndexRoute,
  };

const AuthenticatedWorkspacesIdSettingsPublicSharesRouteWithChildren =
  AuthenticatedWorkspacesIdSettingsPublicSharesRoute._addFileChildren(
    AuthenticatedWorkspacesIdSettingsPublicSharesRouteChildren,
  );

interface AuthenticatedWorkspacesIdSettingsRouteChildren {
  AuthenticatedWorkspacesIdSettingsAiActivityRoute: typeof AuthenticatedWorkspacesIdSettingsAiActivityRoute;
  AuthenticatedWorkspacesIdSettingsAiAgentsRoute: typeof AuthenticatedWorkspacesIdSettingsAiAgentsRoute;
  AuthenticatedWorkspacesIdSettingsAiProvidersRoute: typeof AuthenticatedWorkspacesIdSettingsAiProvidersRoute;
  AuthenticatedWorkspacesIdSettingsAuditLogRoute: typeof AuthenticatedWorkspacesIdSettingsAuditLogRoute;
  AuthenticatedWorkspacesIdSettingsAutoActionsRoute: typeof AuthenticatedWorkspacesIdSettingsAutoActionsRoute;
  AuthenticatedWorkspacesIdSettingsDataRoute: typeof AuthenticatedWorkspacesIdSettingsDataRoute;
  AuthenticatedWorkspacesIdSettingsGeneralRoute: typeof AuthenticatedWorkspacesIdSettingsGeneralRoute;
  AuthenticatedWorkspacesIdSettingsMcpTokensRoute: typeof AuthenticatedWorkspacesIdSettingsMcpTokensRoute;
  AuthenticatedWorkspacesIdSettingsPublicSharesRoute: typeof AuthenticatedWorkspacesIdSettingsPublicSharesRouteWithChildren;
  AuthenticatedWorkspacesIdSettingsWebhooksRoute: typeof AuthenticatedWorkspacesIdSettingsWebhooksRoute;
  AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute: typeof AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute;
  AuthenticatedWorkspacesIdSettingsIndexRoute: typeof AuthenticatedWorkspacesIdSettingsIndexRoute;
  AuthenticatedWorkspacesIdSettingsAiMetricsRoute: typeof AuthenticatedWorkspacesIdSettingsAiMetricsRoute;
}

const AuthenticatedWorkspacesIdSettingsRouteChildren: AuthenticatedWorkspacesIdSettingsRouteChildren =
  {
    AuthenticatedWorkspacesIdSettingsAiActivityRoute:
      AuthenticatedWorkspacesIdSettingsAiActivityRoute,
    AuthenticatedWorkspacesIdSettingsAiAgentsRoute:
      AuthenticatedWorkspacesIdSettingsAiAgentsRoute,
    AuthenticatedWorkspacesIdSettingsAiProvidersRoute:
      AuthenticatedWorkspacesIdSettingsAiProvidersRoute,
    AuthenticatedWorkspacesIdSettingsAuditLogRoute:
      AuthenticatedWorkspacesIdSettingsAuditLogRoute,
    AuthenticatedWorkspacesIdSettingsAutoActionsRoute:
      AuthenticatedWorkspacesIdSettingsAutoActionsRoute,
    AuthenticatedWorkspacesIdSettingsDataRoute:
      AuthenticatedWorkspacesIdSettingsDataRoute,
    AuthenticatedWorkspacesIdSettingsGeneralRoute:
      AuthenticatedWorkspacesIdSettingsGeneralRoute,
    AuthenticatedWorkspacesIdSettingsMcpTokensRoute:
      AuthenticatedWorkspacesIdSettingsMcpTokensRoute,
    AuthenticatedWorkspacesIdSettingsPublicSharesRoute:
      AuthenticatedWorkspacesIdSettingsPublicSharesRouteWithChildren,
    AuthenticatedWorkspacesIdSettingsWebhooksRoute:
      AuthenticatedWorkspacesIdSettingsWebhooksRoute,
    AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute:
      AuthenticatedWorkspacesIdSettingsWeeklyDigestRoute,
    AuthenticatedWorkspacesIdSettingsIndexRoute:
      AuthenticatedWorkspacesIdSettingsIndexRoute,
    AuthenticatedWorkspacesIdSettingsAiMetricsRoute:
      AuthenticatedWorkspacesIdSettingsAiMetricsRoute,
  };

const AuthenticatedWorkspacesIdSettingsRouteWithChildren =
  AuthenticatedWorkspacesIdSettingsRoute._addFileChildren(
    AuthenticatedWorkspacesIdSettingsRouteChildren,
  );

interface AuthenticatedWorkspacesIdRouteChildren {
  AuthenticatedWorkspacesIdProjectsRoute: typeof AuthenticatedWorkspacesIdProjectsRouteWithChildren;
  AuthenticatedWorkspacesIdRemindersRoute: typeof AuthenticatedWorkspacesIdRemindersRoute;
  AuthenticatedWorkspacesIdSettingsRoute: typeof AuthenticatedWorkspacesIdSettingsRouteWithChildren;
  AuthenticatedWorkspacesIdTimeboxesRoute: typeof AuthenticatedWorkspacesIdTimeboxesRoute;
  AuthenticatedWorkspacesIdTimelineRoute: typeof AuthenticatedWorkspacesIdTimelineRoute;
  AuthenticatedWorkspacesIdInsightsPriorityRoute: typeof AuthenticatedWorkspacesIdInsightsPriorityRoute;
  AuthenticatedWorkspacesIdTasksArchivedRoute: typeof AuthenticatedWorkspacesIdTasksArchivedRoute;
  AuthenticatedWorkspacesIdTasksDraftsRoute: typeof AuthenticatedWorkspacesIdTasksDraftsRoute;
  AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute: typeof AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute;
}

const AuthenticatedWorkspacesIdRouteChildren: AuthenticatedWorkspacesIdRouteChildren =
  {
    AuthenticatedWorkspacesIdProjectsRoute:
      AuthenticatedWorkspacesIdProjectsRouteWithChildren,
    AuthenticatedWorkspacesIdRemindersRoute:
      AuthenticatedWorkspacesIdRemindersRoute,
    AuthenticatedWorkspacesIdSettingsRoute:
      AuthenticatedWorkspacesIdSettingsRouteWithChildren,
    AuthenticatedWorkspacesIdTimeboxesRoute:
      AuthenticatedWorkspacesIdTimeboxesRoute,
    AuthenticatedWorkspacesIdTimelineRoute:
      AuthenticatedWorkspacesIdTimelineRoute,
    AuthenticatedWorkspacesIdInsightsPriorityRoute:
      AuthenticatedWorkspacesIdInsightsPriorityRoute,
    AuthenticatedWorkspacesIdTasksArchivedRoute:
      AuthenticatedWorkspacesIdTasksArchivedRoute,
    AuthenticatedWorkspacesIdTasksDraftsRoute:
      AuthenticatedWorkspacesIdTasksDraftsRoute,
    AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute:
      AuthenticatedWorkspacesIdCalendarsCalIdEventsEvtIdRoute,
  };

const AuthenticatedWorkspacesIdRouteWithChildren =
  AuthenticatedWorkspacesIdRoute._addFileChildren(
    AuthenticatedWorkspacesIdRouteChildren,
  );

interface AuthenticatedWorkspacesRouteChildren {
  AuthenticatedWorkspacesIdRoute: typeof AuthenticatedWorkspacesIdRouteWithChildren;
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute;
}

const AuthenticatedWorkspacesRouteChildren: AuthenticatedWorkspacesRouteChildren =
  {
    AuthenticatedWorkspacesIdRoute: AuthenticatedWorkspacesIdRouteWithChildren,
    AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  };

const AuthenticatedWorkspacesRouteWithChildren =
  AuthenticatedWorkspacesRoute._addFileChildren(
    AuthenticatedWorkspacesRouteChildren,
  );

interface AuthenticatedProjectsProjectIdTasksRouteChildren {
  AuthenticatedProjectsProjectIdTasksIndexRoute: typeof AuthenticatedProjectsProjectIdTasksIndexRoute;
}

const AuthenticatedProjectsProjectIdTasksRouteChildren: AuthenticatedProjectsProjectIdTasksRouteChildren =
  {
    AuthenticatedProjectsProjectIdTasksIndexRoute:
      AuthenticatedProjectsProjectIdTasksIndexRoute,
  };

const AuthenticatedProjectsProjectIdTasksRouteWithChildren =
  AuthenticatedProjectsProjectIdTasksRoute._addFileChildren(
    AuthenticatedProjectsProjectIdTasksRouteChildren,
  );

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdGanttRoute: typeof AuthenticatedProjectsProjectIdGanttRoute;
  AuthenticatedProjectsProjectIdTasksRoute: typeof AuthenticatedProjectsProjectIdTasksRouteWithChildren;
  AuthenticatedProjectsProjectIdTimelineRoute: typeof AuthenticatedProjectsProjectIdTimelineRoute;
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute;
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdGanttRoute:
      AuthenticatedProjectsProjectIdGanttRoute,
    AuthenticatedProjectsProjectIdTasksRoute:
      AuthenticatedProjectsProjectIdTasksRouteWithChildren,
    AuthenticatedProjectsProjectIdTimelineRoute:
      AuthenticatedProjectsProjectIdTimelineRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  };

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute;
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute;
  AuthenticatedPagesRoute: typeof AuthenticatedPagesRouteWithChildren;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren;
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute;
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute;
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRouteWithChildren;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren;
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedPagesRoute: AuthenticatedPagesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  InvitesAcceptRoute: InvitesAcceptRoute,
  PublicLensesTokenRoute: PublicLensesTokenRoute,
  ShareCalTokenRoute: ShareCalTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
