// This file is auto-generated by `make gen-time-sdk`.
// Do not edit manually.

// biome-ignore lint/style/useNamingConvention: generated OpenAPI types
export type paths = Record<string, never>;
// biome-ignore lint/style/useNamingConvention: generated OpenAPI types
export type components = Record<string, never>;
// biome-ignore lint/style/useNamingConvention: generated OpenAPI types
export type operations = Record<string, never>;
