-- ====================================
-- pages
-- Wiki/documentation pages with tree structure.
-- A page belongs to a workspace and optionally scopes to a project.
-- Self-referential parent_page_id enables nested page hierarchies.
-- ====================================
CREATE TABLE pages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  project_id INT UNSIGNED NULL COMMENT 'Internal FK to projects.id (NULL = workspace-wide)',
  creator_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',
  parent_page_id INT UNSIGNED NULL COMMENT 'Internal FK to pages.id (NULL = root page)',

  title VARCHAR(500) NOT NULL COMMENT 'Page title',
  body MEDIUMTEXT NOT NULL COMMENT 'Page content',
  is_ai_generated BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether the page was generated by AI',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order among siblings',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_pages_public_id (public_id),
  KEY idx_pages_workspace_id_enabled_sort_weight (workspace_id, enabled, sort_weight),
  KEY idx_pages_workspace_id_project_id (workspace_id, project_id),
  KEY idx_pages_parent_page_id (parent_page_id),
  FULLTEXT KEY ft_pages_title (title),

  CONSTRAINT fk_pages_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_pages_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_pages_creator FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_pages_parent FOREIGN KEY (parent_page_id) REFERENCES pages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Wiki/documentation pages with tree structure';
