import { render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { axe } from 'vitest-axe';
import Input from '../input/input';
import FormField from './form-field';

const THEMES = ['aurora-light', 'aurora-dark', 'dotline-light', 'dotline-dark'] as const;

describe.each(THEMES)('FormField [%s]', (theme) => {
  beforeEach(() => {
    document.documentElement.setAttribute('data-theme', theme);
  });
  afterEach(() => {
    document.documentElement.removeAttribute('data-theme');
  });

  it('wires label + description and has no a11y violations', async () => {
    const { container } = render(
      <FormField label="Email" description="We never share it.">
        {(c) => <Input {...c} />}
      </FormField>,
    );
    const input = screen.getByLabelText('Email') as HTMLInputElement;
    const describedBy = input.getAttribute('aria-describedby');
    expect(describedBy).toBeTruthy();
    expect(input.getAttribute('aria-invalid')).toBeNull();
    expect(await axe(container)).toHaveNoViolations();
  });

  it('applies aria-invalid when error is provided', async () => {
    const { container } = render(
      <FormField label="Name" error="Required">
        {(c) => <Input {...c} />}
      </FormField>,
    );
    const input = screen.getByLabelText('Name') as HTMLInputElement;
    expect(input.getAttribute('aria-invalid')).toBe('true');
    expect(screen.getByText('Required')).toBeDefined();
    expect(await axe(container)).toHaveNoViolations();
  });

  it('renders required indicator', () => {
    render(
      <FormField label="Handle" required>
        {(c) => <Input {...c} />}
      </FormField>,
    );
    expect(screen.getByText('*')).toBeDefined();
  });

  it('wires label to the rendered input via htmlFor / id', () => {
    render(<FormField label="Email">{(c) => <Input {...c} />}</FormField>);
    const input = screen.getByLabelText('Email') as HTMLInputElement;
    // The control id is generated by useId() and forwarded onto the input.
    // The label's htmlFor must match — getByLabelText already proves this,
    // but we assert the underlying ids explicitly to lock the contract.
    const labelEl = document.querySelector(`label[for="${input.id}"]`) as HTMLLabelElement | null;
    expect(labelEl).not.toBeNull();
    expect(labelEl?.textContent).toContain('Email');
  });

  it('links the hint via aria-describedby (hint-only)', () => {
    render(
      <FormField label="Handle" description="3-32 letters or digits">
        {(c) => <Input {...c} />}
      </FormField>,
    );
    const input = screen.getByLabelText('Handle') as HTMLInputElement;
    const describedBy = input.getAttribute('aria-describedby');
    expect(describedBy).not.toBeNull();
    // Every id in aria-describedby must resolve to an element whose text
    // content includes the hint copy. Otherwise screen readers will
    // announce stale or missing ids.
    const ids = (describedBy ?? '').split(/\s+/).filter(Boolean);
    expect(ids.length).toBeGreaterThanOrEqual(1);
    const matched = ids.some((id) =>
      document.getElementById(id)?.textContent?.includes('3-32 letters or digits'),
    );
    expect(matched).toBe(true);
  });

  it('links both hint AND error via aria-describedby (combined)', () => {
    render(
      <FormField label="Handle" description="3-32 letters or digits" error="Already taken">
        {(c) => <Input {...c} />}
      </FormField>,
    );
    const input = screen.getByLabelText('Handle') as HTMLInputElement;
    const ids = (input.getAttribute('aria-describedby') ?? '').split(/\s+/).filter(Boolean);
    // Both the hint and the error must be referenced so AT users hear the
    // requirement AND the failure when the input is focused.
    expect(ids.length).toBe(2);
    const texts = ids.map((id) => document.getElementById(id)?.textContent ?? '');
    expect(texts.some((t) => t.includes('3-32 letters or digits'))).toBe(true);
    expect(texts.some((t) => t.includes('Already taken'))).toBe(true);
    expect(input.getAttribute('aria-invalid')).toBe('true');
  });

  it('omits aria-describedby entirely when no hint and no error are provided', () => {
    render(<FormField label="Email">{(c) => <Input {...c} />}</FormField>);
    const input = screen.getByLabelText('Email') as HTMLInputElement;
    expect(input.getAttribute('aria-describedby')).toBeNull();
  });
});
