// Code generated by gen-signal-kinds. DO NOT EDIT.
//
// Source: signal_kinds/*.yaml
// Regenerate with: go run scripts/gen-signal-kinds.go

export type SignalRetention = "stateful" | "discrete";
export type SignalAutonomy = "suggest" | "draft" | "auto";
export type SignalSubjectType =
  | "user"
  | "task"
  | "workspace"
  | "calendar_event";

export interface SignalKindDefinition {
  readonly kind: string;
  readonly source: string;
  readonly retention: SignalRetention;
  readonly autonomyDefault: SignalAutonomy;
  readonly subjectTypeDefault: SignalSubjectType;
  readonly description: string;
  readonly i18nKey: string;
}

export const SIGNAL_KINDS = [
  {
    kind: "calendar.event_day_arrived",
    source: "calendar",
    retention: "discrete",
    autonomyDefault: "draft",
    subjectTypeDefault: "calendar_event",
    description: "Internal scheduler tick when a calendar event's start_date arrives in workspace local time",
    i18nKey: "signalKinds.calendar.eventDayArrived",
  },
  {
    kind: "discord.presence",
    source: "discord",
    retention: "stateful",
    autonomyDefault: "suggest",
    subjectTypeDefault: "user",
    description: "User online status from Discord gateway",
    i18nKey: "signalKinds.discord.presence",
  },
  {
    kind: "manual",
    source: "manual",
    retention: "discrete",
    autonomyDefault: "auto",
    subjectTypeDefault: "user",
    description: "User-emitted signal from UI or CLI",
    i18nKey: "signalKinds.manual",
  },
  {
    kind: "slack.presence",
    source: "slack",
    retention: "stateful",
    autonomyDefault: "suggest",
    subjectTypeDefault: "user",
    description: "User active/away status from Slack Events API",
    i18nKey: "signalKinds.slack.presence",
  },
] as const satisfies readonly SignalKindDefinition[];

export type SignalKind = (typeof SIGNAL_KINDS)[number]["kind"];

const BY_KIND: ReadonlyMap<string, SignalKindDefinition> = new Map(
  SIGNAL_KINDS.map((d) => [d.kind, d]),
);

/**
 * Look up a signal-kind definition by its dotted identifier.
 * Returns undefined when the kind is not in the registry.
 */
export function lookup(kind: string): SignalKindDefinition | undefined {
  return BY_KIND.get(kind);
}
