// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// AI.AGENT.NOT_FOUND — AI agent not found
	AiAgentNotFound = &Spec{Code: "AI.AGENT.NOT_FOUND", Status: 404, Message: "AI agent not found"}
	// AI.AGENT.PAUSED — AI agent is paused
	AiAgentPaused = &Spec{Code: "AI.AGENT.PAUSED", Status: 409, Message: "AI agent is paused"}
	// AI.AGENT.RUNTIME_DISABLED — AI agent runtime is not configured
	AiAgentRuntimeDisabled = &Spec{Code: "AI.AGENT.RUNTIME_DISABLED", Status: 503, Message: "AI agent runtime is not configured"}
	// AI.COST.GUARD_EXCEEDED — AI cost guard threshold exceeded
	AiCostGuardExceeded = &Spec{Code: "AI.COST.GUARD_EXCEEDED", Status: 402, Message: "AI cost guard threshold exceeded"}
	// AI.MODEL.NOT_FOUND — AI model not found
	AiModelNotFound = &Spec{Code: "AI.MODEL.NOT_FOUND", Status: 404, Message: "AI model not found"}
	// AI.NL_QUERY.UNPARSEABLE — Could not turn that into a filter
	AiNlQueryUnparseable = &Spec{Code: "AI.NL_QUERY.UNPARSEABLE", Status: 422, Message: "Could not turn that into a filter"}
	// AI.PROVIDER.NOT_CONFIGURED — AI provider is not configured
	AiProviderNotConfigured = &Spec{Code: "AI.PROVIDER.NOT_CONFIGURED", Status: 412, Message: "AI provider is not configured"}
	// AI.PROVIDER.UPSTREAM_AUTH_REJECTED — AI provider rejected credentials
	AiProviderUpstreamAuthRejected = &Spec{Code: "AI.PROVIDER.UPSTREAM_AUTH_REJECTED", Status: 502, Message: "AI provider rejected credentials"}
	// AI.PROVIDER.UPSTREAM_RATE_LIMITED — AI provider rate limit exceeded
	AiProviderUpstreamRateLimited = &Spec{Code: "AI.PROVIDER.UPSTREAM_RATE_LIMITED", Status: 429, Message: "AI provider rate limit exceeded"}
	// AI.PROVIDER.UPSTREAM_REQUEST_REJECTED — AI provider rejected the request
	AiProviderUpstreamRequestRejected = &Spec{Code: "AI.PROVIDER.UPSTREAM_REQUEST_REJECTED", Status: 502, Message: "AI provider rejected the request"}
	// AI.PROVIDER.UPSTREAM_TIMEOUT — AI provider call timed out
	AiProviderUpstreamTimeout = &Spec{Code: "AI.PROVIDER.UPSTREAM_TIMEOUT", Status: 504, Message: "AI provider call timed out"}
	// AI.PROVIDER.UPSTREAM_UNREACHABLE — Could not reach AI provider
	AiProviderUpstreamUnreachable = &Spec{Code: "AI.PROVIDER.UPSTREAM_UNREACHABLE", Status: 502, Message: "Could not reach AI provider"}
	// AI.REDACTION.LENS_UNAVAILABLE — Redaction lens is unavailable
	AiRedactionLensUnavailable = &Spec{Code: "AI.REDACTION.LENS_UNAVAILABLE", Status: 500, Message: "Redaction lens is unavailable"}
	// AI.REDACTION.RULE_INVALID — Redaction rule is invalid
	AiRedactionRuleInvalid = &Spec{Code: "AI.REDACTION.RULE_INVALID", Status: 500, Message: "Redaction rule is invalid"}
	// AI.REDACTION.TIMEOUT — Redaction pipeline timed out
	AiRedactionTimeout = &Spec{Code: "AI.REDACTION.TIMEOUT", Status: 504, Message: "Redaction pipeline timed out"}
	// AI.RESPONSE.INVALID_JSON — AI provider response was not valid JSON
	AiResponseInvalidJson = &Spec{Code: "AI.RESPONSE.INVALID_JSON", Status: 502, Message: "AI provider response was not valid JSON"}
	// AI.RESPONSE.MISSING_FIELD — AI provider response is missing a required field
	AiResponseMissingField = &Spec{Code: "AI.RESPONSE.MISSING_FIELD", Status: 502, Message: "AI provider response is missing a required field"}
	// AI.RESPONSE.SCHEMA_MISMATCH — AI provider response did not match the expected schema
	AiResponseSchemaMismatch = &Spec{Code: "AI.RESPONSE.SCHEMA_MISMATCH", Status: 502, Message: "AI provider response did not match the expected schema"}
	// AI.SAFETY.BLOCKED — Request blocked by safety policy
	AiSafetyBlocked = &Spec{Code: "AI.SAFETY.BLOCKED", Status: 422, Message: "Request blocked by safety policy"}
)
