// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// INTEGRATION.GOOGLE.WEBHOOK_INVALID_TOKEN — Google push channel token verification failed
	IntegrationGoogleWebhookInvalidToken = &Spec{Code: "INTEGRATION.GOOGLE.WEBHOOK_INVALID_TOKEN", Status: 401, Message: "Google push channel token verification failed"}
)
