// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// SHARE.SHARE.DELETE_FORBIDDEN — Only workspace admins or owners can delete a share
	ShareShareDeleteForbidden = &Spec{Code: "SHARE.SHARE.DELETE_FORBIDDEN", Status: 403, Message: "Only workspace admins or owners can delete a share"}
	// SHARE.SHARE.EXPIRED — Share page has expired
	ShareShareExpired = &Spec{Code: "SHARE.SHARE.EXPIRED", Status: 410, Message: "Share page has expired"}
	// SHARE.SHARE.NOT_FOUND — Share page not found
	ShareShareNotFound = &Spec{Code: "SHARE.SHARE.NOT_FOUND", Status: 404, Message: "Share page not found"}
	// SHARE.SHARE.TOKEN_INVALID — Share token is invalid
	ShareShareTokenInvalid = &Spec{Code: "SHARE.SHARE.TOKEN_INVALID", Status: 404, Message: "Share token is invalid"}
	// SHARE.SHARE_EVENT.REORDER_INVALID — Reorder input must be a permutation of the share's current events
	ShareShareEventReorderInvalid = &Spec{Code: "SHARE.SHARE_EVENT.REORDER_INVALID", Status: 400, Message: "Reorder input must be a permutation of the share's current events"}
)
