// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// SHARE.SHARE.DELETE_FORBIDDEN — Only workspace admins or owners can delete a share
	ShareShareDeleteForbidden = &Spec{Code: "SHARE.SHARE.DELETE_FORBIDDEN", Status: 403, Message: "Only workspace admins or owners can delete a share", Description: "Returned when a non-admin tries to delete a share. Create / edit / rotate / add events are open to all non-guest workspace members; delete is restricted to admin/owner to prevent accidental URL loss.", UserAction: "Ask a workspace admin or owner to delete the share on your behalf."}
	// SHARE.SHARE.EXPIRED — Share page has expired
	ShareShareExpired = &Spec{Code: "SHARE.SHARE.EXPIRED", Status: 410, Message: "Share page has expired", Description: "Returned when the share's expires_at is in the past. The row still exists but the public render refuses to serve it.", UserAction: "Ask a workspace member to extend or rotate the share, then use the new URL."}
	// SHARE.SHARE.EXPIRES_AT_NOT_IN_FUTURE — Share expiry must be in the future
	ShareShareExpiresAtNotInFuture = &Spec{Code: "SHARE.SHARE.EXPIRES_AT_NOT_IN_FUTURE", Status: 422, Message: "Share expiry must be in the future", Description: "Returned when a share is created or updated with an expires_at that is not later than the time the request is handled, which would produce a share that is already expired when it is returned. Distinct from SHARE.SHARE.EXPIRED, which refuses a reader whose share has since run out.", UserAction: "Pick an expiry timestamp later than the current time, or omit it for a share that does not expire."}
	// SHARE.SHARE.EXPIRES_AT_OUT_OF_RANGE — Share expiry is outside the range this field can hold
	ShareShareExpiresAtOutOfRange = &Spec{Code: "SHARE.SHARE.EXPIRES_AT_OUT_OF_RANGE", Status: 422, Message: "Share expiry is outside the range this field can hold", Description: "Returned when a share is created or updated with an expires_at that the stored expiry field cannot represent, so the value could never be persisted or read back. The bound is the representable range of the field itself, not a policy limit on how far ahead a share may be scheduled. Distinct from SHARE.SHARE.EXPIRES_AT_NOT_IN_FUTURE, which refuses a writer setting a moment that has already passed, and from SHARE.SHARE.EXPIRED, which refuses a reader whose share has since run out.", UserAction: "Pick an expiry timestamp within the range the field accepts, or omit it for a share that does not expire."}
	// SHARE.SHARE.NOT_FOUND — Share page not found
	ShareShareNotFound = &Spec{Code: "SHARE.SHARE.NOT_FOUND", Status: 404, Message: "Share page not found", Description: "Returned when a share with the given public_id or token hash does not exist.", UserAction: "Verify the URL; if you rotated the token recently, use the new URL returned at rotate time."}
	// SHARE.SHARE.TOKEN_INVALID — Share token is invalid
	ShareShareTokenInvalid = &Spec{Code: "SHARE.SHARE.TOKEN_INVALID", Status: 404, Message: "Share token is invalid", Description: "Returned when the URL token does not match any token_hash. Deliberately 404 (not 401) so the existence of any share is not leaked by the status code.", UserAction: "Verify the URL was copied correctly. Rotation invalidates prior tokens."}
	// SHARE.SHARE_EVENT.NOT_FOUND — Event is not on this share
	ShareShareEventNotFound = &Spec{Code: "SHARE.SHARE_EVENT.NOT_FOUND", Status: 404, Message: "Event is not on this share", Description: "Returned when detaching an event that is not attached to the share, or was already detached.", UserAction: "Refresh the share and try again."}
	// SHARE.SHARE_EVENT.REORDER_INVALID — Reorder input must be a permutation of the share's current events
	ShareShareEventReorderInvalid = &Spec{Code: "SHARE.SHARE_EVENT.REORDER_INVALID", Status: 400, Message: "Reorder input must be a permutation of the share's current events", Description: "Returned when a batch reorder request supplies a linkPublicIds array that is missing an existing link, references a link that does not belong to the share, or contains duplicates. The reorder is atomic and requires the full current set.", UserAction: "Refetch the share's event list and resubmit the reorder with every current link exactly once."}
)
