/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces';
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security';
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile';
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin';
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index';
import { Route as AuthenticatedWorkspacesWsIdRouteImport } from './routes/_authenticated/workspaces_.$wsId';
import { Route as AuthenticatedAdminWorkspacesRouteImport } from './routes/_authenticated/admin/workspaces';
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users';
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin/stats';
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings';
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs';
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins';
import { Route as AuthenticatedAdminWorkspacesWsIdRouteImport } from './routes/_authenticated/admin/workspaces_.$wsId';
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users_.$userId';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const AuthenticatedWorkspacesWsIdRoute =
  AuthenticatedWorkspacesWsIdRouteImport.update({
    id: '/workspaces_/$wsId',
    path: '/workspaces/$wsId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminWorkspacesRoute =
  AuthenticatedAdminWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminWorkspacesWsIdRoute =
  AuthenticatedAdminWorkspacesWsIdRouteImport.update({
    id: '/workspaces_/$wsId',
    path: '/workspaces/$wsId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users_/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/admin': typeof AuthenticatedAdminRouteWithChildren;
  '/profile': typeof AuthenticatedProfileRoute;
  '/security': typeof AuthenticatedSecurityRoute;
  '/workspaces': typeof AuthenticatedWorkspacesRoute;
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute;
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute;
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute;
  '/admin/stats': typeof AuthenticatedAdminStatsRoute;
  '/admin/users': typeof AuthenticatedAdminUsersRoute;
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute;
  '/workspaces/$wsId': typeof AuthenticatedWorkspacesWsIdRoute;
  '/admin/': typeof AuthenticatedAdminIndexRoute;
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute;
  '/admin/workspaces/$wsId': typeof AuthenticatedAdminWorkspacesWsIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/profile': typeof AuthenticatedProfileRoute;
  '/security': typeof AuthenticatedSecurityRoute;
  '/workspaces': typeof AuthenticatedWorkspacesRoute;
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute;
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute;
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute;
  '/admin/stats': typeof AuthenticatedAdminStatsRoute;
  '/admin/users': typeof AuthenticatedAdminUsersRoute;
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute;
  '/workspaces/$wsId': typeof AuthenticatedWorkspacesWsIdRoute;
  '/admin': typeof AuthenticatedAdminIndexRoute;
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute;
  '/admin/workspaces/$wsId': typeof AuthenticatedAdminWorkspacesWsIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren;
  '/_authenticated/profile': typeof AuthenticatedProfileRoute;
  '/_authenticated/security': typeof AuthenticatedSecurityRoute;
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute;
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute;
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute;
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute;
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute;
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute;
  '/_authenticated/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute;
  '/_authenticated/workspaces_/$wsId': typeof AuthenticatedWorkspacesWsIdRoute;
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute;
  '/_authenticated/admin/users_/$userId': typeof AuthenticatedAdminUsersUserIdRoute;
  '/_authenticated/admin/workspaces_/$wsId': typeof AuthenticatedAdminWorkspacesWsIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/profile'
    | '/security'
    | '/workspaces'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/workspaces'
    | '/workspaces/$wsId'
    | '/admin/'
    | '/admin/users/$userId'
    | '/admin/workspaces/$wsId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/profile'
    | '/security'
    | '/workspaces'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/workspaces'
    | '/workspaces/$wsId'
    | '/admin'
    | '/admin/users/$userId'
    | '/admin/workspaces/$wsId';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/security'
    | '/_authenticated/workspaces'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workspaces'
    | '/_authenticated/workspaces_/$wsId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/users_/$userId'
    | '/_authenticated/admin/workspaces_/$wsId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces';
      path: '/workspaces';
      fullPath: '/workspaces';
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/security': {
      id: '/_authenticated/security';
      path: '/security';
      fullPath: '/security';
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/profile': {
      id: '/_authenticated/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof AuthenticatedProfileRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin': {
      id: '/_authenticated/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AuthenticatedAdminRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/';
      path: '/';
      fullPath: '/admin/';
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/workspaces_/$wsId': {
      id: '/_authenticated/workspaces_/$wsId';
      path: '/workspaces/$wsId';
      fullPath: '/workspaces/$wsId';
      preLoaderRoute: typeof AuthenticatedWorkspacesWsIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/workspaces': {
      id: '/_authenticated/admin/workspaces';
      path: '/workspaces';
      fullPath: '/admin/workspaces';
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users';
      path: '/users';
      fullPath: '/admin/users';
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats';
      path: '/stats';
      fullPath: '/admin/stats';
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings';
      path: '/settings';
      fullPath: '/admin/settings';
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs';
      path: '/audit-logs';
      fullPath: '/admin/audit-logs';
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins';
      path: '/admins';
      fullPath: '/admin/admins';
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/workspaces_/$wsId': {
      id: '/_authenticated/admin/workspaces_/$wsId';
      path: '/workspaces/$wsId';
      fullPath: '/admin/workspaces/$wsId';
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesWsIdRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/users_/$userId': {
      id: '/_authenticated/admin/users_/$userId';
      path: '/users/$userId';
      fullPath: '/admin/users/$userId';
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute;
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute;
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute;
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute;
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute;
  AuthenticatedAdminWorkspacesRoute: typeof AuthenticatedAdminWorkspacesRoute;
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute;
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute;
  AuthenticatedAdminWorkspacesWsIdRoute: typeof AuthenticatedAdminWorkspacesWsIdRoute;
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkspacesRoute: AuthenticatedAdminWorkspacesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  AuthenticatedAdminWorkspacesWsIdRoute: AuthenticatedAdminWorkspacesWsIdRoute,
};

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren;
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute;
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute;
  AuthenticatedWorkspacesWsIdRoute: typeof AuthenticatedWorkspacesWsIdRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedWorkspacesWsIdRoute: AuthenticatedWorkspacesWsIdRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
