package embed

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"math"
)

// MockProvider is a deterministic in-process embedding provider used by
// development and tests. It derives a reproducible
// 768-dim vector from the SHA-256 of the input text, so the same input
// always produces the same vector across machines, CI runs, and
// processes. Cosine similarity between two mock vectors is therefore a
// stable function of their input texts — exactly what the
// duplicate-detection tests need.
type MockProvider struct{}

// NewMockProvider returns a ready-to-use MockProvider.
func NewMockProvider() *MockProvider { return &MockProvider{} }

// Model implements Provider.
func (MockProvider) Model() string { return "mock-768" }

// Embed implements Provider. The vector is generated by hashing the
// input, seeding a tiny deterministic PRNG, and emitting Dim floats in
// [-1, 1]. The Client normalizes the result afterwards.
func (MockProvider) Embed(_ context.Context, text string) ([]float32, error) {
	sum := sha256.Sum256([]byte(text))
	var state uint64
	for i := 0; i < 4; i++ {
		state ^= binary.LittleEndian.Uint64(sum[i*8 : i*8+8])
	}
	if state == 0 {
		state = 0x9e3779b97f4a7c15
	}
	out := make([]float32, Dim)
	for i := 0; i < Dim; i++ {
		// splitmix64 — cheap, deterministic, good enough for fixture
		// vectors that only need to be reproducible.
		state += 0x9e3779b97f4a7c15
		z := state
		z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9
		z = (z ^ (z >> 27)) * 0x94d049bb133111eb
		z ^= z >> 31
		// Map to [-1, 1).
		f := float64(int64(z)) / float64(math.MaxInt64)
		out[i] = float32(f)
	}
	return out, nil
}
