// Code generated by gen-errors. DO NOT EDIT.

export const AiErrors = {
  AI_AGENT_NOT_FOUND: {
    code: "AI.AGENT.NOT_FOUND",
    status: 404,
    message: "AI agent not found",
  },
  AI_AGENT_PAUSED: {
    code: "AI.AGENT.PAUSED",
    status: 409,
    message: "AI agent is paused",
  },
  AI_AGENT_RUNTIME_DISABLED: {
    code: "AI.AGENT.RUNTIME_DISABLED",
    status: 503,
    message: "AI agent runtime is not configured",
  },
  AI_COST_GUARD_EXCEEDED: {
    code: "AI.COST.GUARD_EXCEEDED",
    status: 402,
    message: "Daily AI spend limit reached",
  },
  AI_MODEL_NOT_FOUND: {
    code: "AI.MODEL.NOT_FOUND",
    status: 404,
    message: "AI model not found",
  },
  AI_NL_QUERY_UNPARSEABLE: {
    code: "AI.NL_QUERY.UNPARSEABLE",
    status: 422,
    message: "Could not turn that into a filter",
  },
  AI_PROVIDER_BASE_URL_NOT_ALLOWED: {
    code: "AI.PROVIDER.BASE_URL_NOT_ALLOWED",
    status: 412,
    message: "AI provider endpoint is not an allowed destination",
  },
  AI_PROVIDER_KEY_DECRYPT_FAILED: {
    code: "AI.PROVIDER.KEY_DECRYPT_FAILED",
    status: 412,
    message: "AI provider API key could not be unsealed",
  },
  AI_PROVIDER_NOT_CONFIGURED: {
    code: "AI.PROVIDER.NOT_CONFIGURED",
    status: 412,
    message: "AI provider is not configured",
  },
  AI_PROVIDER_NOT_FOUND: {
    code: "AI.PROVIDER.NOT_FOUND",
    status: 404,
    message: "AI provider not found",
  },
  AI_PROVIDER_UPSTREAM_AUTH_REJECTED: {
    code: "AI.PROVIDER.UPSTREAM_AUTH_REJECTED",
    status: 502,
    message: "AI provider rejected credentials",
  },
  AI_PROVIDER_UPSTREAM_RATE_LIMITED: {
    code: "AI.PROVIDER.UPSTREAM_RATE_LIMITED",
    status: 429,
    message: "AI provider rate limit exceeded",
  },
  AI_PROVIDER_UPSTREAM_REQUEST_REJECTED: {
    code: "AI.PROVIDER.UPSTREAM_REQUEST_REJECTED",
    status: 502,
    message: "AI provider rejected the request",
  },
  AI_PROVIDER_UPSTREAM_TIMEOUT: {
    code: "AI.PROVIDER.UPSTREAM_TIMEOUT",
    status: 504,
    message: "AI provider call timed out",
  },
  AI_PROVIDER_UPSTREAM_UNREACHABLE: {
    code: "AI.PROVIDER.UPSTREAM_UNREACHABLE",
    status: 502,
    message: "Could not reach AI provider",
  },
  AI_REDACTION_LENS_UNAVAILABLE: {
    code: "AI.REDACTION.LENS_UNAVAILABLE",
    status: 500,
    message: "Redaction lens is unavailable",
  },
  AI_REDACTION_RULE_INVALID: {
    code: "AI.REDACTION.RULE_INVALID",
    status: 500,
    message: "Redaction rule is invalid",
  },
  AI_REDACTION_TIMEOUT: {
    code: "AI.REDACTION.TIMEOUT",
    status: 504,
    message: "Redaction pipeline timed out",
  },
  AI_RESPONSE_INVALID_JSON: {
    code: "AI.RESPONSE.INVALID_JSON",
    status: 502,
    message: "AI provider response was not valid JSON",
  },
  AI_RESPONSE_MISSING_FIELD: {
    code: "AI.RESPONSE.MISSING_FIELD",
    status: 502,
    message: "AI provider response is missing a required field",
  },
  AI_RESPONSE_SCHEMA_MISMATCH: {
    code: "AI.RESPONSE.SCHEMA_MISMATCH",
    status: 502,
    message: "AI provider response did not match the expected schema",
  },
  AI_REVERSE_ALREADY_REVERSED: {
    code: "AI.REVERSE.ALREADY_REVERSED",
    status: 409,
    message: "Event already has a compensating reverse.",
  },
  AI_REVERSE_NOT_LLM_ORIGIN: {
    code: "AI.REVERSE.NOT_LLM_ORIGIN",
    status: 403,
    message: "Cannot reverse an event that did not originate from an LLM agent.",
  },
  AI_REVERSE_TARGET_NOT_FOUND: {
    code: "AI.REVERSE.TARGET_NOT_FOUND",
    status: 404,
    message: "Event not found in this workspace.",
  },
  AI_SAFETY_BLOCKED: {
    code: "AI.SAFETY.BLOCKED",
    status: 422,
    message: "Request blocked by safety policy",
  },
} as const;

export type AiErrorCode = (typeof AiErrors)[keyof typeof AiErrors]["code"];
