// Code generated by gen-errors. DO NOT EDIT.

export const CalendarErrors = {
  CALENDAR_ATTACHMENT_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.ATTACHMENT.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve attachments",
  },
  CALENDAR_ATTACHMENT_NOT_FOUND: {
    code: "CALENDAR.ATTACHMENT.NOT_FOUND",
    status: 404,
    message: "Attachment not found",
  },
  CALENDAR_ATTACHMENT_STORE_DELETE_INTERRUPTED: {
    code: "CALENDAR.ATTACHMENT.STORE_DELETE_INTERRUPTED",
    status: 500,
    message: "Could not delete attachment",
  },
  CALENDAR_ATTACHMENT_STORE_READ_INTERRUPTED: {
    code: "CALENDAR.ATTACHMENT.STORE_READ_INTERRUPTED",
    status: 500,
    message: "Could not find attachment",
  },
  CALENDAR_ATTACHMENT_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.ATTACHMENT.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not save attachment",
  },
  CALENDAR_ATTACHMENT_UPLOADER_OR_OWNER_REQUIRED: {
    code: "CALENDAR.ATTACHMENT.UPLOADER_OR_OWNER_REQUIRED",
    status: 403,
    message: "Only the uploader or calendar owner can delete this attachment",
  },
  CALENDAR_ATTENDEE_CAN_EDIT_UPDATE_INTERRUPTED: {
    code: "CALENDAR.ATTENDEE.CAN_EDIT_UPDATE_INTERRUPTED",
    status: 500,
    message: "Could not update edit permission",
  },
  CALENDAR_ATTENDEE_OWNER_REQUIRED_TO_TOGGLE_EDIT: {
    code: "CALENDAR.ATTENDEE.OWNER_REQUIRED_TO_TOGGLE_EDIT",
    status: 403,
    message: "Only the event owner can change edit permissions",
  },
  CALENDAR_ATTENDEE_RSVP_UPDATE_INTERRUPTED: {
    code: "CALENDAR.ATTENDEE.RSVP_UPDATE_INTERRUPTED",
    status: 500,
    message: "Could not update RSVP",
  },
  CALENDAR_ATTENDEE_STORE_REMOVE_INTERRUPTED: {
    code: "CALENDAR.ATTENDEE.STORE_REMOVE_INTERRUPTED",
    status: 500,
    message: "Could not remove attendee",
  },
  CALENDAR_ATTENDEE_USER_ID_MALFORMED: {
    code: "CALENDAR.ATTENDEE.USER_ID_MALFORMED",
    status: 400,
    message: "Invalid user ID",
  },
  CALENDAR_ATTENDEE_USER_NOT_FOUND: {
    code: "CALENDAR.ATTENDEE.USER_NOT_FOUND",
    status: 404,
    message: "User not found",
  },
  CALENDAR_CALENDAR_ACCESS_DENIED: {
    code: "CALENDAR.CALENDAR.ACCESS_DENIED",
    status: 403,
    message: "You do not have access to this calendar",
  },
  CALENDAR_CALENDAR_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.CALENDAR.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve calendars",
  },
  CALENDAR_CALENDAR_MANAGER_ROLE_REQUIRED: {
    code: "CALENDAR.CALENDAR.MANAGER_ROLE_REQUIRED",
    status: 403,
    message: "You do not have permission to perform this action",
  },
  CALENDAR_CALENDAR_NOT_FOUND: {
    code: "CALENDAR.CALENDAR.NOT_FOUND",
    status: 404,
    message: "Calendar not found",
  },
  CALENDAR_CALENDAR_OWNER_ROLE_REQUIRED: {
    code: "CALENDAR.CALENDAR.OWNER_ROLE_REQUIRED",
    status: 403,
    message: "Only calendar owners can perform this action",
  },
  CALENDAR_CALENDAR_STORE_DELETE_INTERRUPTED: {
    code: "CALENDAR.CALENDAR.STORE_DELETE_INTERRUPTED",
    status: 500,
    message: "Could not delete calendar",
  },
  CALENDAR_CALENDAR_STORE_READ_INTERRUPTED: {
    code: "CALENDAR.CALENDAR.STORE_READ_INTERRUPTED",
    status: 500,
    message: "Could not read calendar after update",
  },
  CALENDAR_CALENDAR_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.CALENDAR.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not save calendar",
  },
  CALENDAR_CHECKLIST_ITEM_NOT_FOUND: {
    code: "CALENDAR.CHECKLIST.ITEM_NOT_FOUND",
    status: 404,
    message: "Checklist item not found",
  },
  CALENDAR_CHECKLIST_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.CHECKLIST.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve checklist items",
  },
  CALENDAR_CHECKLIST_STORE_DELETE_INTERRUPTED: {
    code: "CALENDAR.CHECKLIST.STORE_DELETE_INTERRUPTED",
    status: 500,
    message: "Could not delete checklist item",
  },
  CALENDAR_CHECKLIST_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.CHECKLIST.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not save checklist item",
  },
  CALENDAR_COMMENT_AUTHOR_OR_OWNER_REQUIRED: {
    code: "CALENDAR.COMMENT.AUTHOR_OR_OWNER_REQUIRED",
    status: 403,
    message: "Only the comment author or calendar owner can delete this comment",
  },
  CALENDAR_COMMENT_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.COMMENT.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve comments",
  },
  CALENDAR_COMMENT_NOT_FOUND: {
    code: "CALENDAR.COMMENT.NOT_FOUND",
    status: 404,
    message: "Comment not found",
  },
  CALENDAR_COMMENT_STORE_DELETE_INTERRUPTED: {
    code: "CALENDAR.COMMENT.STORE_DELETE_INTERRUPTED",
    status: 500,
    message: "Could not delete comment",
  },
  CALENDAR_COMMENT_STORE_READ_INTERRUPTED: {
    code: "CALENDAR.COMMENT.STORE_READ_INTERRUPTED",
    status: 500,
    message: "Could not find comment",
  },
  CALENDAR_COMMENT_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.COMMENT.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not save comment",
  },
  CALENDAR_EVENT_DATE_RANGE_UNPARSEABLE: {
    code: "CALENDAR.EVENT.DATE_RANGE_UNPARSEABLE",
    status: 422,
    message: "Could not parse date or datetime parameter",
  },
  CALENDAR_EVENT_EDIT_PERMISSION_REQUIRED: {
    code: "CALENDAR.EVENT.EDIT_PERMISSION_REQUIRED",
    status: 403,
    message: "You do not have permission to edit this event",
  },
  CALENDAR_EVENT_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.EVENT.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve events",
  },
  CALENDAR_EVENT_NOT_FOUND: {
    code: "CALENDAR.EVENT.NOT_FOUND",
    status: 404,
    message: "Event not found",
  },
  CALENDAR_EVENT_OWNER_USER_ID_MALFORMED: {
    code: "CALENDAR.EVENT.OWNER_USER_ID_MALFORMED",
    status: 400,
    message: "Invalid ownerUserId",
  },
  CALENDAR_EVENT_OWNER_USER_NOT_FOUND: {
    code: "CALENDAR.EVENT.OWNER_USER_NOT_FOUND",
    status: 400,
    message: "Owner user not found",
  },
  CALENDAR_EVENT_OWNER_USER_RESOLVE_INTERRUPTED: {
    code: "CALENDAR.EVENT.OWNER_USER_RESOLVE_INTERRUPTED",
    status: 500,
    message: "Could not resolve owner user",
  },
  CALENDAR_EVENT_STORE_DELETE_INTERRUPTED: {
    code: "CALENDAR.EVENT.STORE_DELETE_INTERRUPTED",
    status: 500,
    message: "Could not delete event",
  },
  CALENDAR_EVENT_STORE_READ_INTERRUPTED: {
    code: "CALENDAR.EVENT.STORE_READ_INTERRUPTED",
    status: 500,
    message: "Could not read event",
  },
  CALENDAR_EVENT_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.EVENT.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not save event",
  },
  CALENDAR_INVITE_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.INVITE.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve invites",
  },
  CALENDAR_INVITE_NOT_FOUND: {
    code: "CALENDAR.INVITE.NOT_FOUND",
    status: 404,
    message: "Invite not found or expired",
  },
  CALENDAR_INVITE_STORE_LOOKUP_INTERRUPTED: {
    code: "CALENDAR.INVITE.STORE_LOOKUP_INTERRUPTED",
    status: 500,
    message: "Could not look up invite",
  },
  CALENDAR_INVITE_STORE_REVOKE_INTERRUPTED: {
    code: "CALENDAR.INVITE.STORE_REVOKE_INTERRUPTED",
    status: 500,
    message: "Could not revoke invite",
  },
  CALENDAR_INVITE_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.INVITE.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not save invite",
  },
  CALENDAR_INVITE_TOKEN_GENERATE_INTERRUPTED: {
    code: "CALENDAR.INVITE.TOKEN_GENERATE_INTERRUPTED",
    status: 500,
    message: "Could not generate invite token",
  },
  CALENDAR_MEMBER_ALREADY_SUBSCRIBED: {
    code: "CALENDAR.MEMBER.ALREADY_SUBSCRIBED",
    status: 409,
    message: "User is already a member of this calendar",
  },
  CALENDAR_MEMBER_LAST_OWNER_REMOVAL_BLOCKED: {
    code: "CALENDAR.MEMBER.LAST_OWNER_REMOVAL_BLOCKED",
    status: 409,
    message: "Cannot remove the last owner of a calendar",
  },
  CALENDAR_MEMBER_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.MEMBER.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve members",
  },
  CALENDAR_MEMBER_NOT_FOUND: {
    code: "CALENDAR.MEMBER.NOT_FOUND",
    status: 404,
    message: "Member not found",
  },
  CALENDAR_MEMBER_OWNER_COUNT_QUERY_INTERRUPTED: {
    code: "CALENDAR.MEMBER.OWNER_COUNT_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not verify owner count",
  },
  CALENDAR_MEMBER_STORE_READ_INTERRUPTED: {
    code: "CALENDAR.MEMBER.STORE_READ_INTERRUPTED",
    status: 500,
    message: "Could not look up member",
  },
  CALENDAR_MEMBER_STORE_REMOVE_INTERRUPTED: {
    code: "CALENDAR.MEMBER.STORE_REMOVE_INTERRUPTED",
    status: 500,
    message: "Could not remove member",
  },
  CALENDAR_MEMBER_STORE_ROLE_UPDATE_INTERRUPTED: {
    code: "CALENDAR.MEMBER.STORE_ROLE_UPDATE_INTERRUPTED",
    status: 500,
    message: "Could not update member role",
  },
  CALENDAR_MEMBER_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.MEMBER.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not add member",
  },
  CALENDAR_MEMBER_USER_ID_MALFORMED: {
    code: "CALENDAR.MEMBER.USER_ID_MALFORMED",
    status: 400,
    message: "Invalid user ID",
  },
  CALENDAR_MEMBER_USER_NOT_FOUND: {
    code: "CALENDAR.MEMBER.USER_NOT_FOUND",
    status: 404,
    message: "User not found",
  },
  CALENDAR_MEMO_LIST_QUERY_INTERRUPTED: {
    code: "CALENDAR.MEMO.LIST_QUERY_INTERRUPTED",
    status: 500,
    message: "Could not retrieve memos",
  },
  CALENDAR_MEMO_NOT_FOUND: {
    code: "CALENDAR.MEMO.NOT_FOUND",
    status: 404,
    message: "Memo not found",
  },
  CALENDAR_MEMO_STORE_DELETE_INTERRUPTED: {
    code: "CALENDAR.MEMO.STORE_DELETE_INTERRUPTED",
    status: 500,
    message: "Could not delete memo",
  },
  CALENDAR_MEMO_STORE_READ_INTERRUPTED: {
    code: "CALENDAR.MEMO.STORE_READ_INTERRUPTED",
    status: 500,
    message: "Could not find memo",
  },
  CALENDAR_MEMO_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.MEMO.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not save memo",
  },
  CALENDAR_SMART_CREATE_TEXT_UNPARSEABLE: {
    code: "CALENDAR.SMART_CREATE.TEXT_UNPARSEABLE",
    status: 422,
    message: "Could not parse event from text",
  },
  CALENDAR_SUBSCRIPTION_COUNTRY_INVALID: {
    code: "CALENDAR.SUBSCRIPTION.COUNTRY_INVALID",
    status: 400,
    message: "Country code is invalid or not supported",
  },
  CALENDAR_SUBSCRIPTION_MEMBERSHIP_CHECK_INTERRUPTED: {
    code: "CALENDAR.SUBSCRIPTION.MEMBERSHIP_CHECK_INTERRUPTED",
    status: 500,
    message: "Could not verify membership",
  },
  CALENDAR_SUBSCRIPTION_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.SUBSCRIPTION.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not create calendar subscription",
  },
  CALENDAR_TASK_SYNC_STORE_WRITE_INTERRUPTED: {
    code: "CALENDAR.TASK_SYNC.STORE_WRITE_INTERRUPTED",
    status: 500,
    message: "Could not create event from task",
  },
  CALENDAR_TASK_SYNC_TASK_ID_MALFORMED: {
    code: "CALENDAR.TASK_SYNC.TASK_ID_MALFORMED",
    status: 400,
    message: "Invalid taskId format",
  },
  CALENDAR_TASK_SYNC_TASK_LOOKUP_INTERRUPTED: {
    code: "CALENDAR.TASK_SYNC.TASK_LOOKUP_INTERRUPTED",
    status: 500,
    message: "Could not look up task",
  },
  CALENDAR_TASK_SYNC_TASK_NOT_FOUND: {
    code: "CALENDAR.TASK_SYNC.TASK_NOT_FOUND",
    status: 404,
    message: "Task not found",
  },
  CALENDAR_TASK_SYNC_TIMEZONE_UNRECOGNIZED: {
    code: "CALENDAR.TASK_SYNC.TIMEZONE_UNRECOGNIZED",
    status: 400,
    message: "Unrecognized timezone",
  },
  CALENDAR_TASK_SYNC_VIEWER_ROLE_INSUFFICIENT: {
    code: "CALENDAR.TASK_SYNC.VIEWER_ROLE_INSUFFICIENT",
    status: 403,
    message: "Viewers cannot create events",
  },
  CALENDAR_USER_PROFILE_LOOKUP_INTERRUPTED: {
    code: "CALENDAR.USER_PROFILE.LOOKUP_INTERRUPTED",
    status: 500,
    message: "Could not retrieve user profile",
  },
  CALENDAR_USER_PROFILE_USER_LOOKUP_INTERRUPTED: {
    code: "CALENDAR.USER_PROFILE.USER_LOOKUP_INTERRUPTED",
    status: 500,
    message: "Could not look up user",
  },
  CALENDAR_WORKSPACE_NOT_FOUND: {
    code: "CALENDAR.WORKSPACE.NOT_FOUND",
    status: 404,
    message: "Workspace not found",
  },
} as const;

export type CalendarErrorCode = (typeof CalendarErrors)[keyof typeof CalendarErrors]["code"];
