// Code generated by gen-errors. DO NOT EDIT.

export const ConstraintErrors = {
  CONSTRAINT_EVAL_BAD_DATE: {
    code: "CONSTRAINT.EVAL.BAD_DATE",
    status: 422,
    message: "Constraint date argument is not a valid YYYY-MM-DD",
  },
  CONSTRAINT_PARSE_EMPTY_TERMS: {
    code: "CONSTRAINT.PARSE.EMPTY_TERMS",
    status: 422,
    message: "Constraint and/or requires at least one term",
  },
  CONSTRAINT_PARSE_INVALID_JSON: {
    code: "CONSTRAINT.PARSE.INVALID_JSON",
    status: 422,
    message: "Constraint expression is not valid JSON",
  },
  CONSTRAINT_PARSE_MISSING_ARG: {
    code: "CONSTRAINT.PARSE.MISSING_ARG",
    status: 422,
    message: "Constraint expression is missing a required argument",
  },
  CONSTRAINT_PARSE_UNKNOWN_OP: {
    code: "CONSTRAINT.PARSE.UNKNOWN_OP",
    status: 422,
    message: "Constraint expression uses an unknown operator",
  },
} as const;

export type ConstraintErrorCode = (typeof ConstraintErrors)[keyof typeof ConstraintErrors]["code"];
