// Code generated by gen-errors. DO NOT EDIT.

export const ExportErrors = {
  EXPORT_TASK_FORMAT_UNSUPPORTED: {
    code: "EXPORT.TASK.FORMAT_UNSUPPORTED",
    status: 400,
    message: "Unsupported export format",
  },
  EXPORT_TASK_GENERATION_FAILED: {
    code: "EXPORT.TASK.GENERATION_FAILED",
    status: 500,
    message: "Export file generation failed",
  },
  EXPORT_TASK_LENS_NOT_FOUND: {
    code: "EXPORT.TASK.LENS_NOT_FOUND",
    status: 404,
    message: "Lens referenced for export not found",
  },
  EXPORT_TASK_TOO_MANY_ROWS: {
    code: "EXPORT.TASK.TOO_MANY_ROWS",
    status: 422,
    message: "Export exceeds maximum row limit",
  },
} as const;

export type ExportErrorCode = (typeof ExportErrors)[keyof typeof ExportErrors]["code"];
