// Code generated by gen-errors. DO NOT EDIT.

export const ExportErrors = {
  EXPORT_TASK_DATASET_QUERY_FAILED: {
    code: "EXPORT.TASK.DATASET_QUERY_FAILED",
    status: 500,
    message: "Could not load tasks for export",
  },
  EXPORT_TASK_LENS_NOT_FOUND: {
    code: "EXPORT.TASK.LENS_NOT_FOUND",
    status: 404,
    message: "Lens referenced for export not found",
  },
} as const;

export type ExportErrorCode = (typeof ExportErrors)[keyof typeof ExportErrors]["code"];
