// Code generated by gen-errors. DO NOT EDIT.

export const InternalErrors = {
  INTERNAL_DB_UNAVAILABLE: {
    code: "INTERNAL.DB.UNAVAILABLE",
    status: 503,
    message: "Database is temporarily unavailable",
  },
  INTERNAL_STORAGE_NOT_CONFIGURED: {
    code: "INTERNAL.STORAGE.NOT_CONFIGURED",
    status: 503,
    message: "Storage not configured",
  },
  INTERNAL_UNEXPECTED: {
    code: "INTERNAL.UNEXPECTED",
    status: 500,
    message: "An unexpected internal error occurred",
  },
} as const;

export type InternalErrorCode = (typeof InternalErrors)[keyof typeof InternalErrors]["code"];
