// Code generated by gen-errors. DO NOT EDIT.

export const IntegrationsErrors = {
  INTEGRATION_CONNECTION_NOT_FOUND: {
    code: "INTEGRATION.CONNECTION.NOT_FOUND",
    status: 404,
    message: "Integration connection not found",
  },
  INTEGRATION_OAUTH_ACCOUNT_FETCH_FAILED: {
    code: "INTEGRATION.OAUTH.ACCOUNT_FETCH_FAILED",
    status: 502,
    message: "Could not fetch the provider account profile",
  },
  INTEGRATION_OAUTH_EXCHANGE_FAILED: {
    code: "INTEGRATION.OAUTH.EXCHANGE_FAILED",
    status: 502,
    message: "Could not exchange the OAuth code for an access token",
  },
  INTEGRATION_OAUTH_PROVIDER_NOT_CONFIGURED: {
    code: "INTEGRATION.OAUTH.PROVIDER_NOT_CONFIGURED",
    status: 503,
    message: "Integration provider is not configured on this server",
  },
  INTEGRATION_OAUTH_PROVIDER_UNSUPPORTED: {
    code: "INTEGRATION.OAUTH.PROVIDER_UNSUPPORTED",
    status: 400,
    message: "Unknown integration provider",
  },
  INTEGRATION_OAUTH_STATE_INVALID: {
    code: "INTEGRATION.OAUTH.STATE_INVALID",
    status: 400,
    message: "OAuth state token is missing, unknown, or expired",
  },
} as const;

export type IntegrationsErrorCode = (typeof IntegrationsErrors)[keyof typeof IntegrationsErrors]["code"];
