// Code generated by gen-errors. DO NOT EDIT.

export const PageErrors = {
  PAGE_GENERATION_UPSTREAM_UNAVAILABLE: {
    code: "PAGE.GENERATION.UPSTREAM_UNAVAILABLE",
    status: 502,
    message: "AI page generation failed",
  },
  PAGE_PAGE_CIRCULAR_PARENT: {
    code: "PAGE.PAGE.CIRCULAR_PARENT",
    status: 400,
    message: "Cannot set parent to self or descendant",
  },
  PAGE_PAGE_MAX_DEPTH: {
    code: "PAGE.PAGE.MAX_DEPTH",
    status: 400,
    message: "Maximum nesting depth exceeded",
  },
  PAGE_PAGE_NOT_FOUND: {
    code: "PAGE.PAGE.NOT_FOUND",
    status: 404,
    message: "Page not found",
  },
  PAGE_PAGE_TITLE_TAKEN: {
    code: "PAGE.PAGE.TITLE_TAKEN",
    status: 409,
    message: "A page with this title already exists under the same parent",
  },
} as const;

export type PageErrorCode = (typeof PageErrors)[keyof typeof PageErrors]["code"];
