// Code generated by gen-errors. DO NOT EDIT.

export const RateErrors = {
  RATE_LIMIT_EXCEEDED: {
    code: "RATE.LIMIT.EXCEEDED",
    status: 429,
    message: "Request rate limit exceeded",
  },
} as const;

export type RateErrorCode = (typeof RateErrors)[keyof typeof RateErrors]["code"];
