// Code generated by gen-errors. DO NOT EDIT.

export const RelationErrors = {
  RELATION_SUGGESTION_ALREADY_RESOLVED: {
    code: "RELATION.SUGGESTION.ALREADY_RESOLVED",
    status: 409,
    message: "Relation suggestion has already been resolved",
  },
  RELATION_SUGGESTION_NOT_FOUND: {
    code: "RELATION.SUGGESTION.NOT_FOUND",
    status: 404,
    message: "Relation suggestion not found",
  },
} as const;

export type RelationErrorCode = (typeof RelationErrors)[keyof typeof RelationErrors]["code"];
