// Code generated by gen-errors. DO NOT EDIT.

export const ShareErrors = {
  SHARE_SHARE_DELETE_FORBIDDEN: {
    code: "SHARE.SHARE.DELETE_FORBIDDEN",
    status: 403,
    message: "Only workspace admins or owners can delete a share",
  },
  SHARE_SHARE_EXPIRED: {
    code: "SHARE.SHARE.EXPIRED",
    status: 410,
    message: "Share page has expired",
  },
  SHARE_SHARE_NOT_FOUND: {
    code: "SHARE.SHARE.NOT_FOUND",
    status: 404,
    message: "Share page not found",
  },
  SHARE_SHARE_TOKEN_INVALID: {
    code: "SHARE.SHARE.TOKEN_INVALID",
    status: 404,
    message: "Share token is invalid",
  },
  SHARE_SHARE_EVENT_EVENT_NOT_VISIBLE: {
    code: "SHARE.SHARE_EVENT.EVENT_NOT_VISIBLE",
    status: 422,
    message: "Event cannot be published",
  },
} as const;

export type ShareErrorCode = (typeof ShareErrors)[keyof typeof ShareErrors]["code"];
