// Code generated by gen-errors. DO NOT EDIT.

export const ShareErrors = {
  SHARE_SHARE_DELETE_FORBIDDEN: {
    code: "SHARE.SHARE.DELETE_FORBIDDEN",
    status: 403,
    message: "Only workspace admins or owners can delete a share",
  },
  SHARE_SHARE_EXPIRED: {
    code: "SHARE.SHARE.EXPIRED",
    status: 410,
    message: "Share page has expired",
  },
  SHARE_SHARE_EXPIRES_AT_NOT_IN_FUTURE: {
    code: "SHARE.SHARE.EXPIRES_AT_NOT_IN_FUTURE",
    status: 422,
    message: "Share expiry must be in the future",
  },
  SHARE_SHARE_EXPIRES_AT_OUT_OF_RANGE: {
    code: "SHARE.SHARE.EXPIRES_AT_OUT_OF_RANGE",
    status: 422,
    message: "Share expiry is outside the range this field can hold",
  },
  SHARE_SHARE_NOT_FOUND: {
    code: "SHARE.SHARE.NOT_FOUND",
    status: 404,
    message: "Share page not found",
  },
  SHARE_SHARE_TOKEN_INVALID: {
    code: "SHARE.SHARE.TOKEN_INVALID",
    status: 404,
    message: "Share token is invalid",
  },
  SHARE_SHARE_EVENT_NOT_FOUND: {
    code: "SHARE.SHARE_EVENT.NOT_FOUND",
    status: 404,
    message: "Event is not on this share",
  },
  SHARE_SHARE_EVENT_REORDER_INVALID: {
    code: "SHARE.SHARE_EVENT.REORDER_INVALID",
    status: 400,
    message: "Reorder input must be a permutation of the share's current events",
  },
} as const;

export type ShareErrorCode = (typeof ShareErrors)[keyof typeof ShareErrors]["code"];
