// Code generated by gen-errors. DO NOT EDIT.

export const TimeboxErrors = {
  TIMEBOX_TASK_ALREADY_ADDED: {
    code: "TIMEBOX.TASK.ALREADY_ADDED",
    status: 409,
    message: "Task is already in this timebox",
  },
  TIMEBOX_TASK_NOT_IN_TIMEBOX: {
    code: "TIMEBOX.TASK.NOT_IN_TIMEBOX",
    status: 404,
    message: "Task not found in this timebox",
  },
  TIMEBOX_TIMEBOX_ALREADY_COMPLETED: {
    code: "TIMEBOX.TIMEBOX.ALREADY_COMPLETED",
    status: 409,
    message: "Cannot modify a completed timebox",
  },
  TIMEBOX_TIMEBOX_INVALID_DATES: {
    code: "TIMEBOX.TIMEBOX.INVALID_DATES",
    status: 422,
    message: "Timebox end date must be after start date",
  },
  TIMEBOX_TIMEBOX_NAME_TAKEN: {
    code: "TIMEBOX.TIMEBOX.NAME_TAKEN",
    status: 409,
    message: "A timebox with this name already exists in the workspace",
  },
  TIMEBOX_TIMEBOX_NOT_FOUND: {
    code: "TIMEBOX.TIMEBOX.NOT_FOUND",
    status: 404,
    message: "Timebox not found",
  },
} as const;

export type TimeboxErrorCode = (typeof TimeboxErrors)[keyof typeof TimeboxErrors]["code"];
