// Code generated by gen-errors. DO NOT EDIT.

export const ValidationErrors = {
  VALIDATION_BODY_DATE_FORMAT_INVALID: {
    code: "VALIDATION.BODY.DATE_FORMAT_INVALID",
    status: 400,
    message: "Date must be in YYYY-MM-DD format",
  },
  VALIDATION_BODY_DUE_BEFORE_START: {
    code: "VALIDATION.BODY.DUE_BEFORE_START",
    status: 400,
    message: "Due date must be on or after start date.",
  },
  VALIDATION_BODY_FIELD_INVALID: {
    code: "VALIDATION.BODY.FIELD_INVALID",
    status: 422,
    message: "A field in the request body is invalid",
  },
  VALIDATION_BODY_FIELD_MISSING: {
    code: "VALIDATION.BODY.FIELD_MISSING",
    status: 422,
    message: "A required field is missing in the request body",
  },
  VALIDATION_BODY_UNPARSEABLE: {
    code: "VALIDATION.BODY.UNPARSEABLE",
    status: 400,
    message: "Request body could not be parsed",
  },
  VALIDATION_CHECKSUM_FORMAT_INVALID: {
    code: "VALIDATION.CHECKSUM.FORMAT_INVALID",
    status: 400,
    message: "Invalid checksum format. Expected SHA-256 as 64 hex characters.",
  },
  VALIDATION_FILE_TOO_LARGE: {
    code: "VALIDATION.FILE.TOO_LARGE",
    status: 413,
    message: "File exceeds the maximum allowed size",
  },
  VALIDATION_FILE_TYPE_NOT_ALLOWED: {
    code: "VALIDATION.FILE.TYPE_NOT_ALLOWED",
    status: 415,
    message: "File type is not allowed",
  },
  VALIDATION_PATH_PARAM_INVALID: {
    code: "VALIDATION.PATH.PARAM_INVALID",
    status: 400,
    message: "A path parameter is invalid",
  },
  VALIDATION_QUERY_FIELD_INVALID: {
    code: "VALIDATION.QUERY.FIELD_INVALID",
    status: 422,
    message: "A query parameter is invalid",
  },
  VALIDATION_QUERY_UNKNOWN_FIELD: {
    code: "VALIDATION.QUERY.UNKNOWN_FIELD",
    status: 422,
    message: "Unknown query parameter",
  },
} as const;

export type ValidationErrorCode = (typeof ValidationErrors)[keyof typeof ValidationErrors]["code"];
