// Code generated by gen-errors. DO NOT EDIT.

export const WorkspaceErrors = {
  WORKSPACE_DELETE_CONFIRM_REQUIRED: {
    code: "WORKSPACE.DELETE.CONFIRM_REQUIRED",
    status: 400,
    message: "Confirmation required to delete this workspace. Resend with confirm=true.",
  },
} as const;

export type WorkspaceErrorCode = (typeof WorkspaceErrors)[keyof typeof WorkspaceErrors]["code"];
