// Code generated by gen-errors. DO NOT EDIT.

export const WsErrors = {
  WS_DESCRIPTION_VERSION_NOT_FOUND: {
    code: "WS.DESCRIPTION_VERSION.NOT_FOUND",
    status: 404,
    message: "Description version not found",
  },
  WS_FAVORITE_ALREADY_EXISTS: {
    code: "WS.FAVORITE.ALREADY_EXISTS",
    status: 409,
    message: "This item is already in your favorites",
  },
  WS_FAVORITE_NOT_FOUND: {
    code: "WS.FAVORITE.NOT_FOUND",
    status: 404,
    message: "Favorite not found",
  },
  WS_IMPORT_ALREADY_RUNNING: {
    code: "WS.IMPORT.ALREADY_RUNNING",
    status: 409,
    message: "An import job is already running for this project",
  },
  WS_IMPORT_CANNOT_CANCEL: {
    code: "WS.IMPORT.CANNOT_CANCEL",
    status: 409,
    message: "Only pending or running import jobs can be cancelled",
  },
  WS_IMPORT_NOT_FOUND: {
    code: "WS.IMPORT.NOT_FOUND",
    status: 404,
    message: "Import job not found",
  },
  WS_INTAKE_ALREADY_CONVERTED: {
    code: "WS.INTAKE.ALREADY_CONVERTED",
    status: 409,
    message: "This intake item has already been converted to a task",
  },
  WS_INTAKE_ALREADY_TRIAGED: {
    code: "WS.INTAKE.ALREADY_TRIAGED",
    status: 409,
    message: "This intake item has already been triaged",
  },
  WS_INTAKE_NOT_FOUND: {
    code: "WS.INTAKE.NOT_FOUND",
    status: 404,
    message: "Intake item not found",
  },
  WS_LABEL_NAME_ALREADY_TAKEN: {
    code: "WS.LABEL.NAME_ALREADY_TAKEN",
    status: 409,
    message: "A label with this name already exists",
  },
  WS_LABEL_NOT_FOUND: {
    code: "WS.LABEL.NOT_FOUND",
    status: 404,
    message: "Label not found",
  },
  WS_LENS_ALREADY_PRIVATE: {
    code: "WS.LENS.ALREADY_PRIVATE",
    status: 409,
    message: "This saved view is already private",
  },
  WS_LENS_ALREADY_PUBLIC: {
    code: "WS.LENS.ALREADY_PUBLIC",
    status: 409,
    message: "This saved view is already published",
  },
  WS_LENS_NAME_ALREADY_TAKEN: {
    code: "WS.LENS.NAME_ALREADY_TAKEN",
    status: 409,
    message: "A saved view with this name already exists",
  },
  WS_LENS_NOT_FOUND: {
    code: "WS.LENS.NOT_FOUND",
    status: 404,
    message: "Saved view not found",
  },
  WS_LENS_PUBLIC_TOKEN_INVALID: {
    code: "WS.LENS.PUBLIC_TOKEN_INVALID",
    status: 404,
    message: "Public share link not found or expired",
  },
  WS_MEMBER_NOT_FOUND: {
    code: "WS.MEMBER.NOT_FOUND",
    status: 404,
    message: "Workspace member not found",
  },
  WS_MEMBER_ROLE_DENIED: {
    code: "WS.MEMBER.ROLE_DENIED",
    status: 403,
    message: "Your role does not permit this action",
  },
  WS_MENTION_NOT_FOUND: {
    code: "WS.MENTION.NOT_FOUND",
    status: 404,
    message: "Mention not found",
  },
  WS_NOTIFICATION_NOT_FOUND: {
    code: "WS.NOTIFICATION.NOT_FOUND",
    status: 404,
    message: "Notification not found",
  },
  WS_NOTIFICATION_PREFERENCE_NOT_FOUND: {
    code: "WS.NOTIFICATION_PREFERENCE.NOT_FOUND",
    status: 404,
    message: "Notification preference not found",
  },
  WS_PROJECT_ACCESS_DENIED: {
    code: "WS.PROJECT.ACCESS_DENIED",
    status: 403,
    message: "You do not have access to this project",
  },
  WS_PROJECT_FEATURE_DISABLED: {
    code: "WS.PROJECT.FEATURE_DISABLED",
    status: 403,
    message: "This feature is disabled for the project",
  },
  WS_PROJECT_IDENTIFIER_ALREADY_TAKEN: {
    code: "WS.PROJECT.IDENTIFIER_ALREADY_TAKEN",
    status: 409,
    message: "Project identifier is already taken",
  },
  WS_PROJECT_NOT_FOUND: {
    code: "WS.PROJECT.NOT_FOUND",
    status: 404,
    message: "Project not found",
  },
  WS_PROJECT_SLUG_ALREADY_TAKEN: {
    code: "WS.PROJECT.SLUG_ALREADY_TAKEN",
    status: 409,
    message: "Project slug is already taken",
  },
  WS_REACTION_ALREADY_EXISTS: {
    code: "WS.REACTION.ALREADY_EXISTS",
    status: 409,
    message: "You already reacted with this emoji",
  },
  WS_REACTION_NOT_FOUND: {
    code: "WS.REACTION.NOT_FOUND",
    status: 404,
    message: "Reaction not found",
  },
  WS_SIGNAL_KIND_UNKNOWN: {
    code: "WS.SIGNAL.KIND_UNKNOWN",
    status: 422,
    message: "Unknown signal kind",
  },
  WS_SIGNAL_SUBJECT_MISMATCH: {
    code: "WS.SIGNAL.SUBJECT_MISMATCH",
    status: 422,
    message: "Signal subject does not match the linked task",
  },
  WS_SIGNAL_SUBJECT_NOT_FOUND: {
    code: "WS.SIGNAL.SUBJECT_NOT_FOUND",
    status: 404,
    message: "Signal subject does not exist in this workspace",
  },
  WS_TASK_ACCESS_DENIED: {
    code: "WS.TASK.ACCESS_DENIED",
    status: 403,
    message: "You do not have access to this task",
  },
  WS_TASK_ACTOR_ROLE_INVALID: {
    code: "WS.TASK.ACTOR_ROLE_INVALID",
    status: 422,
    message: "Task actor role must be one of: assignee, reviewer, watcher, approver",
    i18nKey: "workspace.errors.task_actor_role_invalid",
  },
  WS_TASK_ALREADY_ARCHIVED: {
    code: "WS.TASK.ALREADY_ARCHIVED",
    status: 409,
    message: "Task is already archived",
  },
  WS_TASK_NOT_ARCHIVED: {
    code: "WS.TASK.NOT_ARCHIVED",
    status: 409,
    message: "Task is not archived",
  },
  WS_TASK_NOT_FOUND: {
    code: "WS.TASK.NOT_FOUND",
    status: 404,
    message: "Task not found",
  },
  WS_TASK_STATE_TRANSITION_BLOCKED_BY_CONSTRAINT: {
    code: "WS.TASK.STATE_TRANSITION_BLOCKED_BY_CONSTRAINT",
    status: 422,
    message: "Task cannot transition to the requested state",
  },
  WS_TASK_TITLE_TOO_LONG: {
    code: "WS.TASK.TITLE_TOO_LONG",
    status: 422,
    message: "Task title is too long",
  },
  WS_TASK_TRANSITION_REJECTED: {
    code: "WS.TASK.TRANSITION_REJECTED",
    status: 422,
    message: "Task transition not allowed in current state",
  },
  WS_TASK_TRANSITION_UNKNOWN: {
    code: "WS.TASK.TRANSITION_UNKNOWN",
    status: 400,
    message: "Unknown task transition",
  },
  WS_TASK_UPDATE_CONFLICT: {
    code: "WS.TASK.UPDATE_CONFLICT",
    status: 409,
    message: "Task was modified by someone else",
  },
  WS_TASK_AGENT_ALREADY_ASSIGNED: {
    code: "WS.TASK_AGENT.ALREADY_ASSIGNED",
    status: 409,
    message: "Agent is already the assignee for this task",
  },
  WS_TASK_AGENT_COST_CAP_EXCEEDED: {
    code: "WS.TASK_AGENT.COST_CAP_EXCEEDED",
    status: 422,
    message: "Agent monthly cost cap has been reached",
  },
  WS_TASK_AGENT_HANDOFF_LOOP_DETECTED: {
    code: "WS.TASK_AGENT.HANDOFF_LOOP_DETECTED",
    status: 422,
    message: "Handoff bounced between agent and user too many times",
  },
  WS_TASK_AGENT_NOT_ASSIGNED: {
    code: "WS.TASK_AGENT.NOT_ASSIGNED",
    status: 422,
    message: "Task has no agent assignee",
  },
  WS_VIEW_PREFERENCE_NOT_FOUND: {
    code: "WS.VIEW_PREFERENCE.NOT_FOUND",
    status: 404,
    message: "View preference not found",
  },
  WS_WORKSPACE_ACCESS_DENIED: {
    code: "WS.WORKSPACE.ACCESS_DENIED",
    status: 403,
    message: "You do not have access to this workspace",
  },
  WS_WORKSPACE_NOT_FOUND: {
    code: "WS.WORKSPACE.NOT_FOUND",
    status: 404,
    message: "Workspace not found",
  },
  WS_WORKSPACE_SLUG_ALREADY_TAKEN: {
    code: "WS.WORKSPACE.SLUG_ALREADY_TAKEN",
    status: 409,
    message: "Workspace slug is already taken",
  },
  WS_WORKSPACE_INVITE_EXHAUSTED: {
    code: "WS.WORKSPACE_INVITE.EXHAUSTED",
    status: 410,
    message: "Invite has reached its use limit.",
  },
  WS_WORKSPACE_INVITE_EXPIRED: {
    code: "WS.WORKSPACE_INVITE.EXPIRED",
    status: 410,
    message: "Invite has expired.",
  },
} as const;

export type WsErrorCode = (typeof WsErrors)[keyof typeof WsErrors]["code"];
