// Package signaljudge — production TaskMutator backed by the shared
// MySQL pool.
//
// [SQLTaskMutator] is the production wiring for [TaskMutator]; it
// replaces the Phase 3 [LogOnlyTaskMutator] stub for the
// `generate_retro` branch (Phase 6 / L2 of
// `docs/plan/release-8-signals-and-judge-loop.md`). The other branches
// (`complete_task`, `add_comment`) remain no-op-with-warn — their
// production wiring lands in later phases when the corresponding task
// handlers are exposed as reusable functions.
//
// Design notes:
//
//   - The retro path performs two writes (a tasks INSERT and a
//     task_dependencies INSERT) in one transaction so the source
//     task and the new retro draft stay consistent: either both rows
//     land or neither does. The Applier observes the failure by
//     receiving an error back and emits a [SignalRejected] event
//     instead of [TaskRetroDrafted].
//
//   - `derived_state` has no `draft` value in the tasks ENUM
//     (`'open','waiting','review','done','cancelled'`). The "draft"
//     semantics live in two places: (a) the `task_dependencies.kind =
//     'retro_of'` row that backlinks the new task to the source, and
//     (b) the TaskRetroDrafted event payload's `draft` boolean. The
//     web client filters the retro queue on the dependency edge; the
//     task row itself starts at `derived_state='open'` like any other
//     task created via [tasks.Create].
//
//   - The new retro task inherits its workspace and project from the
//     source task. Assignee inheritance is best-effort: when the
//     source task has at least one enabled human `assignee` actor, the
//     first one (by task_actors.id) is also attached to the retro
//     task. When the source task has only agent actors or no actors,
//     the retro task is created without an assignee — the human
//     reviewer picks it up via the queue UI.
//
//   - `created_by_user_id` and `updated_by_user_id` are left NULL.
//     The Applier owns the audit attribution through
//     `events.actor_agent_id = judge_agent_id` on the emitted
//     [TaskRetroDrafted] row; duplicating that on `tasks.created_by_*`
//     would conflate "created by user X" with "created on behalf of
//     judge agent Y" and break the existing audit projection.
package signaljudge

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/nodate-flow/nodate-flow/apps/flow-api/internal/db/dbretry"
	"github.com/nodate-flow/nodate-flow/apps/flow-api/internal/db/generated"
	"github.com/nodate-flow/nodate-flow/apps/flow-api/internal/db/types"
)

// retroTitlePrefix is the canonical prefix every retro-drafted task
// title carries. Kept as a package-level constant so the prompt and
// the queue UI can agree on a single token to match against.
const retroTitlePrefix = "Retro: "

// retroTitleMaxLen mirrors the tasks.title VARCHAR(255) limit. When
// the source task's title plus the prefix would exceed it, the
// concatenated string is truncated on a rune boundary with a
// trailing ellipsis so the title still parses as utf-8.
const retroTitleMaxLen = 255

// retroDescriptionTemplate is the autogenerated body for a retro
// draft. The first `%s` is replaced with the source task title (so
// the operator opening the queue immediately understands what was
// reflected on) and the second with the wall-clock date in
// `YYYY-MM-DD` form. Intentionally bilingual-neutral: the timeline
// UI may render its own i18n header above this; the body itself is
// kept stable so audit projections can fingerprint it.
const retroDescriptionTemplate = "Retrospective draft created by the signal judge in response to %q on %s. Review and edit before publishing."

// SQLTaskMutator implements [TaskMutator] against the production
// MySQL pool. Wired in cmd/api/main.go in place of
// [LogOnlyTaskMutator] once the corresponding action branch has a
// reviewed write path (Phase 6 / L2 lands the `generate_retro`
// branch).
//
// Both DB and Queries are required: the retro path begins a
// transaction on DB and binds the sqlc-generated queries to it via
// Queries.WithTx, so the tasks INSERT and the task_dependencies
// INSERT either both commit or both roll back. NowFn is a wall-clock
// hook so tests can pin the description text; nil falls back to
// time.Now.
type SQLTaskMutator struct {
	// DB is the shared *sql.DB used to begin transactions. Required.
	DB *sql.DB
	// Queries is the sqlc-generated query bundle bound to DB.
	// Required.
	Queries *generated.Queries
	// Logger emits warn-level diagnostics when a no-op branch is
	// invoked (complete_task / add_comment have not been wired yet).
	// nil falls back to slog.Default().
	Logger *slog.Logger
	// NowFn is the wall-clock used to stamp the retro description's
	// date placeholder. nil falls back to time.Now.
	NowFn func() time.Time
}

// CompleteTask is the stub implementation. Phase 6 / L2 only lands
// the retro branch; the complete_task branch is wired in a follow-up
// phase. Returns nil so the Applier's existing TaskAutoCompleted
// emission contract is preserved end-to-end.
func (m *SQLTaskMutator) CompleteTask(ctx context.Context, workspaceID uint32, taskInternalID int64, agentID uint32) error {
	logger := m.logger()
	logger.WarnContext(ctx, "signaljudge: SQLTaskMutator.CompleteTask is a no-op stub (Phase 6 / L2 ships retro only)",
		slog.Uint64("workspace_internal", uint64(workspaceID)),
		slog.Int64("task_internal", taskInternalID),
		slog.Uint64("agent_internal", uint64(agentID)),
	)
	return nil
}

// AddComment is the stub implementation. Phase 6 / L2 only lands
// the retro branch; the add_comment branch is wired in a follow-up
// phase. Returns nil so the Applier's existing event-emission
// contract is preserved end-to-end.
func (m *SQLTaskMutator) AddComment(ctx context.Context, workspaceID uint32, taskInternalID int64, agentID uint32, body string) error {
	logger := m.logger()
	logger.WarnContext(ctx, "signaljudge: SQLTaskMutator.AddComment is a no-op stub (Phase 6 / L2 ships retro only)",
		slog.Uint64("workspace_internal", uint64(workspaceID)),
		slog.Int64("task_internal", taskInternalID),
		slog.Uint64("agent_internal", uint64(agentID)),
		slog.Int("body_len", len(body)),
	)
	return nil
}

// DraftRetroTask is the production implementation of the
// generate_retro branch.
//
// Flow:
//  1. SELECT the source task's workspace, project_id, title, and
//     first enabled human assignee user_id (best-effort).
//  2. BEGIN TX.
//  3. AssignTaskNumber + CreateTask + (optional) AddActor +
//     AddDependency(kind='retro_of'). Every write goes through the
//     sqlc-generated queries bound to the open transaction so the
//     existing prepared-statement cache and instrumentation are
//     reused.
//  4. COMMIT. Returns the new task's internal id and public id so
//     the Applier can embed them in the TaskRetroDrafted event.
//
// On any sub-error the transaction rolls back and the function
// returns the wrapped error verbatim. The caller (Applier) treats
// that as a signal to emit SignalRejected with reason
// "retro_creation_failed" instead of TaskRetroDrafted, per the L2
// brief.
//
// `draft` is the autonomy hint from the verdict: true under
// AutonomyDraft, false under AutonomyAuto. Both branches create the
// task at `derived_state='open'`; the flag is only used to confirm
// the L2 invariant ("retro draft tasks are always created in a
// reviewable state, even under autonomy=auto"). It is also forwarded
// to the TaskRetroDrafted payload by the Applier.
func (m *SQLTaskMutator) DraftRetroTask(
	ctx context.Context,
	workspaceID uint32,
	sourceTaskInternalID int64,
	agentID uint32,
	title string,
	draft bool,
) (int64, string, error) {
	if m == nil || m.DB == nil || m.Queries == nil {
		return 0, "", errors.New("signaljudge: SQLTaskMutator missing DB or Queries")
	}
	if workspaceID == 0 {
		return 0, "", errors.New("signaljudge: DraftRetroTask: workspaceID is zero")
	}
	if sourceTaskInternalID <= 0 {
		return 0, "", errors.New("signaljudge: DraftRetroTask: sourceTaskInternalID is zero")
	}

	// Look up the source task's project + title + first assignee.
	// Raw SQL to avoid coupling the signaljudge package to a sqlc
	// query whose only consumer is this function (the package
	// already uses the same pattern for [SQLTaskResolver] and
	// [SQLSignalUpdater]).
	src, err := m.loadRetroSource(ctx, workspaceID, sourceTaskInternalID)
	if err != nil {
		return 0, "", fmt.Errorf("signaljudge: load retro source: %w", err)
	}

	// Build the new retro task's title. Prefer the caller's title
	// (the Applier passes [retroTitle] which already names the
	// signal); fall back to the source task's own title prefixed
	// with `retroTitlePrefix` when the caller passed nothing.
	newTitle := strings.TrimSpace(title)
	if newTitle == "" {
		newTitle = retroTitlePrefix + src.Title
	}
	newTitle = truncateTitleRunes(newTitle, retroTitleMaxLen)

	// Description text — see [retroDescriptionTemplate].
	now := m.now().UTC()
	description := fmt.Sprintf(retroDescriptionTemplate, src.Title, now.Format("2006-01-02"))

	newPub := types.New()
	var newTaskID int64

	// Single transaction for both inserts (and the optional actor
	// row). dbretry.InTx retries on transient deadlocks; the inner
	// fn is idempotent because no row references the auto-increment
	// id of a previous attempt — both pubIDs (tasks + dependency +
	// actor) are minted fresh per attempt.
	txErr := dbretry.InTx(ctx, m.DB, "signaljudge.SQLTaskMutator.DraftRetroTask", nil, func(ctx context.Context, tx *sql.Tx) error {
		qtx := m.Queries.WithTx(tx)

		// Allocate the next per-project task_number. CreateTask
		// requires this — without it the row would collide on the
		// uniq_tasks_project_id_task_number index.
		nextNum, err := qtx.AssignTaskNumber(ctx, generated.AssignTaskNumberParams{
			WorkspaceID: workspaceID,
			ProjectID:   src.ProjectID,
		})
		if err != nil {
			return fmt.Errorf("AssignTaskNumber: %w", err)
		}

		taskID, err := qtx.CreateTask(ctx, generated.CreateTaskParams{
			PublicID:        newPub,
			WorkspaceID:     workspaceID,
			ProjectID:       src.ProjectID,
			ParentTaskID:    sql.NullInt32{},
			CreatedByUserID: sql.NullInt32{}, // attribution lives on events.actor_agent_id
			UpdatedByUserID: sql.NullInt32{},
			TaskNumber:      uint32(nextNum), //#nosec G115 -- per-project sequence, fits uint32
			Title:           newTitle,
			Description:     sql.NullString{String: description, Valid: true},
			Priority:        0,
			DueOn:           sql.NullTime{},
			StartedOn:       sql.NullTime{},
			Visibility:      generated.TasksVisibilityPublic,
		})
		if err != nil {
			return fmt.Errorf("CreateTask: %w", err)
		}
		newTaskID = taskID

		// Best-effort assignee inheritance. When the source had a
		// human assignee, attach them to the retro draft so the
		// queue surfaces on their /me/tasks feed.
		if src.AssigneeUserID.Valid {
			actorPub := types.New()
			if _, aerr := qtx.AddActor(ctx, generated.AddActorParams{
				PublicID:    actorPub,
				WorkspaceID: workspaceID,
				TaskID:      uint32(taskID), //#nosec G115 -- LastInsertId for tasks.id (BIGINT UNSIGNED), fits uint32 within realistic deployments
				UserID:      src.AssigneeUserID,
				Role:        generated.TaskActorsRoleAssignee,
			}); aerr != nil {
				return fmt.Errorf("AddActor: %w", aerr)
			}
		}

		// retro_of edge. from = the new retro task, to = the
		// original task that prompted the retrospective. The schema
		// comment on [task_dependencies.kind] pins this orientation.
		depPub := types.New()
		if _, derr := qtx.AddDependency(ctx, generated.AddDependencyParams{
			PublicID:    depPub,
			WorkspaceID: workspaceID,
			FromTaskID:  uint32(taskID),               //#nosec G115 -- LastInsertId for tasks.id (BIGINT UNSIGNED), fits uint32 within realistic deployments
			ToTaskID:    uint32(sourceTaskInternalID), //#nosec G115 -- tasks.id (BIGINT UNSIGNED), fits uint32 within realistic deployments
			Kind:        generated.TaskDependenciesKindRetroOf,
		}); derr != nil {
			return fmt.Errorf("AddDependency(retro_of): %w", derr)
		}

		return nil
	})
	if txErr != nil {
		m.logger().WarnContext(ctx, "signaljudge: DraftRetroTask transaction rolled back",
			slog.Any("err", txErr),
			slog.Uint64("workspace_internal", uint64(workspaceID)),
			slog.Int64("source_task_internal", sourceTaskInternalID),
			slog.Uint64("agent_internal", uint64(agentID)),
			slog.Bool("draft", draft),
		)
		return 0, "", fmt.Errorf("signaljudge: draft retro task: %w", txErr)
	}

	return newTaskID, newPub.UUID().String(), nil
}

// retroSourceTask is the projection of the source task that
// [SQLTaskMutator.DraftRetroTask] needs. Defined as a private struct
// so a future column addition does not ripple into the public
// interface.
type retroSourceTask struct {
	ProjectID      uint32
	Title          string
	AssigneeUserID sql.NullInt32
}

// loadRetroSource performs the read-only lookup of the source task's
// (project_id, title, first enabled assignee user_id). Returns
// errors.Is(err, sql.ErrNoRows) when the source task does not exist
// in the workspace — the Applier resolved its internal id from a
// public_id so a missing row here is a TOCTOU between the resolver
// and the mutator; the caller surfaces it as
// "retro_creation_failed".
func (m *SQLTaskMutator) loadRetroSource(ctx context.Context, workspaceID uint32, sourceTaskInternalID int64) (retroSourceTask, error) {
	const q = `
SELECT
  t.project_id,
  t.title,
  (
    SELECT ta.user_id
    FROM task_actors ta
    WHERE ta.task_id = t.id
      AND ta.enabled = TRUE
      AND ta.kind = 'user'
      AND ta.role = 'assignee'
    ORDER BY ta.id ASC
    LIMIT 1
  ) AS assignee_user_id
FROM tasks t
WHERE t.workspace_id = ?
  AND t.id = ?
  AND t.enabled = TRUE
LIMIT 1`
	var src retroSourceTask
	if err := m.DB.QueryRowContext(ctx, q, workspaceID, sourceTaskInternalID).Scan(
		&src.ProjectID,
		&src.Title,
		&src.AssigneeUserID,
	); err != nil {
		return retroSourceTask{}, err
	}
	return src, nil
}

// logger returns a non-nil *slog.Logger.
func (m *SQLTaskMutator) logger() *slog.Logger {
	if m.Logger != nil {
		return m.Logger
	}
	return slog.Default()
}

// now returns the wall-clock used to stamp the retro description.
func (m *SQLTaskMutator) now() time.Time {
	if m.NowFn != nil {
		return m.NowFn()
	}
	return time.Now()
}

// truncateTitleRunes returns s clipped to at most maxRunes runes,
// with a trailing "…" when truncation occurred. Operates on runes
// rather than bytes so multi-byte characters are not split.
//
// maxRunes < 1 returns the empty string. maxRunes >= len([]rune(s))
// returns s verbatim.
func truncateTitleRunes(s string, maxRunes int) string {
	if maxRunes < 1 {
		return ""
	}
	r := []rune(s)
	if len(r) <= maxRunes {
		return s
	}
	// Reserve one rune for the ellipsis.
	if maxRunes == 1 {
		return "…"
	}
	return string(r[:maxRunes-1]) + "…"
}
