// Package signaljudge — production TaskMutator backed by the shared
// MySQL pool.
//
// [SQLTaskMutator] is the production wiring for [TaskMutator]; it
// replaces the Phase 3 [LogOnlyTaskMutator] stub. All three branches
// are real writes:
//
//   - `complete_task` routes through [taskstate.ApplyTransitionTx], the
//     canonical in-transaction derived_state writer the REST
//     /tasks/{id}/transitions handler and the auto-action executor also
//     use, so the completion actually moves the task to 'done'.
//   - `add_comment` reuses the generated AddComment INSERT (the same one
//     the REST POST /tasks/{id}/comments handler issues), persisting a
//     real comments row attributed to a resolved workspace member.
//   - `generate_retro` materialises a new retro task plus its retro_of
//     dependency edge in one transaction.
//
// Design notes:
//
//   - The retro path performs two writes (a tasks INSERT and a
//     task_dependencies INSERT) in one transaction so the source
//     task and the new retro draft stay consistent: either both rows
//     land or neither does. The Applier observes the failure by
//     receiving an error back and emits a [SignalRejected] event
//     instead of [TaskRetroDrafted].
//
//   - `derived_state` has no `draft` value in the tasks ENUM
//     (`'open','waiting','review','done','cancelled'`). The "draft"
//     semantics live in two places: (a) the `task_dependencies.kind =
//     'retro_of'` row that backlinks the new task to the source, and
//     (b) the TaskRetroDrafted event payload's `draft` boolean. The
//     web client filters the retro queue on the dependency edge; the
//     task row itself starts at `derived_state='open'` like any other
//     task created via [tasks.Create].
//
//   - The new retro task inherits its workspace and project from the
//     source task. Assignee inheritance is best-effort: when the
//     source task has at least one enabled human `assignee` actor, the
//     first one (by task_actors.id) is also attached to the retro
//     task. When the source task has only agent actors or no actors,
//     the retro task is created without an assignee — the human
//     reviewer picks it up via the queue UI.
//
//   - `created_by_user_id` and `updated_by_user_id` are left NULL.
//     The Applier owns the audit attribution through
//     `events.actor_agent_id = judge_agent_id` on the emitted
//     [TaskRetroDrafted] row; duplicating that on `tasks.created_by_*`
//     would conflate "created by user X" with "created on behalf of
//     judge agent Y" and break the existing audit projection.
package signaljudge

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/libraz/nodate-flow/apps/flow-api/internal/db/dbretry"
	"github.com/libraz/nodate-flow/apps/flow-api/internal/db/generated"
	"github.com/libraz/nodate-flow/apps/flow-api/internal/db/types"
	apierrors "github.com/libraz/nodate-flow/apps/flow-api/internal/errors"
	"github.com/libraz/nodate-flow/apps/flow-api/internal/taskcreate"
	"github.com/libraz/nodate-flow/apps/flow-api/internal/taskstate"
)

// agentCommentPrefix marks a comment row authored on behalf of the
// signal judge. The comments table has no agent-author column
// (author_id is a NOT NULL FK to users.id), so an auto-comment is
// attributed to a real workspace member while this prefix keeps the
// row honest about its machine origin. The timeline UI may render its
// own badge; the prefix is the durable, query-able marker.
const agentCommentPrefix = "[signal judge] "

// retroTitlePrefix is the canonical prefix every retro-drafted task
// title carries. Kept as a package-level constant so the prompt and
// the queue UI can agree on a single token to match against.
const retroTitlePrefix = "Retro: "

// retroTitleMaxLen mirrors the tasks.title VARCHAR(255) limit. When
// the source task's title plus the prefix would exceed it, the
// concatenated string is truncated on a rune boundary with a
// trailing ellipsis so the title still parses as utf-8.
const retroTitleMaxLen = 255

// retroDescriptionTemplate is the autogenerated body for a retro
// draft. The first `%s` is replaced with the source task title (so
// the operator opening the queue immediately understands what was
// reflected on) and the second with the wall-clock date in
// `YYYY-MM-DD` form. Intentionally bilingual-neutral: the timeline
// UI may render its own i18n header above this; the body itself is
// kept stable so audit projections can fingerprint it.
const retroDescriptionTemplate = "Retrospective draft created by the signal judge in response to %q on %s. Review and edit before publishing."

// SQLTaskMutator implements [TaskMutator] against the production
// MySQL pool. Wired in cmd/api/main.go in place of
// [LogOnlyTaskMutator]; every action branch (complete_task,
// add_comment, generate_retro) performs a real write.
//
// Both DB and Queries are required: complete_task begins a transaction
// on DB and drives [taskstate.ApplyTransitionTx]; add_comment and the
// retro path bind the sqlc-generated queries via Queries.WithTx (the
// retro path commits the tasks INSERT and the task_dependencies INSERT
// atomically). NowFn is a wall-clock hook so tests can pin the
// description text; nil falls back to time.Now.
type SQLTaskMutator struct {
	// DB is the shared *sql.DB used to begin transactions. Required.
	DB *sql.DB
	// Queries is the sqlc-generated query bundle bound to DB.
	// Required.
	Queries *generated.Queries
	// Logger emits warn-level diagnostics on benign skips (an
	// idempotent re-completion, an unresolvable comment author, a
	// rolled-back retro transaction). nil falls back to slog.Default().
	Logger *slog.Logger
	// NowFn is the wall-clock used to stamp the retro description's
	// date placeholder. nil falls back to time.Now.
	NowFn func() time.Time
}

// CompleteTask drives the judged auto-complete through the canonical
// in-transaction state-transition path so the task's derived_state
// actually moves to 'done' — the same [taskstate.ApplyTransitionTx]
// the REST /tasks/{id}/transitions handler and the auto-action
// executor use. Routing through that single writer keeps the
// derived_state UPDATE, the FOR UPDATE row lock, and the canonical
// task.transition.complete event append atomic, and preserves the
// trg_tasks_derived_state_guard invariant (derived_state is writable
// only through that helper).
//
// Idempotency: when the task is already 'done' (a prior auto-complete
// already landed, or a human closed it first), the state machine has
// no 'complete' transition out of 'done' and ApplyTransitionTx returns
// WS.TASK.TRANSITION_REJECTED. That case is treated as success — the
// desired end state already holds, so the Applier proceeds to emit its
// TaskAutoCompleted audit event.
//
// Any other rejection (the task sits in a state from which 'complete'
// is genuinely illegal, e.g. 'waiting', or the row vanished) returns a
// non-nil error. The Applier surfaces that error and short-circuits
// before appending TaskAutoCompleted, so no completion event is ever
// emitted without the matching state change.
//
// The trusted workspaceID / taskInternalID references are used as-is:
// the workspace id scopes both the lock and the persisted UPDATE, and
// the internal id is the FOR UPDATE lock key. The PublicID the
// persisted UPDATE keys on is resolved from the same (workspace_id, id)
// row so the two never diverge.
func (m *SQLTaskMutator) CompleteTask(ctx context.Context, workspaceID uint32, taskInternalID int64, agentID uint32) error {
	if m == nil || m.DB == nil {
		return errors.New("signaljudge: SQLTaskMutator missing DB")
	}
	if workspaceID == 0 {
		return errors.New("signaljudge: CompleteTask: workspaceID is zero")
	}
	if taskInternalID <= 0 {
		return errors.New("signaljudge: CompleteTask: taskInternalID is zero")
	}

	pub, err := m.loadTaskPublicID(ctx, workspaceID, taskInternalID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("signaljudge: CompleteTask: source task not found: %w", err)
		}
		return fmt.Errorf("signaljudge: CompleteTask: load task public id: %w", err)
	}

	var rejected bool
	txErr := dbretry.InTx(ctx, m.DB, "signaljudge.SQLTaskMutator.CompleteTask", nil, func(ctx context.Context, tx *sql.Tx) error {
		_, spec, cause := taskstate.ApplyTransitionTx(ctx, tx, taskstate.ApplyParams{
			WorkspaceID: workspaceID,
			TaskID:      uint32(taskInternalID), //#nosec G115 -- tasks.id (INT UNSIGNED), fits uint32
			PublicID:    pub,
			Transition:  taskstate.TransitionComplete,
			ActorUserID: nil, // judged by an agent, not a real user
			Reason:      "auto-completed by signal judge",
			Via:         "signal_judge",
			ExtraPayload: map[string]any{
				"agentInternalId": agentID,
			},
		})
		if spec != nil {
			if spec == apierrors.WsTaskTransitionRejected && m.taskIsDone(ctx, tx, workspaceID, taskInternalID) {
				// Already done: idempotent success. The desired end
				// state holds; let the Applier emit its audit event.
				rejected = false
				return nil
			}
			// Genuine rejection (illegal source state / missing row).
			// Surface a sentinel error so the Applier skips the event.
			rejected = true
			if cause != nil {
				return fmt.Errorf("transition rejected (%s): %w", spec.Code, cause)
			}
			return fmt.Errorf("transition rejected (%s)", spec.Code)
		}
		return nil
	})
	if txErr != nil {
		if rejected {
			m.logger().WarnContext(ctx, "signaljudge: CompleteTask transition rejected by state machine",
				slog.Any("err", txErr),
				slog.Uint64("workspace_internal", uint64(workspaceID)),
				slog.Int64("task_internal", taskInternalID),
				slog.Uint64("agent_internal", uint64(agentID)),
			)
		}
		return fmt.Errorf("signaljudge: complete task: %w", txErr)
	}
	return nil
}

// loadTaskPublicID resolves the public_id of an enabled task addressed
// by its internal (workspace_id, id) pair. Returns sql.ErrNoRows when
// the row does not exist or is disabled — the caller treats that as a
// TOCTOU between the resolver and the mutator.
func (m *SQLTaskMutator) loadTaskPublicID(ctx context.Context, workspaceID uint32, taskInternalID int64) (types.PublicID, error) {
	const q = `SELECT public_id FROM tasks WHERE workspace_id = ? AND id = ? AND enabled = TRUE LIMIT 1`
	var pub types.PublicID
	if err := m.DB.QueryRowContext(ctx, q, workspaceID, taskInternalID).Scan(&pub); err != nil {
		return types.PublicID{}, err
	}
	return pub, nil
}

// taskIsDone reports whether the task's derived_state is already
// 'done', read inside the open transaction so the answer is consistent
// with the row [taskstate.ApplyTransitionTx] just locked. Used to tell
// an idempotent re-completion (already done) apart from a genuine
// illegal-state rejection. A read error is treated as "not done" so the
// caller surfaces the original rejection rather than masking it.
func (m *SQLTaskMutator) taskIsDone(ctx context.Context, tx *sql.Tx, workspaceID uint32, taskInternalID int64) bool {
	const q = `SELECT derived_state FROM tasks WHERE workspace_id = ? AND id = ? AND enabled = TRUE LIMIT 1`
	var state string
	if err := tx.QueryRowContext(ctx, q, workspaceID, taskInternalID).Scan(&state); err != nil {
		return false
	}
	return state == string(generated.TasksDerivedStateDone)
}

// AddComment persists a real comment row for the judged auto-comment,
// reusing the same generated.AddComment INSERT the REST
// POST /tasks/{id}/comments handler uses. The comments table's
// author_id is a NOT NULL FK to users.id with no agent-author column,
// so the row is attributed to a real workspace member — the task's
// first enabled human assignee, falling back to the workspace owner —
// and the body is prefixed with agentCommentPrefix so the row stays
// honest about its machine origin.
//
// The applier emits no follow-on event for the add_comment branch, so
// the "no event without a state change" invariant is not at stake here;
// this implementation eliminates the prior silent data-loss by making
// the comment actually land. When no human author can be resolved at
// all (no assignee and no owner — a degenerate workspace), the call
// logs and returns nil rather than inventing an author, again without
// emitting any event.
//
// The trusted workspaceID / taskInternalID references are used as-is to
// scope the author lookup and the INSERT.
func (m *SQLTaskMutator) AddComment(ctx context.Context, workspaceID uint32, taskInternalID int64, agentID uint32, body string) error {
	if m == nil || m.DB == nil || m.Queries == nil {
		return errors.New("signaljudge: SQLTaskMutator missing DB or Queries")
	}
	if workspaceID == 0 {
		return errors.New("signaljudge: AddComment: workspaceID is zero")
	}
	if taskInternalID <= 0 {
		return errors.New("signaljudge: AddComment: taskInternalID is zero")
	}

	trimmed := strings.TrimSpace(body)
	if trimmed == "" {
		// Nothing worth persisting; not an error, no event is emitted.
		return nil
	}

	authorID, err := m.resolveCommentAuthor(ctx, workspaceID, taskInternalID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			m.logger().WarnContext(ctx, "signaljudge: AddComment skipped — no resolvable human author",
				slog.Uint64("workspace_internal", uint64(workspaceID)),
				slog.Int64("task_internal", taskInternalID),
				slog.Uint64("agent_internal", uint64(agentID)),
			)
			return nil
		}
		return fmt.Errorf("signaljudge: AddComment: resolve author: %w", err)
	}

	if _, err := m.Queries.AddComment(ctx, generated.AddCommentParams{
		PublicID:    types.New(),
		WorkspaceID: workspaceID,
		TaskID:      sql.NullInt32{Int32: int32(taskInternalID), Valid: true}, //#nosec G115 -- tasks.id (INT UNSIGNED), fits int32
		AuthorID:    authorID,
		Body:        agentCommentPrefix + trimmed,
	}); err != nil {
		return fmt.Errorf("signaljudge: AddComment: insert comment: %w", err)
	}
	return nil
}

// resolveCommentAuthor picks a real users.id to satisfy the comments
// author_id FK for an agent-authored comment. Preference order:
//  1. the task's first enabled human assignee (task_actors), so the
//     comment surfaces under the owner most likely to act on it;
//  2. the workspace owner (workspace_members.role='owner'), the stable
//     fallback every workspace has.
//
// Returns sql.ErrNoRows when neither resolves (a degenerate workspace
// with no owner and no human assignee); the caller treats that as a
// skip rather than an error.
func (m *SQLTaskMutator) resolveCommentAuthor(ctx context.Context, workspaceID uint32, taskInternalID int64) (uint32, error) {
	const q = `
SELECT COALESCE(
  (
    SELECT ta.user_id
    FROM task_actors ta
    WHERE ta.workspace_id = ?
      AND ta.task_id = ?
      AND ta.enabled = TRUE
      AND ta.kind = 'user'
      AND ta.role = 'assignee'
      AND ta.user_id IS NOT NULL
    ORDER BY ta.id ASC
    LIMIT 1
  ),
  (
    SELECT wm.user_id
    FROM workspace_members wm
    WHERE wm.workspace_id = ?
      AND wm.role = 'owner'
      AND wm.enabled = TRUE
    ORDER BY wm.id ASC
    LIMIT 1
  )
) AS author_id`
	var authorID sql.NullInt32
	if err := m.DB.QueryRowContext(ctx, q, workspaceID, taskInternalID, workspaceID).Scan(&authorID); err != nil {
		return 0, err
	}
	if !authorID.Valid {
		return 0, sql.ErrNoRows
	}
	return uint32(authorID.Int32), nil //#nosec G115 -- users.id (INT UNSIGNED), fits uint32
}

// DraftRetroTask is the production implementation of the
// generate_retro branch.
//
// Flow:
//  1. SELECT the source task's workspace, project_id, title, and
//     first enabled human assignee user_id (best-effort).
//  2. BEGIN TX.
//  3. AssignTaskNumber + CreateTask + (optional) AddActor +
//     AddDependency(kind='retro_of'). Every write goes through the
//     sqlc-generated queries bound to the open transaction so the
//     existing prepared-statement cache and instrumentation are
//     reused.
//  4. COMMIT. Returns the new task's internal id and public id so
//     the Applier can embed them in the TaskRetroDrafted event.
//
// On any sub-error the transaction rolls back and the function
// returns the wrapped error verbatim. The caller (Applier) treats
// that as a signal to emit SignalRejected with reason
// "retro_creation_failed" instead of TaskRetroDrafted, per the L2
// brief.
//
// `draft` is the autonomy hint from the verdict: true under
// AutonomyDraft, false under AutonomyAuto. Both branches create the
// task at `derived_state='open'`; the flag is only used to confirm
// the L2 invariant ("retro draft tasks are always created in a
// reviewable state, even under autonomy=auto"). It is also forwarded
// to the TaskRetroDrafted payload by the Applier.
func (m *SQLTaskMutator) DraftRetroTask(
	ctx context.Context,
	workspaceID uint32,
	sourceTaskInternalID int64,
	agentID uint32,
	title string,
	draft bool,
) (int64, string, error) {
	if m == nil || m.DB == nil || m.Queries == nil {
		return 0, "", errors.New("signaljudge: SQLTaskMutator missing DB or Queries")
	}
	if workspaceID == 0 {
		return 0, "", errors.New("signaljudge: DraftRetroTask: workspaceID is zero")
	}
	if sourceTaskInternalID <= 0 {
		return 0, "", errors.New("signaljudge: DraftRetroTask: sourceTaskInternalID is zero")
	}

	// Look up the source task's project + title + first assignee.
	// Raw SQL to avoid coupling the signaljudge package to a sqlc
	// query whose only consumer is this function (the package
	// already uses the same pattern for [SQLTaskResolver] and
	// [SQLSignalUpdater]).
	src, err := m.loadRetroSource(ctx, workspaceID, sourceTaskInternalID)
	if err != nil {
		return 0, "", fmt.Errorf("signaljudge: load retro source: %w", err)
	}

	// Build the new retro task's title. Prefer the caller's title
	// (the Applier passes [retroTitle] which already names the
	// signal); fall back to the source task's own title prefixed
	// with `retroTitlePrefix` when the caller passed nothing.
	newTitle := strings.TrimSpace(title)
	if newTitle == "" {
		newTitle = retroTitlePrefix + src.Title
	}
	newTitle = truncateTitleRunes(newTitle, retroTitleMaxLen)

	// Description text — see [retroDescriptionTemplate].
	now := m.now().UTC()
	description := fmt.Sprintf(retroDescriptionTemplate, src.Title, now.Format("2006-01-02"))

	var (
		newPub    types.PublicID
		newTaskID int64
	)

	// Single transaction for both inserts (and the optional actor
	// row). dbretry.InTx retries on transient deadlocks; the inner
	// fn is idempotent because no row references the auto-increment
	// id of a previous attempt — both pubIDs (tasks + dependency +
	// actor) are minted fresh per attempt.
	txErr := dbretry.InTx(ctx, m.DB, "signaljudge.SQLTaskMutator.DraftRetroTask", nil, func(ctx context.Context, tx *sql.Tx) error {
		qtx := m.Queries.WithTx(tx)

		created, err := taskcreate.New(ctx, tx, taskcreate.Args{
			WorkspaceID: workspaceID,
			ProjectID:   src.ProjectID,
			// ActorUserID stays invalid: attribution for an agent-drafted
			// retro lives on events.actor_agent_id, not on the task row.
			ActorUserID: sql.NullInt32{},
			Title:       newTitle,
			Description: sql.NullString{String: description, Valid: true},
		})
		if err != nil {
			return fmt.Errorf("taskcreate.New: %w", err)
		}
		taskID := created.ID
		newPub = created.PublicID
		newTaskID = taskID

		// Best-effort assignee inheritance. When the source had a
		// human assignee, attach them to the retro draft so the
		// queue surfaces on their /me/tasks feed.
		if src.AssigneeUserID.Valid {
			actorPub := types.New()
			if _, aerr := qtx.AddActor(ctx, generated.AddActorParams{
				PublicID:    actorPub,
				WorkspaceID: workspaceID,
				TaskID:      uint32(taskID), //#nosec G115 -- LastInsertId for tasks.id (BIGINT UNSIGNED), fits uint32 within realistic deployments
				UserID:      src.AssigneeUserID,
				Role:        generated.TaskActorsRoleAssignee,
			}); aerr != nil {
				return fmt.Errorf("AddActor: %w", aerr)
			}
		}

		// retro_of edge. from = the new retro task, to = the
		// original task that prompted the retrospective. The schema
		// comment on [task_dependencies.kind] pins this orientation.
		depPub := types.New()
		if _, derr := qtx.AddDependency(ctx, generated.AddDependencyParams{
			PublicID:    depPub,
			WorkspaceID: workspaceID,
			FromTaskID:  uint32(taskID),               //#nosec G115 -- LastInsertId for tasks.id (BIGINT UNSIGNED), fits uint32 within realistic deployments
			ToTaskID:    uint32(sourceTaskInternalID), //#nosec G115 -- tasks.id (BIGINT UNSIGNED), fits uint32 within realistic deployments
			Kind:        generated.TaskDependenciesKindRetroOf,
		}); derr != nil {
			return fmt.Errorf("AddDependency(retro_of): %w", derr)
		}

		return nil
	})
	if txErr != nil {
		m.logger().WarnContext(ctx, "signaljudge: DraftRetroTask transaction rolled back",
			slog.Any("err", txErr),
			slog.Uint64("workspace_internal", uint64(workspaceID)),
			slog.Int64("source_task_internal", sourceTaskInternalID),
			slog.Uint64("agent_internal", uint64(agentID)),
			slog.Bool("draft", draft),
		)
		return 0, "", fmt.Errorf("signaljudge: draft retro task: %w", txErr)
	}

	return newTaskID, newPub.UUID().String(), nil
}

// retroSourceTask is the projection of the source task that
// [SQLTaskMutator.DraftRetroTask] needs. Defined as a private struct
// so a future column addition does not ripple into the public
// interface.
type retroSourceTask struct {
	ProjectID      uint32
	Title          string
	AssigneeUserID sql.NullInt32
}

// loadRetroSource performs the read-only lookup of the source task's
// (project_id, title, first enabled assignee user_id). Returns
// errors.Is(err, sql.ErrNoRows) when the source task does not exist
// in the workspace — the Applier resolved its internal id from a
// public_id so a missing row here is a TOCTOU between the resolver
// and the mutator; the caller surfaces it as
// "retro_creation_failed".
func (m *SQLTaskMutator) loadRetroSource(ctx context.Context, workspaceID uint32, sourceTaskInternalID int64) (retroSourceTask, error) {
	const q = `
SELECT
  t.project_id,
  t.title,
  (
    SELECT ta.user_id
    FROM task_actors ta
    WHERE ta.task_id = t.id
      AND ta.enabled = TRUE
      AND ta.kind = 'user'
      AND ta.role = 'assignee'
    ORDER BY ta.id ASC
    LIMIT 1
  ) AS assignee_user_id
FROM tasks t
WHERE t.workspace_id = ?
  AND t.id = ?
  AND t.enabled = TRUE
LIMIT 1`
	var src retroSourceTask
	if err := m.DB.QueryRowContext(ctx, q, workspaceID, sourceTaskInternalID).Scan(
		&src.ProjectID,
		&src.Title,
		&src.AssigneeUserID,
	); err != nil {
		return retroSourceTask{}, err
	}
	return src, nil
}

// logger returns a non-nil *slog.Logger.
func (m *SQLTaskMutator) logger() *slog.Logger {
	if m.Logger != nil {
		return m.Logger
	}
	return slog.Default()
}

// now returns the wall-clock used to stamp the retro description.
func (m *SQLTaskMutator) now() time.Time {
	if m.NowFn != nil {
		return m.NowFn()
	}
	return time.Now()
}

// truncateTitleRunes returns s clipped to at most maxRunes runes,
// with a trailing "…" when truncation occurred. Operates on runes
// rather than bytes so multi-byte characters are not split.
//
// maxRunes < 1 returns the empty string. maxRunes >= len([]rune(s))
// returns s verbatim.
func truncateTitleRunes(s string, maxRunes int) string {
	if maxRunes < 1 {
		return ""
	}
	r := []rune(s)
	if len(r) <= maxRunes {
		return s
	}
	// Reserve one rune for the ellipsis.
	if maxRunes == 1 {
		return "…"
	}
	return string(r[:maxRunes-1]) + "…"
}
