// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// AI.COST.GUARD_EXCEEDED — AI cost guard threshold exceeded
	AiCostGuardExceeded = &Spec{Code: "AI.COST.GUARD_EXCEEDED", Status: 402, Message: "AI cost guard threshold exceeded"}
	// AI.PROVIDER.NOT_CONFIGURED — AI provider is not configured
	AiProviderNotConfigured = &Spec{Code: "AI.PROVIDER.NOT_CONFIGURED", Status: 412, Message: "AI provider is not configured"}
	// AI.PROVIDER.UPSTREAM_CALL_FAILED — AI provider call failed
	AiProviderUpstreamCallFailed = &Spec{Code: "AI.PROVIDER.UPSTREAM_CALL_FAILED", Status: 502, Message: "AI provider call failed"}
	// AI.PROVIDER.UPSTREAM_TIMEOUT — AI provider call timed out
	AiProviderUpstreamTimeout = &Spec{Code: "AI.PROVIDER.UPSTREAM_TIMEOUT", Status: 504, Message: "AI provider call timed out"}
	// AI.REDACTION.PIPELINE_FAILED — Sensitive data redaction failed
	AiRedactionPipelineFailed = &Spec{Code: "AI.REDACTION.PIPELINE_FAILED", Status: 500, Message: "Sensitive data redaction failed"}
	// AI.SAFETY.BLOCKED — Request blocked by safety policy
	AiSafetyBlocked = &Spec{Code: "AI.SAFETY.BLOCKED", Status: 422, Message: "Request blocked by safety policy"}
)
