// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// AI.AGENT.NOT_FOUND — AI agent not found
	AiAgentNotFound = &Spec{Code: "AI.AGENT.NOT_FOUND", Status: 404, Message: "AI agent not found"}
	// AI.AGENT.PAUSED — AI agent is paused
	AiAgentPaused = &Spec{Code: "AI.AGENT.PAUSED", Status: 409, Message: "AI agent is paused"}
	// AI.AGENT.RUNTIME_DISABLED — AI agent runtime is not configured
	AiAgentRuntimeDisabled = &Spec{Code: "AI.AGENT.RUNTIME_DISABLED", Status: 503, Message: "AI agent runtime is not configured"}
	// AI.COST.GUARD_EXCEEDED — AI cost guard threshold exceeded
	AiCostGuardExceeded = &Spec{Code: "AI.COST.GUARD_EXCEEDED", Status: 402, Message: "AI cost guard threshold exceeded"}
	// AI.MODEL.NOT_FOUND — AI model not found
	AiModelNotFound = &Spec{Code: "AI.MODEL.NOT_FOUND", Status: 404, Message: "AI model not found"}
	// AI.NL_QUERY.UNPARSEABLE — Could not turn that into a filter
	AiNlQueryUnparseable = &Spec{Code: "AI.NL_QUERY.UNPARSEABLE", Status: 422, Message: "Could not turn that into a filter"}
	// AI.PROVIDER.NOT_CONFIGURED — AI provider is not configured
	AiProviderNotConfigured = &Spec{Code: "AI.PROVIDER.NOT_CONFIGURED", Status: 412, Message: "AI provider is not configured"}
	// AI.PROVIDER.UPSTREAM_CALL_FAILED — AI provider call failed
	AiProviderUpstreamCallFailed = &Spec{Code: "AI.PROVIDER.UPSTREAM_CALL_FAILED", Status: 502, Message: "AI provider call failed"}
	// AI.PROVIDER.UPSTREAM_TIMEOUT — AI provider call timed out
	AiProviderUpstreamTimeout = &Spec{Code: "AI.PROVIDER.UPSTREAM_TIMEOUT", Status: 504, Message: "AI provider call timed out"}
	// AI.REDACTION.PIPELINE_FAILED — Sensitive data redaction failed
	AiRedactionPipelineFailed = &Spec{Code: "AI.REDACTION.PIPELINE_FAILED", Status: 500, Message: "Sensitive data redaction failed"}
	// AI.RESPONSE.PARSE_FAILED — AI provider response could not be parsed
	AiResponseParseFailed = &Spec{Code: "AI.RESPONSE.PARSE_FAILED", Status: 502, Message: "AI provider response could not be parsed"}
	// AI.SAFETY.BLOCKED — Request blocked by safety policy
	AiSafetyBlocked = &Spec{Code: "AI.SAFETY.BLOCKED", Status: 422, Message: "Request blocked by safety policy"}
)
