// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// CONSTRAINT.EVAL.BAD_DATE — Constraint date argument is not a valid YYYY-MM-DD
	ConstraintEvalBadDate = &Spec{Code: "CONSTRAINT.EVAL.BAD_DATE", Status: 422, Message: "Constraint date argument is not a valid YYYY-MM-DD"}
	// CONSTRAINT.PARSE.EMPTY_TERMS — Constraint and/or requires at least one term
	ConstraintParseEmptyTerms = &Spec{Code: "CONSTRAINT.PARSE.EMPTY_TERMS", Status: 422, Message: "Constraint and/or requires at least one term"}
	// CONSTRAINT.PARSE.INVALID_JSON — Constraint expression is not valid JSON
	ConstraintParseInvalidJson = &Spec{Code: "CONSTRAINT.PARSE.INVALID_JSON", Status: 422, Message: "Constraint expression is not valid JSON"}
	// CONSTRAINT.PARSE.MISSING_ARG — Constraint expression is missing a required argument
	ConstraintParseMissingArg = &Spec{Code: "CONSTRAINT.PARSE.MISSING_ARG", Status: 422, Message: "Constraint expression is missing a required argument"}
	// CONSTRAINT.PARSE.UNKNOWN_OP — Constraint expression uses an unknown operator
	ConstraintParseUnknownOp = &Spec{Code: "CONSTRAINT.PARSE.UNKNOWN_OP", Status: 422, Message: "Constraint expression uses an unknown operator"}
)
