// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// PAGE.GENERATION.UPSTREAM_UNAVAILABLE — AI page generation failed
	PageGenerationUpstreamUnavailable = &Spec{Code: "PAGE.GENERATION.UPSTREAM_UNAVAILABLE", Status: 502, Message: "AI page generation failed"}
	// PAGE.PAGE.CIRCULAR_PARENT — Cannot set parent to self or descendant
	PagePageCircularParent = &Spec{Code: "PAGE.PAGE.CIRCULAR_PARENT", Status: 400, Message: "Cannot set parent to self or descendant"}
	// PAGE.PAGE.MAX_DEPTH — Maximum nesting depth exceeded
	PagePageMaxDepth = &Spec{Code: "PAGE.PAGE.MAX_DEPTH", Status: 400, Message: "Maximum nesting depth exceeded"}
	// PAGE.PAGE.NOT_FOUND — Page not found
	PagePageNotFound = &Spec{Code: "PAGE.PAGE.NOT_FOUND", Status: 404, Message: "Page not found"}
	// PAGE.PAGE.TITLE_TAKEN — A page with this title already exists under the same parent
	PagePageTitleTaken = &Spec{Code: "PAGE.PAGE.TITLE_TAKEN", Status: 409, Message: "A page with this title already exists under the same parent"}
)
