// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// TIMEBOX.TASK.ALREADY_ADDED — Task is already in this timebox
	TimeboxTaskAlreadyAdded = &Spec{Code: "TIMEBOX.TASK.ALREADY_ADDED", Status: 409, Message: "Task is already in this timebox"}
	// TIMEBOX.TASK.NOT_IN_TIMEBOX — Task not found in this timebox
	TimeboxTaskNotInTimebox = &Spec{Code: "TIMEBOX.TASK.NOT_IN_TIMEBOX", Status: 404, Message: "Task not found in this timebox"}
	// TIMEBOX.TIMEBOX.ALREADY_COMPLETED — Cannot modify a completed timebox
	TimeboxTimeboxAlreadyCompleted = &Spec{Code: "TIMEBOX.TIMEBOX.ALREADY_COMPLETED", Status: 409, Message: "Cannot modify a completed timebox"}
	// TIMEBOX.TIMEBOX.INVALID_DATES — Timebox end date must be after start date
	TimeboxTimeboxInvalidDates = &Spec{Code: "TIMEBOX.TIMEBOX.INVALID_DATES", Status: 422, Message: "Timebox end date must be after start date"}
	// TIMEBOX.TIMEBOX.NAME_TAKEN — A timebox with this name already exists in the workspace
	TimeboxTimeboxNameTaken = &Spec{Code: "TIMEBOX.TIMEBOX.NAME_TAKEN", Status: 409, Message: "A timebox with this name already exists in the workspace"}
	// TIMEBOX.TIMEBOX.NOT_FOUND — Timebox not found
	TimeboxTimeboxNotFound = &Spec{Code: "TIMEBOX.TIMEBOX.NOT_FOUND", Status: 404, Message: "Timebox not found"}
)
