// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// VALIDATION.BODY.DATE_FORMAT_INVALID — Date must be in YYYY-MM-DD format
	ValidationBodyDateFormatInvalid = &Spec{Code: "VALIDATION.BODY.DATE_FORMAT_INVALID", Status: 400, Message: "Date must be in YYYY-MM-DD format"}
	// VALIDATION.BODY.FIELD_INVALID — A field in the request body is invalid
	ValidationBodyFieldInvalid = &Spec{Code: "VALIDATION.BODY.FIELD_INVALID", Status: 422, Message: "A field in the request body is invalid"}
	// VALIDATION.BODY.FIELD_MISSING — A required field is missing in the request body
	ValidationBodyFieldMissing = &Spec{Code: "VALIDATION.BODY.FIELD_MISSING", Status: 422, Message: "A required field is missing in the request body"}
	// VALIDATION.BODY.UNPARSEABLE — Request body could not be parsed
	ValidationBodyUnparseable = &Spec{Code: "VALIDATION.BODY.UNPARSEABLE", Status: 400, Message: "Request body could not be parsed"}
	// VALIDATION.PATH.PARAM_INVALID — A path parameter is invalid
	ValidationPathParamInvalid = &Spec{Code: "VALIDATION.PATH.PARAM_INVALID", Status: 400, Message: "A path parameter is invalid"}
	// VALIDATION.QUERY.FIELD_INVALID — A query parameter is invalid
	ValidationQueryFieldInvalid = &Spec{Code: "VALIDATION.QUERY.FIELD_INVALID", Status: 422, Message: "A query parameter is invalid"}
	// VALIDATION.QUERY.UNKNOWN_FIELD — Unknown query parameter
	ValidationQueryUnknownField = &Spec{Code: "VALIDATION.QUERY.UNKNOWN_FIELD", Status: 422, Message: "Unknown query parameter"}
)
