// Code generated by gen-errors. DO NOT EDIT.

package errors

// Error codes and specs.
var (
	// WEBHOOK.DELIVERY.ALREADY_DELIVERED — Webhook delivery has already been completed
	WebhookDeliveryAlreadyDelivered = &Spec{Code: "WEBHOOK.DELIVERY.ALREADY_DELIVERED", Status: 409, Message: "Webhook delivery has already been completed"}
	// WEBHOOK.DELIVERY.NOT_FOUND — Webhook delivery not found
	WebhookDeliveryNotFound = &Spec{Code: "WEBHOOK.DELIVERY.NOT_FOUND", Status: 404, Message: "Webhook delivery not found"}
	// WEBHOOK.SUBSCRIPTION.LIMIT_EXCEEDED — Maximum webhook subscriptions per workspace reached
	WebhookSubscriptionLimitExceeded = &Spec{Code: "WEBHOOK.SUBSCRIPTION.LIMIT_EXCEEDED", Status: 409, Message: "Maximum webhook subscriptions per workspace reached"}
	// WEBHOOK.SUBSCRIPTION.NOT_FOUND — Webhook subscription not found
	WebhookSubscriptionNotFound = &Spec{Code: "WEBHOOK.SUBSCRIPTION.NOT_FOUND", Status: 404, Message: "Webhook subscription not found"}
	// WEBHOOK.SUBSCRIPTION.URL_UNREACHABLE — Webhook URL is not reachable
	WebhookSubscriptionUrlUnreachable = &Spec{Code: "WEBHOOK.SUBSCRIPTION.URL_UNREACHABLE", Status: 400, Message: "Webhook URL is not reachable"}
)
