// Code generated by gen-errors. DO NOT EDIT.

package errors

import "github.com/libraz/nodate-flow/packages/go-shared/apierr"

// Spec describes an error code defined in errors/*.yaml.
type Spec = apierr.Spec

// APIError is the runtime error value carried through the API. It wraps a
// Spec and optional details for structured rendering.
type APIError = apierr.APIError

// New constructs an APIError from a Spec.
var New = apierr.New

// Newf constructs an APIError from a Spec and wraps a formatted cause.
var Newf = apierr.Newf

// Wrap constructs an APIError from a Spec and an underlying cause.
var Wrap = apierr.Wrap
