-- ====================================
-- pages
-- Wiki/documentation pages with tree structure.
-- A page belongs to a workspace and optionally scopes to a project.
-- Self-referential parent_page_id enables nested page hierarchies.
-- Titles are unique among the live children of one parent, root pages
-- included.
-- ====================================
CREATE TABLE pages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  project_id INT UNSIGNED NULL COMMENT 'Internal FK to projects.id (NULL = workspace-wide)',
  creator_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',
  parent_page_id INT UNSIGNED NULL COMMENT 'Internal FK to pages.id (NULL = root page)',
  -- Parent value for the title-uniqueness key below. parent_page_id stays
  -- nullable because NULL is what "root page" means and the foreign key
  -- depends on it, but a unique index never treats an entry containing
  -- NULL as a duplicate: keyed on parent_page_id directly the key would
  -- bind only child pages and let a workspace hold any number of live
  -- root pages with the same title — which is most pages. See
  -- sql/core/conformance/schema/50-nullable-unique-keys.sql.
  scope_parent_page_id INT UNSIGNED GENERATED ALWAYS AS (IFNULL(parent_page_id, 0)) VIRTUAL NOT NULL COMMENT 'The page this one sits under, or 0 when it is a root page. Exists only so the title-uniqueness key binds on root pages; AUTO_INCREMENT never issues 0, so it cannot name a real page. VIRTUAL rather than STORED because a STORED NOT NULL generated column fails the precondition check for the ON DELETE SET NULL foreign key on parent_page_id.',

  title VARCHAR(500) NOT NULL COMMENT 'Page title. Unique among live siblings under the same parent. The comparison is the table collation, which is case- and accent-insensitive and compares kana by primary weight, so two sibling titles differing only in letter case, accents or kana form are the same title — matching what a reader can tell apart in the tree, and matching how the title search already compares.',
  body MEDIUMTEXT NOT NULL COMMENT 'Page content',
  is_ai_generated BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether the page was generated by AI',
  archived_at DATETIME(3) NULL COMMENT 'Set when page is archived (distinct from enabled)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order among siblings',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  -- Liveness marker scoping the title-uniqueness key below to live rows:
  -- 1 while enabled, NULL once soft-deleted, so a deleted page releases
  -- its title and tombstones accumulate without colliding with each
  -- other. See the soft-delete rule in
  -- sql/core/conformance/schema/40-soft-delete-uniqueness.sql.
  active TINYINT UNSIGNED GENERATED ALWAYS AS (IF(enabled, 1, NULL)) VIRTUAL COMMENT 'NULL once soft-deleted; exists only to scope the title-uniqueness key below to live rows',
  updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE KEY uniq_pages_public_id (public_id),
  UNIQUE KEY uniq_pages_workspace_public_id (workspace_id, public_id),
  -- One live page per title among the children of one parent. The tree is
  -- navigated by reading sibling titles, so two siblings sharing one is a
  -- pair a reader cannot tell apart, and the API answers the second
  -- attempt with a conflict rather than creating it. workspace_id leads
  -- the key because a page id is only meaningful inside its workspace and
  -- because every read of this table is already workspace-scoped.
  UNIQUE KEY uniq_pages_workspace_id_scope_parent_page_id_title_active (workspace_id, scope_parent_page_id, title, active),
  KEY idx_pages_workspace_id_archived_at (workspace_id, archived_at),
  KEY idx_pages_workspace_id_enabled_sort_weight (workspace_id, enabled, sort_weight),
  KEY idx_pages_workspace_id_project_id (workspace_id, project_id),
  -- Bare parent_page_id index backing the self-referential foreign key.
  -- The unique key above leads with workspace_id and keys the de-NULLed
  -- projection rather than the column itself, so it cannot serve either
  -- the constraint or a parent_page_id-only lookup, and leaving this out
  -- would have InnoDB create an unnamed index instead.
  KEY idx_pages_parent_page_id (parent_page_id),
  FULLTEXT KEY ft_pages_title (title),

  CONSTRAINT fk_pages_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_pages_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_pages_creator FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_pages_parent FOREIGN KEY (parent_page_id) REFERENCES pages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Wiki/documentation pages with tree structure';
