-- ====================================
-- task_dependencies
-- Directed edges between tasks. from_task is the dependent / originating side,
-- to_task is the target. Supported kinds:
--   - blocks       : from_task is blocked until to_task completes
--   - relates      : informational sibling link, no scheduling impact
--   - duplicates   : from_task duplicates to_task (resolved together)
--   - subtask_of   : from_task is a subtask of to_task (hierarchy)
--   - retro_of     : from_task is a retrospective draft generated by the
--                    signal_judge Applier when an event-day signal triggers
--                    a retro for to_task (the original task whose lifecycle
--                    finished and prompted the retrospective).
-- ====================================
CREATE TABLE task_dependencies (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  from_task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id (source)',
  to_task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id (target)',

  kind ENUM('blocks','relates','duplicates','subtask_of','retro_of') NOT NULL DEFAULT 'blocks' COMMENT 'Dependency kind. blocks: from_task waits on to_task. relates: informational link. duplicates: from_task duplicates to_task. subtask_of: from_task is a subtask of to_task. retro_of: created by the signal_judge Applier when an event-day signal triggers a retrospective draft task; from_task is the new draft, to_task is the original task whose lifecycle finished and prompted the retro.',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  -- Liveness marker scoping the unique key below to live rows: 1 while
  -- enabled, NULL once soft-deleted, so tombstones leave the index
  -- rather than colliding with each other. See the soft-delete rule in
  -- sql/core/conformance/schema/40-soft-delete-uniqueness.sql.
  active TINYINT UNSIGNED GENERATED ALWAYS AS (IF(enabled, 1, NULL)) VIRTUAL COMMENT 'NULL once soft-deleted; exists only to scope the unique key below to live rows',
  updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE KEY uniq_task_dependencies_public_id (public_id),
  UNIQUE KEY uniq_task_dependencies_workspace_public_id (workspace_id, public_id),
  UNIQUE KEY uniq_task_dependencies_edge (from_task_id, to_task_id, kind, active),
  KEY idx_task_dependencies_workspace_from (workspace_id, from_task_id),
  KEY idx_task_dependencies_workspace_to (workspace_id, to_task_id),
  -- Bare to_task_id index for ON DELETE CASCADE on tasks. The workspace-leading
  -- composite above does not satisfy to_task_id-only lookups, and the unique
  -- edge key only helps for from_task_id leading queries.
  KEY idx_task_dependencies_to_task_id (to_task_id),

  CONSTRAINT fk_task_dependencies_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_dependencies_from FOREIGN KEY (from_task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_dependencies_to FOREIGN KEY (to_task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT chk_task_dependencies_no_self CHECK (from_task_id != to_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Directed task dependencies';
