package middleware

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"net/http"
)

// nonceCtxKey is the context key for the per-request CSP style nonce.
type nonceCtxKey struct{}

// NonceFromContext extracts the CSP style nonce generated by the
// [SecurityHeaders] middleware. Returns an empty string when no nonce
// is present (should not happen when the middleware is mounted).
func NonceFromContext(ctx context.Context) string {
	v, _ := ctx.Value(nonceCtxKey{}).(string)
	return v
}

// generateNonce produces a cryptographically random 16-byte nonce
// encoded as unpadded base64. On the extremely unlikely failure of
// crypto/rand it returns an empty string (the CSP header will fall back
// to blocking inline styles, which is the safe default).
func generateNonce() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return ""
	}
	return base64.RawStdEncoding.EncodeToString(b)
}

// SecurityHeaders is a chi-compatible middleware that sets a standard set
// of security-related response headers on every reply. Mount it early in
// the chain (right after [ClientIP]) so the headers are present even on
// error responses produced by inner middleware.
//
// A per-request cryptographic nonce is generated and stored in the
// request context (see [NonceFromContext]). The CSP style-src directive
// uses this nonce so that only explicitly tagged <style> elements are
// allowed.
func SecurityHeaders() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			nonce := generateNonce()
			ctx := context.WithValue(r.Context(), nonceCtxKey{}, nonce)

			h := w.Header()

			styleSrc := "'self'"
			if nonce != "" {
				styleSrc = "'self' 'nonce-" + nonce + "'"
			}
			h.Set("Content-Security-Policy",
				"default-src 'self'; script-src 'self'; style-src "+styleSrc+"; "+
					"img-src 'self' data: blob:; connect-src 'self'; font-src 'self'; frame-ancestors 'none'")
			h.Set("Strict-Transport-Security", "max-age=63072000; includeSubDomains; preload")
			h.Set("X-Content-Type-Options", "nosniff")
			h.Set("X-Frame-Options", "DENY")
			h.Set("Referrer-Policy", "strict-origin-when-cross-origin")
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
