#!/usr/bin/env bash
# build-schema.sh
# Concatenate tables/*.sql then views/*.sql into a single schema stream.
# Pre-release: no migrations. Intended usage is drop & recreate.
#
#   bash sql/build-schema.sh | mysql -h 127.0.0.1 -u root -p nodate_flow
#
# FK checks are toggled OFF at the top and ON at the bottom so tables can be
# loaded in plain alphabetical order regardless of dependency direction.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TABLES_DIR="${SCRIPT_DIR}/tables"
VIEWS_DIR="${SCRIPT_DIR}/views"

echo "-- Generated by sql/build-schema.sh"
echo "-- DO NOT EDIT the output; edit files in sql/tables/ or sql/views/."
echo "SET NAMES utf8mb4;"
echo "SET FOREIGN_KEY_CHECKS = 0;"
echo "SET UNIQUE_CHECKS = 0;"
echo

if [[ -d "${TABLES_DIR}" ]]; then
  # Drop existing tables first so a re-run is idempotent.
  for f in "${TABLES_DIR}"/*.sql; do
    [[ -e "${f}" ]] || continue
    name="$(basename "${f}" .sql)"
    echo "DROP TABLE IF EXISTS \`${name}\`;"
  done
  echo

  for f in "${TABLES_DIR}"/*.sql; do
    [[ -e "${f}" ]] || continue
    echo "-- >>> $(basename "${f}")"
    cat "${f}"
    echo
  done
fi

if [[ -d "${VIEWS_DIR}" ]]; then
  # Base views (suffix `_all.sql`) are loaded before their dependants so that
  # filtered child views (e.g. v_task_list, v_task_list_archived) can reference
  # them. Default glob ordering would otherwise put `v_task_list.sql` before
  # `v_task_list_all.sql` because '.' (0x2E) sorts before '_' (0x5F).
  base_views=()
  leaf_views=()
  for f in "${VIEWS_DIR}"/*.sql; do
    [[ -e "${f}" ]] || continue
    if [[ "$(basename "${f}")" == *_all.sql ]]; then
      base_views+=("${f}")
    else
      leaf_views+=("${f}")
    fi
  done

  # Drop in reverse dependency order: leaves first, then bases.
  for f in "${leaf_views[@]:-}" "${base_views[@]:-}"; do
    [[ -n "${f:-}" && -e "${f}" ]] || continue
    name="$(basename "${f}" .sql)"
    echo "DROP VIEW IF EXISTS \`${name}\`;"
  done
  echo

  # Create in dependency order: bases first, then leaves.
  for f in "${base_views[@]:-}" "${leaf_views[@]:-}"; do
    [[ -n "${f:-}" && -e "${f}" ]] || continue
    echo "-- >>> $(basename "${f}")"
    cat "${f}"
    echo
  done
fi

echo "SET UNIQUE_CHECKS = 1;"
echo "SET FOREIGN_KEY_CHECKS = 1;"
