-- Generated by sql/build-schema.sh
-- DO NOT EDIT the output; edit files in sql/tables/ or sql/views/.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;

DROP TABLE IF EXISTS `agent_runs`;
DROP TABLE IF EXISTS `ai_agents`;
DROP TABLE IF EXISTS `ai_invocations`;
DROP TABLE IF EXISTS `ai_models`;
DROP TABLE IF EXISTS `ai_providers`;
DROP TABLE IF EXISTS `ai_settings`;
DROP TABLE IF EXISTS `attachments`;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `events`;
DROP TABLE IF EXISTS `identities`;
DROP TABLE IF EXISTS `instance_admins`;
DROP TABLE IF EXISTS `instance_audit_logs`;
DROP TABLE IF EXISTS `mcp_invocations`;
DROP TABLE IF EXISTS `mcp_tokens`;
DROP TABLE IF EXISTS `oauth_states`;
DROP TABLE IF EXISTS `personal_access_tokens`;
DROP TABLE IF EXISTS `project_members`;
DROP TABLE IF EXISTS `projects`;
DROP TABLE IF EXISTS `sessions`;
DROP TABLE IF EXISTS `signals`;
DROP TABLE IF EXISTS `task_actors`;
DROP TABLE IF EXISTS `task_constraints`;
DROP TABLE IF EXISTS `task_dependencies`;
DROP TABLE IF EXISTS `task_embeddings`;
DROP TABLE IF EXISTS `tasks`;
DROP TABLE IF EXISTS `user_integrations`;
DROP TABLE IF EXISTS `user_recovery_codes`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `workspace_members`;
DROP TABLE IF EXISTS `workspaces`;

-- >>> agent_runs.sql
-- ====================================
-- agent_runs
-- Queue + history for AI agent executions (4.AGENT-1 scheduler/worker
-- split). The scheduler enqueues one row per due (agent, scheduled_at)
-- pair with a UNIQUE dedupe_key so multiple scheduler replicas cannot
-- double-fire a job. Workers claim rows with SELECT ... FOR UPDATE
-- SKIP LOCKED, run the agent, then update status to succeeded / failed.
-- Completed rows are retained as the audit trail for
-- `ai.agent.run.*` events (ADR 0002 — events in MySQL).
-- ====================================
CREATE TABLE agent_runs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  agent_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to ai_agents.id',

  dedupe_key VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Unique key shaped as <agent_id>:<unix_minute> to prevent double enqueue across scheduler replicas',
  status ENUM('pending','claimed','succeeded','failed') NOT NULL DEFAULT 'pending' COMMENT 'Lifecycle state',
  attempts TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Number of claim attempts (for retry budget)',
  scheduled_at DATETIME NOT NULL COMMENT 'Tick time the scheduler enqueued the run for',
  claimed_at DATETIME NULL COMMENT 'When a worker claimed the row',
  finished_at DATETIME NULL COMMENT 'When the worker ack/nacked the row',
  error_message TEXT NULL COMMENT 'Last failure message for operator visibility',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_agent_runs_public_id (public_id),
  UNIQUE KEY uniq_agent_runs_dedupe_key (dedupe_key),
  KEY idx_agent_runs_status_scheduled_at (status, scheduled_at),
  KEY idx_agent_runs_workspace_id_agent_id (workspace_id, agent_id),

  CONSTRAINT fk_agent_runs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_runs_agent FOREIGN KEY (agent_id) REFERENCES ai_agents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent execution queue + history';

-- >>> ai_agents.sql
-- ====================================
-- ai_agents
-- Reusable LLM agent configuration: a model + system prompt + defaults.
-- Agents are referenced by automations and MCP tools.
-- ====================================
CREATE TABLE ai_agents (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  model_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to ai_models.id',

  name VARCHAR(255) NOT NULL COMMENT 'Human-readable agent name',
  description TEXT NULL COMMENT 'Free-form description',
  system_prompt MEDIUMTEXT NOT NULL COMMENT 'System prompt text',
  temperature SMALLINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Sampling temperature x100 (e.g., 100 = 1.00)',
  max_output_tokens INT UNSIGNED NULL COMMENT 'Per-call output cap (null = model default)',
  tools_json JSON NULL COMMENT 'Allowed tool list as JSON array',
  allowed_scopes_json JSON NULL COMMENT 'Allowed MCP scope list as JSON array (null = inherit from token)',
  monthly_cost_cap_cents INT UNSIGNED NULL COMMENT 'Monthly spend cap in USD cents (null = no cap)',
  schedule_kind ENUM('disabled','interval','on_event','manual') NOT NULL DEFAULT 'disabled' COMMENT 'Trigger mode: interval = fires every NF_AGENT_TICK_INTERVAL; on_event = fires from eventbus; manual = only via /agents/{id}/trigger',
  event_trigger_types JSON NULL COMMENT 'JSON array of eventbus Kind strings that fire this agent when schedule_kind=on_event (e.g., ["signal.attached","task.transition.submit"])',
  paused BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Manually or automatically paused (e.g., cost cap exceeded)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_ai_agents_public_id (public_id),
  KEY idx_ai_agents_workspace_id_enabled (workspace_id, enabled),
  KEY idx_ai_agents_model_id (model_id),

  CONSTRAINT fk_ai_agents_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_agents_model FOREIGN KEY (model_id) REFERENCES ai_models(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Reusable LLM agent configurations';

-- >>> ai_invocations.sql
-- ====================================
-- ai_invocations
-- LLM call audit. Prompts and responses are stored redacted; raw secrets
-- must never appear here.
-- ====================================
CREATE TABLE ai_invocations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  provider_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to ai_providers.id',
  user_id INT UNSIGNED NULL COMMENT 'Internal FK to users.id (if user-initiated)',
  agent_id INT UNSIGNED NULL COMMENT 'Internal FK to ai_agents.id when the call was made on behalf of an AI agent (2.MCP-2)',
  task_id INT UNSIGNED NULL COMMENT 'Internal FK to tasks.id if applicable',

  purpose VARCHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Logical call purpose (e.g., propose_tasks)',
  model VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Model name actually used',
  prompt_redacted MEDIUMTEXT NOT NULL COMMENT 'Redacted prompt text',
  response_redacted MEDIUMTEXT NULL COMMENT 'Redacted response text',
  tokens_input INT UNSIGNED NULL COMMENT 'Input token count',
  tokens_output INT UNSIGNED NULL COMMENT 'Output token count',
  cost_estimate DECIMAL(10,6) NULL COMMENT 'Estimated cost (USD)',
  status ENUM('ok','error','blocked') NOT NULL COMMENT 'Outcome',
  error_code VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'Error code when status != ok',
  invoked_at DATETIME NOT NULL COMMENT 'Invocation time (second precision)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_ai_invocations_public_id (public_id),
  KEY idx_ai_invocations_workspace_id_invoked_at (workspace_id, invoked_at),
  KEY idx_ai_invocations_workspace_id_provider_id (workspace_id, provider_id),
  KEY idx_ai_invocations_agent_id_invoked_at (agent_id, invoked_at),

  CONSTRAINT fk_ai_invocations_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_invocations_provider FOREIGN KEY (provider_id) REFERENCES ai_providers(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_invocations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_invocations_agent FOREIGN KEY (agent_id) REFERENCES ai_agents(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_invocations_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM invocation audit';

-- >>> ai_models.sql
-- ====================================
-- ai_models
-- Concrete model offered by an ai_providers row. Pricing is stored as
-- micro-USD per 1M tokens to keep integer math.
-- ====================================
CREATE TABLE ai_models (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  provider_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to ai_providers.id',

  name VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Provider model identifier (e.g., claude-opus-4)',
  display_name VARCHAR(255) NOT NULL COMMENT 'Human-readable label',
  context_window INT UNSIGNED NOT NULL COMMENT 'Max context tokens',
  max_output_tokens INT UNSIGNED NULL COMMENT 'Max generated tokens (null = same as context)',
  input_price_micro_usd_per_mtok BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Input price in micro-USD per 1M tokens',
  output_price_micro_usd_per_mtok BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Output price in micro-USD per 1M tokens',
  supports_tools BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether model supports tool use',
  supports_vision BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether model supports image input',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_ai_models_public_id (public_id),
  UNIQUE KEY uniq_ai_models_provider_id_name (provider_id, name),
  KEY idx_ai_models_workspace_id_enabled (workspace_id, enabled),

  CONSTRAINT fk_ai_models_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_models_provider FOREIGN KEY (provider_id) REFERENCES ai_providers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Concrete LLM models per provider';

-- >>> ai_providers.sql
-- ====================================
-- ai_providers
-- LLM provider configurations. api_key_ciphertext stores AES-256-GCM
-- output (nonce + tag + ciphertext) and is NEVER read back via the API.
-- ====================================
CREATE TABLE ai_providers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',

  kind ENUM('anthropic','openai','google','ollama','openai_compat') NOT NULL COMMENT 'Provider kind',
  name VARCHAR(255) NOT NULL COMMENT 'Human-readable label',
  base_url VARCHAR(1024) NULL COMMENT 'API base URL (required for openai_compat/ollama)',
  api_key_ciphertext VARBINARY(512) NOT NULL COMMENT 'AES-256-GCM nonce+tag+ciphertext',
  api_key_prefix CHAR(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Leading chars for display masking',
  api_key_suffix CHAR(4) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Trailing chars for display masking',
  default_model VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'Default model name',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_ai_providers_public_id (public_id),
  KEY idx_ai_providers_workspace_id_enabled (workspace_id, enabled),

  CONSTRAINT fk_ai_providers_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM provider credentials';

-- >>> ai_settings.sql
-- ====================================
-- ai_settings
-- Per-workspace AI configuration (ADR 0003).
-- Holds duplicate-detection thresholds and the embed-budget bucket that
-- the CostGuard tracks separately from the LLM chat budget.
--
-- Settings are not user-facing entities, so no public_id: the row is
-- addressed by its parent workspace.
-- ====================================
CREATE TABLE ai_settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',

  embed_model              VARCHAR(64)  NOT NULL DEFAULT 'mock-768' COMMENT 'Embedding model key (resolved by ai/embed registry)',
  embed_budget_cents_day   INT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Daily embed cost cap in cents (separate bucket from chat budget)',
  duplicate_threshold_high DECIMAL(4,3) NOT NULL DEFAULT 0.870 COMMENT 'Cosine sim >= this -> duplicate candidate',
  duplicate_threshold_low  DECIMAL(4,3) NOT NULL DEFAULT 0.750 COMMENT 'Cosine sim in [low, high) -> related task',

  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_ai_settings_workspace (workspace_id),

  CONSTRAINT fk_ai_settings_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-workspace AI configuration (ADR 0003)';

-- >>> attachments.sql
-- ====================================
-- attachments
-- Files uploaded against a task. The actual blob lives in object storage
-- under storage_key; this row is the metadata index.
-- ====================================
CREATE TABLE attachments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id',
  uploader_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id (uploader)',

  filename VARCHAR(255) NOT NULL COMMENT 'Original filename',
  content_type VARCHAR(127) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'MIME type',
  byte_size BIGINT UNSIGNED NOT NULL COMMENT 'Size in bytes',
  storage_key VARCHAR(512) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Object storage key (e.g., s3 key)',
  checksum_sha256 CHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'SHA-256 hex of file contents',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_attachments_public_id (public_id),
  UNIQUE KEY uniq_attachments_storage_key (storage_key),
  KEY idx_attachments_workspace_id_task_id (workspace_id, task_id),
  KEY idx_attachments_workspace_id_uploader_id (workspace_id, uploader_id),

  CONSTRAINT fk_attachments_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_attachments_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_attachments_uploader FOREIGN KEY (uploader_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Task file attachments metadata';

-- >>> audit_logs.sql
-- ====================================
-- audit_logs
-- Workspace-scoped audit trail for sensitive actions (auth, ACL, secret
-- rotation, MCP tool writes). Values are stored post-redaction.
-- ====================================
CREATE TABLE audit_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  actor_user_id INT UNSIGNED NULL COMMENT 'Actor user.id (null for system)',

  action VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Action identifier (e.g., ai_provider.create)',
  resource_type VARCHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Target resource type',
  resource_public_id BINARY(16) NULL COMMENT 'Target resource public_id when available',
  ip_address VARBINARY(16) NULL COMMENT 'Packed IPv4/IPv6 address',
  user_agent VARCHAR(512) NULL COMMENT 'Client user agent',
  metadata_json JSON NULL COMMENT 'Redacted metadata (no secrets, no raw keys)',
  occurred_at DATETIME NOT NULL COMMENT 'Logical occurrence time (second precision; ties broken by id)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_audit_logs_public_id (public_id),
  KEY idx_audit_logs_workspace_id_occurred_at (workspace_id, occurred_at),
  KEY idx_audit_logs_workspace_id_action (workspace_id, action),

  CONSTRAINT fk_audit_logs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Workspace audit log';

-- >>> comments.sql
-- ====================================
-- comments
-- Discussion thread attached to a task. Markdown body with edit history
-- captured via edited_at (full revisions out of scope).
-- ====================================
CREATE TABLE comments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id',
  author_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',

  body MEDIUMTEXT NOT NULL COMMENT 'Markdown body',
  edited_at DATETIME NULL COMMENT 'Last edit time (null = never edited)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_comments_public_id (public_id),
  KEY idx_comments_workspace_id_task_id (workspace_id, task_id),
  KEY idx_comments_workspace_id_author_id (workspace_id, author_id),
  FULLTEXT KEY ft_comments_body (body),

  CONSTRAINT fk_comments_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Task discussion comments';

-- >>> events.sql
-- ====================================
-- events
-- Append-only event log. All workspace state transitions flow through this
-- table. The API offers no DELETE endpoint; purgeWorkspace is the sole
-- deletion path (test fixtures only).
-- ====================================
CREATE TABLE events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  task_id INT UNSIGNED NULL COMMENT 'Internal FK to tasks.id when the event targets a task',
  actor_user_id INT UNSIGNED NULL COMMENT 'Acting user.id (null for system/bot actions)',

  type VARCHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Event type (e.g., task.created, signal.attached)',
  payload_json JSON NOT NULL COMMENT 'Event payload',
  occurred_at DATETIME NOT NULL COMMENT 'Logical time of the event (second precision; ties broken by id)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_events_public_id (public_id),
  KEY idx_events_workspace_id_occurred_at (workspace_id, occurred_at),
  KEY idx_events_workspace_id_task_id_occurred_at (workspace_id, task_id, occurred_at),
  KEY idx_events_workspace_id_type (workspace_id, type),

  CONSTRAINT fk_events_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_events_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Append-only event log';

-- >>> identities.sql
-- ====================================
-- identities
-- Authentication credentials for users. A user can have multiple
-- identities: one local (password) plus zero or more OIDC providers.
-- ====================================
CREATE TABLE identities (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',

  provider ENUM('local','google','github','microsoft','generic_oidc') NOT NULL COMMENT 'Identity provider kind',
  subject VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Provider subject / external ID (ASCII)',
  password_hash CHAR(97) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'Argon2id encoded hash, only for provider=local', -- argon2id encoded form (97 chars)
  mfa_secret_ciphertext VARBINARY(512) NULL COMMENT 'Encrypted TOTP secret (AES-256-GCM)',
  mfa_confirmed_at DATETIME NULL COMMENT 'When the TOTP enrollment was confirmed by submitting a valid code',
  failed_attempts INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Consecutive failed login attempts',
  locked_until_at DATETIME NULL COMMENT 'Lockout expiry timestamp',
  last_used_at DATETIME NULL COMMENT 'Last successful authentication time',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_identities_public_id (public_id),
  UNIQUE KEY uniq_identities_provider_subject (provider, subject),
  KEY idx_identities_user_id (user_id),

  CONSTRAINT fk_identities_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User authentication identities';

-- >>> instance_admins.sql
-- ====================================
-- instance_admins
-- Instance-wide admin grants. NOT workspace-scoped: an instance admin can
-- act across every workspace on this deployment.
-- ====================================
CREATE TABLE instance_admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',
  granted_by_user_id INT UNSIGNED NULL COMMENT 'Internal FK to users.id (granter, null for bootstrap)',

  granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time the grant was created',
  revoked_at DATETIME NULL COMMENT 'Explicit revocation time',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_instance_admins_public_id (public_id),
  UNIQUE KEY uniq_instance_admins_user_id (user_id),

  CONSTRAINT fk_instance_admins_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_instance_admins_granted_by FOREIGN KEY (granted_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Instance-wide admin grants';

-- >>> instance_audit_logs.sql
-- ====================================
-- instance_audit_logs
-- Instance-wide audit trail for operations that cross workspaces or affect
-- the deployment itself (instance admin grants, workspace create/delete,
-- global setting changes). Not workspace-scoped.
-- ====================================
CREATE TABLE instance_audit_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  actor_user_id INT UNSIGNED NULL COMMENT 'Actor user.id (null for system)',

  action VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Action identifier (e.g., instance_admin.grant)',
  target_workspace_id INT UNSIGNED NULL COMMENT 'Affected workspace.id when applicable',
  target_resource_type VARCHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'Target resource type',
  target_resource_public_id BINARY(16) NULL COMMENT 'Target resource public_id when available',
  ip_address VARBINARY(16) NULL COMMENT 'Packed IPv4/IPv6 address',
  user_agent VARCHAR(512) NULL COMMENT 'Client user agent',
  payload_json JSON NULL COMMENT 'Redacted payload (no secrets)',
  occurred_at DATETIME NOT NULL COMMENT 'Logical occurrence time (second precision; ties broken by id)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_instance_audit_logs_public_id (public_id),
  KEY idx_instance_audit_logs_occurred_at (occurred_at),
  KEY idx_instance_audit_logs_action (action),
  KEY idx_instance_audit_logs_target_workspace_id (target_workspace_id),

  CONSTRAINT fk_instance_audit_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_instance_audit_logs_workspace FOREIGN KEY (target_workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Instance-wide audit log';

-- >>> mcp_invocations.sql
-- ====================================
-- mcp_invocations
-- Audit record for every MCP tool invocation. Arguments and results are
-- stored post-redaction (no raw secrets).
-- ====================================
CREATE TABLE mcp_invocations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  user_id INT UNSIGNED NULL COMMENT 'Internal FK to users.id (PAT owner)',
  task_id INT UNSIGNED NULL COMMENT 'Internal FK to tasks.id when applicable',

  tool_name VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'MCP tool name (e.g., create_task)',
  arguments_redacted_json JSON NOT NULL COMMENT 'Redacted arguments',
  result_redacted_json JSON NULL COMMENT 'Redacted result payload',
  status ENUM('ok','error','denied') NOT NULL COMMENT 'Outcome',
  error_code VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'Error code when status != ok',
  duration_ms INT UNSIGNED NULL COMMENT 'Wall-clock duration in milliseconds',
  invoked_at DATETIME NOT NULL COMMENT 'Invocation start time (second precision)',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_mcp_invocations_public_id (public_id),
  KEY idx_mcp_invocations_workspace_id_invoked_at (workspace_id, invoked_at),
  KEY idx_mcp_invocations_workspace_id_user_id (workspace_id, user_id),

  CONSTRAINT fk_mcp_invocations_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_invocations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_mcp_invocations_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MCP tool invocation audit';

-- >>> mcp_tokens.sql
-- ====================================
-- mcp_tokens
-- Personal access tokens used by MCP clients (Claude Desktop, mcp-cli, ...).
-- Only the SHA-256 hash is stored.
-- ====================================
CREATE TABLE mcp_tokens (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id (token owner)',
  agent_id INT UNSIGNED NULL COMMENT 'Internal FK to ai_agents.id when the token acts on behalf of an AI agent (2.MCP-2)',

  name VARCHAR(255) NOT NULL COMMENT 'Human-readable label',
  token_hash CHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'SHA-256 hex of the bearer token',
  token_prefix CHAR(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Leading chars shown as hint',
  scopes_json JSON NOT NULL COMMENT 'Array of granted MCP tool scopes',
  expires_at DATETIME NULL COMMENT 'Expiry time (null = never)',
  last_used_at DATETIME NULL COMMENT 'Last successful use',
  revoked_at DATETIME NULL COMMENT 'Explicit revocation time',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_mcp_tokens_public_id (public_id),
  UNIQUE KEY uniq_mcp_tokens_token_hash (token_hash),
  KEY idx_mcp_tokens_workspace_id_user_id (workspace_id, user_id),

  CONSTRAINT fk_mcp_tokens_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_tokens_agent FOREIGN KEY (agent_id) REFERENCES ai_agents(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MCP personal access tokens';

-- >>> oauth_states.sql
-- ====================================
-- oauth_states
-- Short-lived CSRF-protection state tokens for the personal OAuth
-- flow (POST /me/integrations/{provider}/connect → GET /oauth/
-- callback/{provider}). A row is inserted when the user clicks
-- "Connect", and deleted atomically when the callback handler
-- consumes the matching state. Rows expire after 15 minutes; the
-- callback refuses stale rows.
-- ====================================
CREATE TABLE oauth_states (
  state CHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL PRIMARY KEY COMMENT 'Random 32-byte token, hex-encoded',

  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id — the user who started the connect flow',
  provider ENUM('github','slack','google_calendar') NOT NULL COMMENT 'Which provider this state belongs to',
  redirect_to VARCHAR(512) NULL COMMENT 'Optional client-supplied return URL to send the user to after the callback completes',

  expires_at DATETIME NOT NULL COMMENT 'Hard expiry; callback handler rejects rows past this timestamp',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  KEY idx_oauth_states_expires_at (expires_at),

  CONSTRAINT fk_oauth_states_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Short-lived OAuth CSRF state tokens for personal integrations';

-- >>> personal_access_tokens.sql
-- ====================================
-- personal_access_tokens
-- User-scoped API tokens for the REST API and CLI (`tnk`).
-- Only the SHA-256 hash of the bearer token is stored; the plaintext is
-- shown to the user exactly once at creation time.
-- ====================================
CREATE TABLE personal_access_tokens (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id (token owner)',

  name VARCHAR(255) NOT NULL COMMENT 'Human-readable label',
  token_hash CHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'SHA-256 hex of the bearer token',
  token_prefix CHAR(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Leading chars shown as hint',
  scopes_json JSON NOT NULL COMMENT 'Array of granted API scopes',
  expires_at DATETIME NULL COMMENT 'Expiry time (null = never)',
  last_used_at DATETIME NULL COMMENT 'Last successful use',
  revoked_at DATETIME NULL COMMENT 'Explicit revocation time',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_personal_access_tokens_public_id (public_id),
  UNIQUE KEY uniq_personal_access_tokens_token_hash (token_hash),
  KEY idx_personal_access_tokens_workspace_id_user_id (workspace_id, user_id),

  CONSTRAINT fk_personal_access_tokens_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_personal_access_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User personal access tokens for REST/CLI';

-- >>> project_members.sql
-- ====================================
-- project_members
-- Project-level access override. A user must already be a workspace_member.
-- ====================================
CREATE TABLE project_members (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  project_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to projects.id',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',

  role ENUM('lead','editor','commenter','viewer') NOT NULL DEFAULT 'editor' COMMENT 'Project-level role',
  added_at DATETIME NULL COMMENT 'Time added to project',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_project_members_public_id (public_id),
  UNIQUE KEY uniq_project_members_project_id_user_id (project_id, user_id),
  KEY idx_project_members_workspace_id_user_id (workspace_id, user_id),

  CONSTRAINT fk_project_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_project_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Project membership';

-- >>> projects.sql
-- ====================================
-- projects
-- Workspace-scoped container for tasks.
-- ====================================
CREATE TABLE projects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',

  slug VARCHAR(63) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Workspace-local slug',
  name VARCHAR(255) NOT NULL COMMENT 'Display name',
  description TEXT NULL COMMENT 'Optional description',
  color VARCHAR(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'Hex color (e.g., #1abc9c)',
  is_archived BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Archived flag (distinct from enabled)',
  started_on DATE NULL COMMENT 'Project start date',
  ended_on DATE NULL COMMENT 'Project end date',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_projects_public_id (public_id),
  UNIQUE KEY uniq_projects_workspace_id_slug (workspace_id, slug),
  KEY idx_projects_workspace_id_enabled (workspace_id, enabled),

  CONSTRAINT fk_projects_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Task container';

-- >>> sessions.sql
-- ====================================
-- sessions
-- Refresh-token backed user sessions. Access tokens are stateless JWT;
-- this table only tracks the refresh token hash and its metadata.
-- ====================================
CREATE TABLE sessions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',

  refresh_hash CHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'SHA-256 hex of refresh token',
  user_agent VARCHAR(512) NULL COMMENT 'Client user agent at issue time',
  ip_address VARBINARY(16) NULL COMMENT 'Packed IPv4/IPv6 address at issue time',
  expires_at DATETIME NOT NULL COMMENT 'Refresh token expiry',
  revoked_at DATETIME NULL COMMENT 'Explicit revocation time',
  last_used_at DATETIME NULL COMMENT 'Last refresh time',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_sessions_public_id (public_id),
  UNIQUE KEY uniq_sessions_refresh_hash (refresh_hash),
  KEY idx_sessions_user_id_expires_at (user_id, expires_at),

  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Refresh-token backed sessions';

-- >>> signals.sql
-- ====================================
-- signals
-- External or manually submitted signals (webhooks, manual drops) that may
-- be normalized and attached to a task. Optionally linked to a task.
-- ====================================
CREATE TABLE signals (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  task_id INT UNSIGNED NULL COMMENT 'Internal FK to tasks.id, if resolved',

  source ENUM('manual','github','slack','email','google','webhook') NOT NULL COMMENT 'Originating channel',
  kind VARCHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Source-specific event kind (e.g., pull_request.opened)',
  external_id VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL COMMENT 'External identifier (delivery id, message ts, ...)',
  payload_json JSON NOT NULL COMMENT 'Raw normalized payload',
  received_at DATETIME NOT NULL COMMENT 'Time the signal was received',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_signals_public_id (public_id),
  KEY idx_signals_workspace_id_received_at (workspace_id, received_at),
  KEY idx_signals_workspace_id_task_id (workspace_id, task_id),
  KEY idx_signals_source_external_id (source, external_id),

  CONSTRAINT fk_signals_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_signals_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Inbound signals';

-- >>> task_actors.sql
-- ====================================
-- task_actors
-- Users attached to a task in a given role (assignee, reviewer, etc.).
-- ====================================
CREATE TABLE task_actors (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id',
  user_id INT UNSIGNED NULL COMMENT 'Internal FK to users.id (null when this row is an AI agent actor)',
  agent_id INT UNSIGNED NULL COMMENT 'Internal FK to ai_agents.id (null when this row is a human actor)',
  kind ENUM('user','agent') NOT NULL DEFAULT 'user' COMMENT 'Actor kind — user or AI agent (2.MCP-2)',

  role ENUM('assignee','reviewer','watcher','approver') NOT NULL DEFAULT 'assignee' COMMENT 'Actor role on the task',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_task_actors_public_id (public_id),
  UNIQUE KEY uniq_task_actors_task_id_user_id_role (task_id, user_id, role),
  UNIQUE KEY uniq_task_actors_task_id_agent_id_role (task_id, agent_id, role),
  KEY idx_task_actors_workspace_id_user_id (workspace_id, user_id),
  KEY idx_task_actors_workspace_id_agent_id (workspace_id, agent_id),

  CONSTRAINT fk_task_actors_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_actors_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_actors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_actors_agent FOREIGN KEY (agent_id) REFERENCES ai_agents(id) ON DELETE CASCADE,
  CONSTRAINT chk_task_actors_kind_target CHECK (
    (kind = 'user'  AND user_id  IS NOT NULL AND agent_id IS NULL) OR
    (kind = 'agent' AND agent_id IS NOT NULL AND user_id  IS NULL)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Task actors (assignees/reviewers/...)';

-- >>> task_constraints.sql
-- ====================================
-- task_constraints
-- Declarative conditions attached to a task. The constraint engine
-- evaluates these in combination with events to derive task state.
-- ====================================
CREATE TABLE task_constraints (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id',

  kind ENUM('deadline','dependency','approval','signal','custom') NOT NULL COMMENT 'Constraint kind',
  expression TEXT NOT NULL COMMENT 'Engine-specific expression (JSON-ish DSL)',
  satisfied_at DATETIME NULL COMMENT 'Time the constraint was first satisfied',
  failed_at DATETIME NULL COMMENT 'Time the constraint was last evaluated as failing',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_task_constraints_public_id (public_id),
  KEY idx_task_constraints_workspace_id_task_id (workspace_id, task_id),

  CONSTRAINT fk_task_constraints_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_constraints_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Task constraints';

-- >>> task_dependencies.sql
-- ====================================
-- task_dependencies
-- Directed edges between tasks. from_task blocks/relates to to_task.
-- ====================================
CREATE TABLE task_dependencies (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  from_task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id (source)',
  to_task_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id (target)',

  kind ENUM('blocks','relates','duplicates','subtask_of') NOT NULL DEFAULT 'blocks' COMMENT 'Dependency kind',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_task_dependencies_public_id (public_id),
  UNIQUE KEY uniq_task_dependencies_edge (from_task_id, to_task_id, kind),
  KEY idx_task_dependencies_workspace_id_to_task_id (workspace_id, to_task_id),

  CONSTRAINT fk_task_dependencies_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_dependencies_from FOREIGN KEY (from_task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_dependencies_to FOREIGN KEY (to_task_id) REFERENCES tasks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Directed task dependencies';

-- >>> task_embeddings.sql
-- ====================================
-- task_embeddings
-- Per ADR 0003: native MySQL 9.x VECTOR storage for duplicate detection.
-- Vectors are L2-normalized before insert so cosine similarity reduces
-- to a dot product. (task_id, model) composite PK lets two models
-- coexist during a rolling re-embed; the duplicate-detection query
-- pins WHERE model = :current_model to avoid mixing vector spaces.
--
-- Internal plumbing only: never crosses the API boundary, so no
-- public_id / workspace_id columns. Workspace scoping is reached via
-- the FK to tasks(id) (ON DELETE CASCADE).
-- ====================================
CREATE TABLE task_embeddings (
  task_id      INT UNSIGNED NOT NULL COMMENT 'Internal FK to tasks.id',
  model        VARCHAR(64)  NOT NULL COMMENT 'Embedding model key, e.g. mock-768',
  dim          SMALLINT UNSIGNED NOT NULL COMMENT 'Vector dimensionality (redundant with type today)',
  vector       VECTOR(768)  NOT NULL COMMENT 'L2-normalized embedding vector',
  content_hash CHAR(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'SHA-256 hex of embedded text',
  embedded_at  DATETIME(3)  NOT NULL COMMENT 'Last embed time',

  PRIMARY KEY (task_id, model),
  INDEX idx_task_embeddings_model_embedded_at (model, embedded_at),

  CONSTRAINT fk_task_embeddings_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Task embedding vectors for duplicate detection (ADR 0003)';

-- >>> tasks.sql
-- ====================================
-- tasks
-- nodate-flow's central object. derived_state is computed from
-- constraints + events and MUST NOT be updated directly by the API;
-- the event bus is the sole writer.
-- ====================================
CREATE TABLE tasks (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  project_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to projects.id',
  parent_task_id INT UNSIGNED NULL COMMENT 'Self-reference for subtasks',
  created_by_user_id INT UNSIGNED NULL COMMENT 'Creator user.id',

  title VARCHAR(255) NOT NULL COMMENT 'Task title',
  description MEDIUMTEXT NULL COMMENT 'Markdown body',
  derived_state ENUM('open','waiting','review','done','cancelled') NOT NULL DEFAULT 'open' COMMENT 'Computed from constraints + events; do NOT update directly',
  priority INT NOT NULL DEFAULT 0 COMMENT 'LLM-optimized heuristic priority',
  due_on DATE NULL COMMENT 'Due date',
  started_on DATE NULL COMMENT 'Started date',
  completed_at DATETIME NULL COMMENT 'Time derived_state transitioned to done',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_tasks_public_id (public_id),
  KEY idx_tasks_workspace_id_project_id (workspace_id, project_id),
  KEY idx_tasks_workspace_id_due_on (workspace_id, due_on),
  KEY idx_tasks_workspace_id_derived_state (workspace_id, derived_state),
  KEY idx_tasks_parent_task_id (parent_task_id),
  FULLTEXT KEY ft_tasks_title_description (title, description),

  CONSTRAINT fk_tasks_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_tasks_parent FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
  CONSTRAINT fk_tasks_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='nodate-flow core task object';

-- >>> user_integrations.sql
-- ====================================
-- user_integrations
-- Personal OAuth connections (GitHub / Slack / Google Calendar) owned
-- by an individual user. Separate from workspace-level integrations
-- managed by @mcp. Tokens are encrypted with NF_SECRET_KEY (same
-- cipher as the AI provider credentials).
-- ====================================
CREATE TABLE user_integrations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',

  provider ENUM('github','slack','google_calendar') NOT NULL COMMENT 'OAuth provider kind',
  external_account_id VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Provider subject (GH login, Slack user id, Google sub)',
  external_account_label VARCHAR(255) NOT NULL COMMENT 'Display-only label (email or @handle)',
  scopes TEXT NOT NULL COMMENT 'Space-separated list of granted OAuth scopes',

  access_token_ciphertext VARBINARY(4096) NOT NULL COMMENT 'AES-256-GCM encrypted access token',
  refresh_token_ciphertext VARBINARY(4096) NULL COMMENT 'AES-256-GCM encrypted refresh token (nullable: GitHub OAuth apps do not issue one)',
  access_token_expires_at DATETIME NULL COMMENT 'Access token expiry (providers that issue long-lived tokens leave this NULL)',

  connected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the user first authorised the app',
  last_refreshed_at DATETIME NULL COMMENT 'Last successful token refresh',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_user_integrations_public_id (public_id),
  UNIQUE KEY uniq_user_integrations_user_provider (user_id, provider),
  KEY idx_user_integrations_user_id (user_id),

  CONSTRAINT fk_user_integrations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Personal OAuth integrations owned by an individual user';

-- >>> user_recovery_codes.sql
-- ====================================
-- user_recovery_codes
-- One-time recovery codes used to bypass TOTP at login when the user
-- loses access to their authenticator app. Codes are stored as
-- SHA-256 hashes; the plaintext is shown to the user only once at
-- generation time.
-- ====================================
CREATE TABLE user_recovery_codes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',
  code_hash BINARY(32) NOT NULL COMMENT 'SHA-256 of the normalized recovery code',
  used_at DATETIME NULL COMMENT 'Set when the code is consumed at login',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_user_recovery_codes_user_hash (user_id, code_hash),
  KEY idx_user_recovery_codes_user_used (user_id, used_at),

  CONSTRAINT fk_user_recovery_codes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TOTP recovery codes';

-- >>> users.sql
-- ====================================
-- users
-- Account-level principals. Authenticated via identities (local/oidc).
-- Not workspace-scoped; users are global and join workspaces via workspace_members.
-- ====================================
CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',

  email VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Primary email, ASCII only',
  email_verified_at DATETIME NULL COMMENT 'Email verification timestamp',
  display_name VARCHAR(255) NOT NULL COMMENT 'Human-readable name',
  avatar_url VARCHAR(1024) NULL COMMENT 'Avatar image URL',
  locale VARCHAR(16) NOT NULL DEFAULT 'en' COMMENT 'Preferred locale tag (BCP 47)',
  theme_preference ENUM('aurora-light','aurora-dark','dotline-light','dotline-dark','system') NOT NULL DEFAULT 'system' COMMENT 'UI theme preference',
  last_login_at DATETIME NULL COMMENT 'Last successful login',

  -- Notification channel toggles (see /settings/notifications).
  notif_email_digest_enabled     BOOLEAN NOT NULL DEFAULT TRUE  COMMENT 'Weekly digest email',
  notif_email_mention_enabled    BOOLEAN NOT NULL DEFAULT TRUE  COMMENT 'Email when mentioned in comments',
  notif_email_assignment_enabled BOOLEAN NOT NULL DEFAULT TRUE  COMMENT 'Email when assigned to a task',
  notif_email_due_soon_enabled   BOOLEAN NOT NULL DEFAULT TRUE  COMMENT 'Email when owned task is due within 24h',
  notif_web_push_enabled         BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Browser push notifications',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_users_public_id (public_id),
  UNIQUE KEY uniq_users_email (email),
  KEY idx_users_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Global user accounts';

-- >>> workspace_members.sql
-- ====================================
-- workspace_members
-- M:N between workspaces and users with a workspace-scoped role.
-- ====================================
CREATE TABLE workspace_members (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',
  workspace_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to workspaces.id',
  user_id INT UNSIGNED NOT NULL COMMENT 'Internal FK to users.id',

  role ENUM('owner','admin','member','guest') NOT NULL DEFAULT 'member' COMMENT 'Workspace-level role',
  invited_by_user_id INT UNSIGNED NULL COMMENT 'Inviter user.id',
  invited_at DATETIME NULL COMMENT 'Invitation time',
  joined_at DATETIME NULL COMMENT 'Acceptance time',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_workspace_members_public_id (public_id),
  UNIQUE KEY uniq_workspace_members_workspace_id_user_id (workspace_id, user_id),
  KEY idx_workspace_members_user_id (user_id),

  CONSTRAINT fk_workspace_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_workspace_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_workspace_members_inviter FOREIGN KEY (invited_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Workspace membership';

-- >>> workspaces.sql
-- ====================================
-- workspaces
-- Top-level tenant boundary. Every workspace-scoped table carries
-- workspace_id as its leading composite index column.
-- ====================================
CREATE TABLE workspaces (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'Internal PK, never exposed',
  public_id BINARY(16) NOT NULL COMMENT 'UUID v7, the only externally visible ID',

  slug VARCHAR(63) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'DNS-label slug (RFC 1035)',
  name VARCHAR(255) NOT NULL COMMENT 'Display name',
  description TEXT NULL COMMENT 'Optional description',
  icon_url VARCHAR(1024) NULL COMMENT 'Icon image URL',

  sort_weight INT NOT NULL DEFAULT 0 COMMENT 'Display order',
  notes TEXT NULL COMMENT 'Admin notes',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Enabled flag',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uniq_workspaces_public_id (public_id),
  UNIQUE KEY uniq_workspaces_slug (slug),
  KEY idx_workspaces_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tenant boundary';

DROP VIEW IF EXISTS `v_audit_recent`;
DROP VIEW IF EXISTS `v_inbox`;
DROP VIEW IF EXISTS `v_my_tasks`;
DROP VIEW IF EXISTS `v_project_stats`;
DROP VIEW IF EXISTS `v_projects`;
DROP VIEW IF EXISTS `v_task_detail`;
DROP VIEW IF EXISTS `v_task_list`;
DROP VIEW IF EXISTS `v_task_timeline`;
DROP VIEW IF EXISTS `v_users`;
DROP VIEW IF EXISTS `v_workspace_members`;

-- >>> v_audit_recent.sql
-- v_audit_recent
-- Recent audit events projected for the admin UI. api_key values are
-- never present here; metadata_json is already redacted at write time.
CREATE OR REPLACE VIEW v_audit_recent AS
SELECT
  al.workspace_id,
  al.public_id,
  actor.public_id AS actor_user_public_id,
  actor.display_name AS actor_display_name,
  al.action,
  al.resource_type,
  al.resource_public_id,
  al.ip_address,
  al.user_agent,
  al.metadata_json,
  al.occurred_at
FROM audit_logs al
INNER JOIN workspaces w
  ON w.id = al.workspace_id AND w.enabled = TRUE
LEFT JOIN users actor
  ON actor.id = al.actor_user_id AND actor.enabled = TRUE
WHERE al.enabled = TRUE;

-- >>> v_inbox.sql
-- v_inbox
-- Aggregated inbox: signals that have arrived in a workspace with optional
-- task linkage. Consumers filter by workspace_id and archive/snooze state.
CREATE OR REPLACE VIEW v_inbox AS
SELECT
  s.workspace_id,
  w.public_id AS workspace_public_id,
  s.public_id,
  t.public_id AS task_public_id,
  t.title AS task_title,
  s.source,
  s.kind,
  s.external_id,
  s.payload_json,
  s.received_at,
  s.updated_at,
  s.created_at
FROM signals s
INNER JOIN workspaces w
  ON w.id = s.workspace_id AND w.enabled = TRUE
LEFT JOIN tasks t
  ON t.id = s.task_id AND t.enabled = TRUE
WHERE s.enabled = TRUE;

-- >>> v_my_tasks.sql
-- v_my_tasks
-- Tasks where a user is attached as an actor. Consumers filter on
-- user_public_id in addition to workspace_id.
CREATE OR REPLACE VIEW v_my_tasks AS
SELECT
  t.workspace_id,
  t.public_id,
  u.public_id AS user_public_id,
  p.public_id AS project_public_id,
  p.name AS project_name,
  t.title,
  t.derived_state,
  t.priority,
  t.due_on,
  a.role AS actor_role,
  t.updated_at,
  t.created_at
FROM task_actors a
INNER JOIN tasks t
  ON t.id = a.task_id AND t.enabled = TRUE
INNER JOIN projects p
  ON p.id = t.project_id AND p.enabled = TRUE
INNER JOIN users u
  ON u.id = a.user_id AND u.enabled = TRUE
INNER JOIN workspaces w
  ON w.id = t.workspace_id AND w.enabled = TRUE
WHERE a.enabled = TRUE;

-- >>> v_project_stats.sql
-- v_project_stats
-- Aggregated task counts per project, grouped by derived_state.
CREATE OR REPLACE VIEW v_project_stats AS
SELECT
  p.workspace_id,
  p.public_id,
  p.name,
  COUNT(t.id) AS task_count,
  SUM(CASE WHEN t.derived_state = 'open' THEN 1 ELSE 0 END) AS open_count,
  SUM(CASE WHEN t.derived_state = 'waiting' THEN 1 ELSE 0 END) AS waiting_count,
  SUM(CASE WHEN t.derived_state = 'review' THEN 1 ELSE 0 END) AS review_count,
  SUM(CASE WHEN t.derived_state = 'done' THEN 1 ELSE 0 END) AS done_count,
  SUM(CASE WHEN t.derived_state = 'cancelled' THEN 1 ELSE 0 END) AS cancelled_count,
  MAX(t.updated_at) AS last_task_updated_at
FROM projects p
LEFT JOIN tasks t
  ON t.project_id = p.id AND t.enabled = TRUE
INNER JOIN workspaces w
  ON w.id = p.workspace_id AND w.enabled = TRUE
WHERE p.enabled = TRUE
GROUP BY p.workspace_id, p.public_id, p.name;

-- >>> v_projects.sql
-- v_projects
-- Project listing with basic metadata. Workspace-scoped.
CREATE OR REPLACE VIEW v_projects AS
SELECT
  p.workspace_id,
  p.public_id,
  p.slug,
  p.name,
  p.description,
  p.color,
  p.is_archived,
  p.started_on,
  p.ended_on,
  p.sort_weight,
  p.updated_at,
  p.created_at
FROM projects p
INNER JOIN workspaces w
  ON w.id = p.workspace_id AND w.enabled = TRUE
WHERE p.enabled = TRUE;

-- >>> v_task_detail.sql
-- v_task_detail
-- Detailed task projection. Aggregates constraint / dependency / actor
-- counts; full lists are fetched via dedicated queries.
CREATE OR REPLACE VIEW v_task_detail AS
SELECT
  t.workspace_id,
  w.public_id AS workspace_public_id,
  t.public_id,
  p.public_id AS project_public_id,
  p.name AS project_name,
  pt.public_id AS parent_task_public_id,
  creator.public_id AS created_by_user_public_id,
  t.title,
  t.description,
  t.derived_state,
  t.priority,
  t.due_on,
  t.started_on,
  t.completed_at,
  COUNT(DISTINCT c.id) AS constraint_count,
  COUNT(DISTINCT CASE WHEN c.satisfied_at IS NOT NULL THEN c.id END) AS constraint_satisfied_count,
  COUNT(DISTINCT d.id) AS dependency_count,
  COUNT(DISTINCT a.id) AS actor_count,
  t.sort_weight,
  t.updated_at,
  t.created_at
FROM tasks t
INNER JOIN projects p
  ON p.id = t.project_id AND p.enabled = TRUE
INNER JOIN workspaces w
  ON w.id = t.workspace_id AND w.enabled = TRUE
LEFT JOIN tasks pt
  ON pt.id = t.parent_task_id AND pt.enabled = TRUE
LEFT JOIN users creator
  ON creator.id = t.created_by_user_id AND creator.enabled = TRUE
LEFT JOIN task_constraints c
  ON c.task_id = t.id AND c.enabled = TRUE
LEFT JOIN task_dependencies d
  ON d.from_task_id = t.id AND d.enabled = TRUE
LEFT JOIN task_actors a
  ON a.task_id = t.id AND a.enabled = TRUE
WHERE t.enabled = TRUE
GROUP BY
  t.workspace_id,
  w.public_id,
  t.public_id,
  p.public_id,
  p.name,
  pt.public_id,
  creator.public_id,
  t.title,
  t.description,
  t.derived_state,
  t.priority,
  t.due_on,
  t.started_on,
  t.completed_at,
  t.sort_weight,
  t.updated_at,
  t.created_at;

-- >>> v_task_list.sql
-- v_task_list
-- Minimal task projection for list / board views.
CREATE OR REPLACE VIEW v_task_list AS
SELECT
  t.workspace_id,
  t.public_id,
  p.public_id AS project_public_id,
  p.name AS project_name,
  pt.public_id AS parent_task_public_id,
  t.title,
  t.derived_state,
  t.priority,
  t.due_on,
  t.started_on,
  t.completed_at,
  t.sort_weight,
  t.updated_at,
  t.created_at,
  (
    SELECT u.public_id
    FROM task_actors ta
    INNER JOIN users u ON u.id = ta.user_id AND u.enabled = TRUE
    WHERE ta.task_id = t.id
      AND ta.enabled = TRUE
      AND ta.role = 'assignee'
    ORDER BY ta.sort_weight ASC, ta.id ASC
    LIMIT 1
  ) AS primary_assignee_public_id,
  (
    SELECT COUNT(*)
    FROM task_actors ta
    WHERE ta.task_id = t.id
      AND ta.enabled = TRUE
      AND ta.role = 'assignee'
  ) AS assignee_count
FROM tasks t
INNER JOIN projects p
  ON p.id = t.project_id AND p.enabled = TRUE
INNER JOIN workspaces w
  ON w.id = t.workspace_id AND w.enabled = TRUE
LEFT JOIN tasks pt
  ON pt.id = t.parent_task_id AND pt.enabled = TRUE
WHERE t.enabled = TRUE;

-- >>> v_task_timeline.sql
-- v_task_timeline
-- Timeline of events related to tasks. Merges events with the owning
-- task's public_id so the UI can render without touching internal ids.
CREATE OR REPLACE VIEW v_task_timeline AS
SELECT
  e.workspace_id,
  e.id AS event_id,
  e.public_id,
  t.public_id AS task_public_id,
  p.public_id AS project_public_id,
  actor.public_id AS actor_user_public_id,
  actor.display_name AS actor_display_name,
  e.type,
  e.payload_json,
  e.occurred_at
FROM events e
INNER JOIN workspaces w
  ON w.id = e.workspace_id AND w.enabled = TRUE
LEFT JOIN tasks t
  ON t.id = e.task_id AND t.enabled = TRUE
LEFT JOIN projects p
  ON p.id = t.project_id AND p.enabled = TRUE
LEFT JOIN users actor
  ON actor.id = e.actor_user_id AND actor.enabled = TRUE
WHERE e.enabled = TRUE;

-- >>> v_users.sql
-- v_users
-- Workspace-scoped user projection. Joins workspace_members so the view
-- carries workspace_id for tenant guards. Internal ids are not selected.
CREATE OR REPLACE VIEW v_users AS
SELECT
  wm.workspace_id,
  u.public_id,
  u.email,
  u.display_name,
  u.avatar_url,
  u.locale,
  u.theme_preference,
  wm.role AS workspace_role,
  u.last_login_at,
  u.updated_at,
  u.created_at
FROM users u
INNER JOIN workspace_members wm
  ON wm.user_id = u.id AND wm.enabled = TRUE
INNER JOIN workspaces w
  ON w.id = wm.workspace_id AND w.enabled = TRUE
WHERE u.enabled = TRUE;

-- >>> v_workspace_members.sql
-- v_workspace_members
-- Workspace membership joined with user display fields.
CREATE OR REPLACE VIEW v_workspace_members AS
SELECT
  wm.workspace_id,
  wm.public_id,
  u.public_id AS user_public_id,
  u.email,
  u.display_name,
  u.avatar_url,
  wm.role,
  wm.invited_at,
  wm.joined_at,
  wm.updated_at,
  wm.created_at
FROM workspace_members wm
INNER JOIN users u
  ON u.id = wm.user_id AND u.enabled = TRUE
INNER JOIN workspaces w
  ON w.id = wm.workspace_id AND w.enabled = TRUE
WHERE wm.enabled = TRUE;

SET UNIQUE_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 1;
